In [1]:
import pandas as pd
import re
import json
import random

In [6]:
food_dir='dataset/gofood_dataset.csv'
prod_dir = 'dataset/tokopedia_product_reviews_2025.csv'
names_dir = 'dataset/Indonesian_Name_Dataset.csv'
makanan_dir = 'dataset/alergen_dataset.csv'
produk_dir = 'dataset/produk_tokopedia.csv'
menu_dir = 'dataset/Steakhouse_dataset.csv'

In [7]:
df_food = pd.read_csv(food_dir)
df_food.head()

,merchant_name,merchant_area,category,display,product,price,discount_price,isDiscount,description
0,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Almara Kopi (kopi Susu Gula Aren),20000.0,NaN,0,Sajian Kopi Susu Gula Aren Yang Berbeda Dari K...
1,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice Almara Kopi (kopi Susu Gula Aren),22000.0,NaN,0,Sajian Kopi Susu Gula Aren Yang Berbeda Dari K...
2,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Millsis,20000.0,NaN,0,Sajian Susu Coklat Milo Dengan Racikan Khas 3 ...
3,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice Millsis,20000.0,NaN,0,Sajian Susu Coklat Milo Dengan Racikan Khas 3 ...
4,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Millbro,22000.0,NaN,0,Sajian Susu Coklat Milo Plus Espresso Dengan R...

In [8]:
raw_food = df_food['product'].dropna().tolist()
raw_food

['Hot Almara Kopi (kopi Susu Gula Aren)',
 'Ice Almara Kopi (kopi Susu Gula Aren)',
 'Hot Millsis',
 'Ice Millsis',
 'Hot Millbro',
 'Ice Millbro',
 'Hot 330 Helateh',
 'Ice 330 Helateh',
 'Hot Ilusi Kopi',
 'Ice Ilusi Kopi',
 'Kopi Jelly',
 'Hot Americano',
 'Ice Americano',
 'Hot Latte',
 'Ice Latte',
 'Hot Cappucino',
 'Ice Cappucino',
 'Hot Mocacino',
 'Ice Mocacino',
 'Hot Caramel Latte',
 'Ice Frappucino',
 'Ice Caramel Latte',
 'Hot Hazelnut Latte',
 'Ice Hazelnut Latte',
 'Hot Vanilla Latte',
 'Ice Vanilla Latte',
 'Vietnam Drip',
 'Kopi Tarik',
 'Kopi Matcha',
 'Kopi Charcoal',
 'Hot Matcha',
 'Ice Matcha',
 'Hot Charcoal',
 'Ice Charcoal',
 'Hot Coklat',
 'Ice Coklat',
 'Hot Lemon Tea',
 'Ice Lemon Tea',
 'Ice Yakult Squash',
 'Kopi Beer',
 'Teh Jelly',
 'Lemon Squash',
 'Ocean Blue',
 'Chocomint',
 'Lychee Squash',
 'Chocoreo',
 'Pisang Lumer Coklat',
 'Roti Bakar',
 'Kentang Goreng',
 'Paket Ngemil 1',
 'Paket Ngemil 2',
 'Paket Ngemil 3',
 'Paket Mix Bento',
 'Paket Bento Shrimp Roll',
 'Paket Bento Ebi Furai',
 'Paket Bento Ekkado',
 'Paket Chicken Teriyaki',
 'Paket Chicken Blackpaper',
 'Paket Beff Teriyaki',
 'Paket Beff Blackpaper',
 'Paket Mie Ayam',
 'Paket Mie Ayam Bakso',
 'Paket Mie Yamin',
 'Paket Mie Yamin Bakso',
 'Hemat Berdua',
 'Hemat 1',
 'Hemat Combo 3',
 'Hemat Combo 2',
 'Hemat Combo 1',
 'Hemat Super 5',
 'Chicken Steak Pops',
 'Sirloin Steak Beef Pops',
 'Tenderloin Steak Beef Pop',
 'Chicken Crispy',
 'Tenderloin Crispy',
 'Sirloin Steak Crispy',
 'Chicken Double',
 'Sirloin Double',
 'Tenderloin Double',
 'Beef Steak',
 'Blackpepper',
 'Chicken Mushroom',
 'Chicken Pepper',
 'Sirloin Import 175 Gram',
 'Rib Eye Import 175 Gram',
 'Chicken Steak Geprek',
 'Sirloin Steak Geprek',
 'Tenderloin Steak Geprek',
 'Steak Cumi',
 'Steak Tuna Pepper',
 'Steak Tuna Mushroom',
 'Steak Dori Crispy',
 'Nasi',
 'Kuah Steak',
 'Chicken Drumstick',
 'Spaghetty',
 'Kentang Lokal',
 'Frenchfries',
 'Lemon Tea',
 'Es Tea Manis',
 'Lemon Squash',
 'Es Jeruk',
 'Teh Tawar',
 'Capucino Float',
 'Avocado Float',
 'Orange Float',
 'Milkshake Vanila',
 'Milkshake Strawberry',
 'Milkshake Coklat',
 'Milkshake Vanila Spesial',
 'Milkshake Coklat Spesial',
 'Milkshake Strawberry Spesial',
 'Orange',
 'Es Capucino',
 'Milkshake Mocca',
 'Milkshake Mocca Spesial',
 'Lemon Fresh',
 'Chicken Drumstick',
 'Tas ABUBA ( Max 5 Box )',
 'Lychee Popping Boba',
 'Peach Popping Boba',
 'Choco Volcano',
 'Oreo Fruit Blast',
 'Bread Pudding Classic',
 'Guava Juice',
 'Honeydew Juice',
 'Mango Juice',
 'Sourmint',
 'Soursop Juice',
 'Strawberry Juice',
 'Watermelon Juice',
 'Orange Juice',
 'Avocado Juice',
 'Oreo Milkshake',
 'Strawbeery Milkshake',
 'Vanilla Milkshake',
 'Chocolate Milkshake',
 'Ice Age Melt Down',
 'Lychee Tea',
 'Mojito Classic',
 'Peach Tea',
 'The Genjer',
 'The Passion',
 'Air Mineral',
 'Coca Cola',
 'Hot Chocolate',
 'Hot Lemonade',
 'Hot Tea',
 'Hot Tea Sweet',
 'Hot Lemontea',
 'Ice Chocolate',
 'Ice Lemonade',
 'Ice Tea',
 'Ice Tea Sweet',
 'Sprite',
 'Ice Lemontea',
 'Rib Eye Wagyu 4-5',
 'Rib Eye Wagyu 6-7',
 'Tenderloin Wagyu',
 'Sirloin Wagyu 4-5',
 'Sirloin Wagyu 6-7',
 'Tenderloin Local',
 'Tenderloin Nz',
 'Tenderloin Us',
 'Sirloin Nz',
 'Sirloin Us',
 'Sirloin Lokal',
 'Rib Eye Nz',
 'Rib Eye Us',
 'Lamb Chop Nz',
 'Battered Dory Fish Regular',
 'Battered Dory Spicy',
 'Salmon Steak',
 'Fish Bite Regular',
 'Fish Bite Spicy',
 'T-Bone Local',
 'T-Bone Nz',
 'Boneless Fried Chicken Regular',
 'Boneless Fried Chicken Spicy',
 'Grilled Chicken Steak',
 'Grilled Chicken Wings',
 'Chicken Pop Corn Regular',
 'Chicken Pop Corn Spicy',
 'Chicken Wings Crush Garlic',
 'Chicken Wings Crush Hot',
 'Chicken Pop Corn With Butter Rice',
 'Spaghetti Bolognese Kids Meal',
 'Grilled Meatball Vegetable & Potato',
 'Beef Patty Steak',
 'Grilled Meatball',
 'Mix Beef Rice',
 'Abuba Signature Salad',
 'Creamy Fun Fries',
 'Spicy Fun Fries',
 'Veggie Fruit Salad',
 'French Fries Original',
 'Veggie Fruit Salad With Sesame Dressing',
 'Beef Lasagna',
 'Fettuccine Carbonara',
 'Spaghetti Bolognese',
 'Sweet Corn',
 'Mix vegetables',
 'Potato Wedges',
 'Mashed Potato',
 'Mushroom Sauce',
 'Tartar Sauce',
 'Blackpepper Sauce',
 'Barbecue Sauce',
 'Lychee Popping Boba',
 'Peach Popping Boba',
 'Crunchy Vegan Fried Chicken Reg',
 'Crunchy Vegan Fried Chicken Spicy',
 'Vegan Beef Mix Rice',
 'Vegan Beef Steak',
 'Vegan Chi-Pop',
 'Vegan Chic Mix Rice',
 'Vegan Chicken Steak',
 'bakwan Sayur',
 'tempe Crispi',
 'tahu Jeletot',
 'tahu Pong',
 'risole',
 'Cireng',
 'piscok Lumer',
 'Gorengan Ubi',
 'Pisang Goreng',
 'Tape Goreng',
 'Tempe Basah',
 'Singkong Goreng',
 'Combro Ranjau',
 'Pisang Molen',
 'Loncom',
 'Lonsay',
 'Es Buah Segar',
 'Es Pukat',
 'Es Lemon Tea',
 'Es Nutri Sari,Es Cincau',
 'Es Nutri Sari,Jeruk Nipis',
 'Es Nutri Sari ,Sweet Mango',
 'Es Nutri Sari,Sweet Orange',
 'Es Nutri Sari,Sweet Guava',
 'Es Nutri Sari,Sirsak',
 'Es Nutri Sari,Jeruk Peras',
 'Es Nutri Sari,Anggur',
 'Es Nutri Sari,Leci',
 'Es Nutri Sari,Lemon Tea',
 'Es Nutri Sari,Blewah',
 'Nutri Sari,Es Rujak',
 'Es Capucino',
 'Bakso Ceker Mercon',
 'ceker Mercon',
 'Bakso Mercon',
 'Dimsum',
 'Tiam MIE',
 'TiamMie',
 'Nasi Goreng Sapi',
 'Kwetiaw Sapi',
 'Telur  CEPLOK',
 'Kwetiaw Kengci',
 'Ayam Full',
 'Nasi',
 'Ayam Dada',
 'Ayam Paha',
 'Kepala Ayam',
 'Ceker Ayam',
 'Ati Ampela Ayam',
 'Usus Ayam',
 'Ati Ampela Bebek',
 'Paha Bebek',
 'Kepala Bebek',
 'Dada Bebek',
 'Tempe',
 'Tahu',
 'Pete',
 'Peyek',
 'Kulit Ayam',
 'Sosis Kecil Bakar/ Goreng',
 'Sosis Bakar/Goreng Jumbo',
 'Sosis Bakar/Goreng Sedang Keju',
 'Sosis Bakar/goreng Sedang Lada Hitam',
 'Sosis Bakar/goreng Sedang Original',
 'lobster Bakar/goreng',
 'Cikuwa Bakar/goreng',
 'Dampling Cheese Bakar/goreng',
 'Bakso Bakar/Goreng',
 'bola Udang Bakar/Goreng',
 'CrabStik bakar',
 'Skelep Bakar/Goreng',
 'Baso Ikan bakar/goreng',
 'Bakso Salmon Bakar/Goreng',
 'Otak-otak Singapur Bakar/goreng',
 'Otak-otak Bakar/goreng',
 'udang bakar/Goreng',
 'Maklor ( Makaroni Telur)',
 'Cireng',
 'Tokoyaki  isi 5',
 'Telur Gulung Original',
 'Cilor Tusuk',
 'Telor Gulung Isi',
 'Sempol Isi 5',
 'Kaki Naga Isi 5',
 'Naget Cham  Isi 5',
 'Kentang Goreng',
 'Cilor (Aci Telor)',
 'Mielor (Mie Telur)',
 'Omlet (Mie + Telur)',
 'Martabak Telur Loyang',
 'Martabak Telur Terigu Loyang',
 'Martabak Telur Puyuh',
 'Lumpia Telor Ayam',
 'Lumpia Telor Bebek',
 'Otak-otak Kriuk',
 'Bakso Kriuk',
 'Makaroni Pedas',
 'kripik Kaca',
 'Makaroni Spiral',
 'es pop ice',
 'Es Teh Manis',
 'Es Milo',
 'Es Drink Beng-beng',
 'Aqua',
 'Es Good Day Cappucino',
 'Es Good Day Freeze',
 'Es Good Day Mocacino',
 'Dancow Panas/Dingin',
 'Indomi Kuah + Telur',
 'Indomie goreng + Telur',
 'Indomie Kuah + Bakso',
 'Indomie Soto Telur + Bakso Sosis',
 'Super Bihun Kuah Telur + Bakso',
 'Indomi Goreng Mix Ceker Mercon',
 'Indomie Goreng Mix Ceker+Bakso Mercon',
 'Indomie Soto  Telur + Ceker Mercon',
 'Otak-otak Mercon',
 'Bakso Mercon',
 'Ceker Mercon',
 'Ceker Mix Bakso Mercon',
 '275 Gr Tenderloin Beef With Truffle Sauce',
 'Chicken Croffle Truffle',
 'Single Serve Croffle with Ovomaltine',
 'Cinnamon Rolls Ovomaltine',
 'Ovomaltine Raspberry Tart',
 'Black Coffee 1 L',
 'Black Coffee 500 mL',
 'Kopi Nusantara 1 L',
 'Kopi Nusantara 500 mL',
 'Caffe Latte 1 L',
 'Caffe Latte 500 mL',
 'Almond Croissant',
 'Bacon & cheese croissant',
 'Butter croissant',
 'Choco lava croissant',
 'Nutella Pain au Chocolat',
 'Peanut butter & jelly croissant',
 'Salted egg yolk croissant',
 'Triple Cheese Croissant',
 'Truffle Mushroom croissant',
 'Garlic Cheese Bread',
 'Bacon & cheese quiche',
 'Spinach mushroom quiche',
 'Beef Pie',
 'Chicken Mushroom Pie',
 'Pain Au Raisin',
 'Pain Au Praline',
 'Vanilla Bomboloni',
 'Chocolate Brownies Bomboloni',
 'Biscoff Lotus Bomboloni',
 'Lemon Meringue Bomboloni',
 'Nutella Bomboloni',
 'Salted Caramel Bomboloni',
 'Peanut Butter & Jelly Bomboloni',
 'Strawberry Cheesecake Bomboloni',
 'Plain Croffle',
 'Cinnamon Sugar Croffle',
 'Maple Croffle',
 'Nutella Croffle',
 'Salted Caramel Croffle',
 'Biscoff Lotus Croffle',
 'Assorted Croffle Box of 8 pcs',
 'Peanut Butter & Jelly Croffle',
 'Kaya Toast Croffle',
 'Hot Espresso',
 'Hot Long Black / Americano',
 'Hot Macchiato / Piccolo',
 'Hot Cappucino / Flat White',
 'Hot Caffe Latte',
 'Hot Mocha',
 'Hot Magic',
 'Add Soy Milk',
 'Add Almond Milk',
 'Add Oat Milk',
 'Iced Americano',
 'Iced Caffe Latte',
 'Iced Caffe Latte with Vanilla Ice Cream',
 'Iced Mocha',
 'Iced Mocha with Chocolate Ice Cream',
 'Iced Matha Espresso Latte',
 'Classic Affogato',
 'Es Kopi Nusantara',
 'Kopi Nusantara Granita',
 'Loose Leaf Tea (English Breakfast, Earl Grey, Blackcurrant & Hibiscus, Lemongrass & Ginger, Chamomile, Peppermint)',
 'Matcha Latte',
 'Lychee / Peach / Strawberry Iced Tea',
 'Lemon Iced Tea',
 'Signature Chocolate',
 'Pure Orange Juice',
 'Pure Apple Juice',
 'Orange + Apple Juice',
 'Fresh Brewed Ice Tea',
 'Avocado Float',
 'Avocado Affogato',
 'Avocado with Kopi Nusantara Granita',
 'Loose Leaf Tea (Jasmine, French Vanilla, Rosebud)',
 'Triple Berry Smoothies',
 'Banana & Co Smoothies',
 'Mango Tango Smoothies',
 'Nashville Hot Chiken Wings',
 'House Fries',
 'Beef Brisket Ball',
 'Oriental Roasted Duck Bao',
 'Fried Calamari',
 'Spaghetti (Cacio e Pepe)',
 'Tagliatelle Oxtail Ragu',
 'Spagethetti Carbonara',
 'Clam Linguine',
 'Add Lobster Tail (For Mac And Cheese)',
 'Mac And Cheese',
 'Cavatelli',
 'Black Truffle Tagliarini',
 'Lasagna Verde',
 'Osso Buco Agnolotti',
 'Crab Spaghetti',
 'Charred Corn Ribs , Maple Chilli Sauce',
 'House , Parmesan',
 'Truffle Mashed Potato',
 'Asparagus , Hollandaise',
 'Creamed Or Wilted Spinach',
 'Steamed Sea Bass',
 'Balinese Fried Duck',
 'Chargrilled Cabe Ijo Short Ribs',
 'BBQ Char Siu Short Rib',
 'Nasi Goreng Gila',
 'Chargrilled Jumbo King Prawn',
 'Black Truffle Wagyu Beef Bowl',
 'Mushroom Soup',
 'Burrata',
 'Bakers Caesar',
 'New England Clam Chowder',
 'Cajun Rub Hot Smoked Salmon',
 'Buttermilk Fried Chicken Croffle',
 'Avocado Toast',
 'Bakers Breakfast',
 'Crab Omelette',
 'Scramble Egg & Foie Gras',
 'Baked Eggs',
 'Eeg Benedict',
 'Garlic Cheese',
 'Valrhona Chocolate Tart',
 'Verlhona Flourless Cake Tart',
 'Brie Caramel',
 'Pistachio Fragipane',
 'Pear Tart',
 'Peach Tart',
 'Lemon Tart',
 'Caramel Pecan',
 'Apple Tart',
 'Milk Chocolate  Hazelnut Fondant',
 'Croissant Eeg Tart',
 'Varlhona Dark Chocolate Fondant',
 'Dark Chocolate Fondant',
 'Crispy Skin Salmon',
 'Steak and Frites',
 'Half Roasted Chicken',
 'Nashville Fried Lobster & Chips',
 'Lobster Thermidor',
 'Black Angus Striploin 300gr',
 'Black Angus Ribeye 300gr',
 'Bourbon Beef & Bone Marrow Pie',
 'Black Angus Tenderloin 275gr',
 "Baker's Burger",
 'Lobster Roll',
 'Egg Sandwich',
 'Cheeseburger',
 'French Dip Roast Beef Sandwich',
 'Reuben Sandwich',
 'Elderflower Grape',
 'Berry Blast',
 'Jasmine Citrus Mojito',
 'Chamomile Strawberry Spritzer',
 'Lemongrass & Guava Sparkler',
 'Coffee Crumb Cinnamon Roll',
 'Lotus Biscoff Cinnamon Roll',
 'Choco Nutella Cinnamon Roll',
 'Peanut Nougat Cinnamon Roll',
 'Walnut Caramel Cinnamon Roll',
 'Bakmi Istimewa (3 Toppings)',
 'Bakmi Special (Bebek Peking + Ayam Kampung)',
 'Bakmi Bebek Peking',
 'Bakmi Campur (Ayam Kampung + Ayam Cincang)',
 'Bakmi Ayam Kampung',
 'Bakmi Ayam Cincang',
 'Bakmi Ayam Kampung Super Topping',
 'Bakmi Bebek Peking Super Topping',
 'Bakso Sapi 1 Porsi (10 Pcs)',
 'Bakso Sapi 1/2 Porsi (5 Pcs)',
 'Bakso Sapi (2 Pcs)',
 'Bakso Goreng',
 'Pangsit Rebus 1 Porsi (10 Pcs)',
 'Pangsit Rebus 1/2 Porsi (5 Pcs)',
 'Pangsit Rebus (2 Pcs)',
 'Bebek Peking 1 Ekor',
 'Bebek Peking 1/2 Ekor',
 'Bebek Peking 1/4 Ekor',
 'Ayam Kampung 1 Ekor',
 'Ayam Kampung 1/2 Ekor',
 'Ayam Kampung 1/4 Ekor',
 'Air Mineral 600 Ml',
 'Teh Pucuk',
 'Bakmi Rebus Kalimantan',
 'Bakmi Goreng Kalimantan',
 'Bakmi Kuah Kalimantan',
 'Bakmi Goreng Kari',
 'Bakmi Siram Kalimantan',
 'Kwetiaw Rebus Kalimantan',
 'Kwetiaw Goreng Kalimantan',
 'Kwetiaw Goreng Kari',
 'Kwetiaw Siram Kalimantan',
 'Bihun Rebus Kalimantan',
 'Bihun Goreng Kalimantan',
 'Nasi Goreng Kalimantan',
 'Nasi Goreng Kusut',
 'Nasi Goreng Singapore',
 'Nasi Goreng Kari',
 'Nasi Siram Kalimantan',
 'Nasi Telor Kalimantan',
 'Nasi Muntahu Lopui',
 'Locupan Jam',
 'Locupan Tek-Tek',
 'Pangsit Kuah Isi 5',
 'Pangsit Kuah Isi 10',
 'Pangsit Tek - Tek Isi 5',
 'Pangsit Tek - Tek Isi 10',
 'Susu Kacang 500ML',
 'Ayam Kampung Goreng Kremes',
 'Ayam Kampung Goreng Kremes + Nasi',
 'Bakso Mie Campur',
 'Bakso Soun/Bihun/Mie Kuning',
 'Bakso Spesial',
 'Bakso Kuah',
 'Bakso Urat Besar',
 'Bakso Telur',
 'Bakso Setengah Porsi',
 'Nasi Putih',
 'Mie Ayam Bakso',
 'Mie Ayam Bakso Pangsit',
 'Mie Ayam Bakso Pangsit + Urat Besar',
 'Mie Ayam Bakso Urat Besar',
 'Mie Ayam Pangsit',
 'Mie Ayam Pangsit + Urat Besar',
 'Mie Ayam',
 'Mie Ayam Bakso Telur',
 'Mie Ayam Pangsit + Bakso Telur',
 'Sop Daging Sapi',
 'Siomay',
 'Siomay Goreng',
 'Krupuk',
 'Kelapa Bulat ala Thailand',
 'Soda Susu',
 'Es Alpukat',
 'Es Kelapa Jeruk',
 'Es Alpukat Kelapa',
 'Es Campur',
 'Es Kelapa',
 'Es Jeruk',
 'Es Teh Manis',
 'Es Teh Tawar',
 'Teh Manis Panas',
 'Teh Tawar',
 'Jeruk Panas',
 'Lemon Tea',
 'Juas Buah Naga',
 'Jus Alpukat',
 'Jus Sirsak',
 'Jus Melon',
 'Jus Strawberry',
 'Jus Tomat',
 'Jus Jambu',
 'Air Mineral',
 'Coca Cola',
 'Sprite',
 'Fanta',
 'Fruite Tea',
 'Teh Botol',
 'Jus Mangga',
 'Prima Gelas',
 'Pulpy Orange',
 'Fresh Tea',
 'Happiness Bento Set 1',
 'Happiness Bento Set 2',
 'Oishii Set 1',
 'Oishii Set 2',
 'Chicken Katsu Curry Bento',
 'Chicken Karaage Nanban Bento',
 'Beef Hamburg Curry Rice',
 'Chicken Karaage Mentai Bento',
 'Cheesy Beef Cutlet Curry',
 'Fish Katsu Mentai Bento',
 'Double Hamburg Curry Rice',
 'Cheesy Hamburg Curry Rice',
 'Es Matcha Mindfulness',
 'Es Mango Yakult Jelly',
 'Es Lychee Yakult Jelly',
 'Cinnamon Roll',
 'Choco Lava Cake',
 'Dark Chocolate',
 'Tiramisu Cheesecake',
 'Chicken Karaage Curry Bento',
 'Chicken Katsu Nanban Bento',
 'Beef Teriyaki Bento',
 'Chicken Teriyaki Bento',
 'Chicken Katsu Mentai Bento',
 'Extra Cheesy Beef Cutlet Curry',
 'Cheesy Chicken Cutlet Curry',
 'Extra Cheesy Chicken Cutlet Curry',
 'Fish Katsu Nanban Bento',
 'Fish Katsu Curry Bento',
 'Hemat Set',
 'Ekkado Set',
 'Cheesy Chicken Set',
 'Chicken Katsu Set',
 'Chicken Popcorn Bento 1',
 'Chicken Popcorn Bento 2',
 'Coffee Brownie',
 'Almond Brownie',
 'Coconut Pandan',
 'Red Velvet',
 'Original Cheesecake',
 'Blueberry Cheesecake',
 'Raspberry Cheesecake',
 'Extra Sambal Sachet',
 'Extra Mayonnaise Sachet..',
 'Es Kopi Cheer Me Up',
 'Es Cokelat Cozy',
 'Es Teh Joyful',
 '1Ltr Es Kopi Cheer Me Up',
 'Mineral Water 330 Ml',
 'Es Sukur - Susu Kurma',
 'Es Cendol Ceria',
 'Coca-Cola',
 'Bakso Bakar',
 'Bakso Salmon Bakar',
 'Crabstick Bakar',
 'Dumpling Bakar',
 'Fishroll Bakar',
 'Ikan Kue Pedas Bakar',
 'Rolade Bakar',
 'Scallope Bakar',
 'Sosis Bakar',
 'Sosis Bakar Jumbo',
 'Tofu Seafood Bakar',
 'Chikuwa Bakar',
 'Otak - Otak Bakar',
 'Mie Oyeng',
 'Sosis + Kyentang Oyeng',
 'Kyentang Oyeng',
 'Sotang (Sosis Kentang) Oyeng',
 'Otak-otak Oyeng',
 'Bebek Goreng',
 'Bebek Belur Cabe Ijo',
 'Bebek Bakar Bumbu Rica',
 'Bebek Bakar Kacang',
 'Ayam Kota Goreng',
 'Ayam Kota Belur Cabe Ijo',
 'Ayam Kota Bakar Kacang',
 'Ayam Kota Bakar Rica',
 'Ayam Kampung Belur Cabe Ijo',
 'Ayam Kampung Goreng',
 'Ayam Kampung Bakar Kacang',
 'Ayam Kampung Bakar Rica',
 'Udang Goreng Tepung',
 'Cumi Goreng Tepung',
 'Cumi Tumis Cabe Ijo',
 'Udang Tumis Cabe Ijo',
 'Cumi Asin Tumis Cabe Ijo',
 'Nila Belur (Cabe Ijo)',
 'Nila Goreng.',
 'Nila Bakar Kacang',
 'Nila Bakar Rica',
 'Sayur Asem',
 'Cah Kangkung Polos',
 'Cah Kangkung Teri',
 'Cah Kangkung Seafood',
 'Terong Goreng Tepung',
 'Tumis Jamur Tiram',
 'Plencing Kangkung',
 'Telur Penyet',
 'Telur Dadar',
 'Sosis Goreng (2potong)',
 'Tahu Goreng (5potong)',
 'Tempe Goreng (5potong)',
 'Telur Bakar',
 'Sosis Bakar (2potong)',
 'Nasi A',
 'Nasi B',
 'Nasi Putih',
 'Sambal Korek',
 'Sambal Ijo',
 'Sambal Mangga',
 'Sambal Teri',
 'Sambal Terasi',
 'Sambal Terong',
 'Es Jeruk',
 'Jeruk Murni',
 'Es Lidah Buaya',
 'Es Timun',
 'Es Jeruk Nipis',
 'Es Lemon Tea',
 'Es Milo',
 'Mineral Botol',
 'Es Teh Manis',
 'Es Teh Tawar',
 'Es Alpukat Susu',
 'Jus Alpukat',
 'Teh Botol',
 'Es Kosong',
 'Es Mangga Boedjang',
 'Jus Mangga',
 'Bebek Goreng',
 'Bebek Belur Cabe Ijo',
 'Bebek Bakar Bumbu Rica',
 'Bebek Bakar Kacang',
 'Ayam Kota Goreng',
 'Ayam Kota Belur Cabe Ijo',
 'Ayam Kota Bakar Kacang',
 'Ayam Kota Bakar Rica',
 'Ayam Kampung Belur Cabe Ijo',
 'Ayam Kampung Goreng',
 'Ayam Kampung Bakar Kacang',
 'Ayam Kampung Bakar Rica',
 'Udang Goreng Tepung',
 'Cumi Goreng Tepung',
 'Cumi Tumis Cabe Ijo',
 'Udang Tumis Cabe Ijo',
 'Cumi Asin Tumis Cabe Ijo',
 'Nila Belur (Cabe Ijo)',
 'Nila Goreng.',
 'Nila Bakar Kacang',
 'Nila Bakar Rica',
 'Sayur Asem',
 'Cah Kangkung Polos',
 'Cah Kangkung Teri',
 'Cah Kangkung Seafood',
 'Terong Goreng Tepung',
 'Tumis Jamur Tiram',
 'Plencing Kangkung',
 'Telur Penyet',
 'Telur Dadar',
 'Sosis Goreng (2potong)',
 'Tahu Goreng (5potong)',
 'Tempe Goreng (5potong)',
 'Telur Bakar',
 'Sosis Bakar (2potong)',
 'Nasi A',
 'Nasi B',
 'Nasi Putih',
 'Sambal Korek',
 'Sambal Ijo',
 'Sambal Mangga',
 'Sambal Teri',
 'Sambal Terasi',
 'Sambal Terong',
 'Es Jeruk',
 'Jeruk Murni',
 'Es Lidah Buaya',
 'Es Timun',
 'Es Jeruk Nipis',
 'Es Lemon Tea',
 'Es Milo',
 'Mineral Botol',
 'Es Teh Manis',
 'Es Teh Tawar',
 'Es Alpukat Susu',
 'Jus Alpukat',
 'Teh Botol',
 'Es Kosong',
 'Es Mangga Boedjang',
 'Jus Mangga',
 'Original Topokki',
 'MozzarellaTopokki',
 'Kimmari Topokki',
 'Ganjeong Topokki',
 'Rapokki',
 'Roze Topokki',
 'Kimchi Kimbab',
 'Odeng',
 'Original Package',
 'Mozzarella Package',
 'Roze Package',
 'Sharing Package',
 'Kimchi Stir Friced Rice',
 'Bulgogi Rice',
 'A Bowl Of Rice',
 'Bulgogi Japchae',
 'Jeyuk Bokkeum',
 'Mineral Water',
 'Coke',
 'Sprite',
 'Chilsung Cider',
 'Milkis Banana',
 'Milkis Melon',
 'Milkis Milk',
 'Milkis Strawberry',
 'Lapis Original',
 'Cokelat Keju',
 'Bolu Susu Oreo',
 'Bolu Susu Red Velvet',
 'Cokelat',
 'Pandan Keju',
 'Full Talas',
 'Lapis Blackforest',
 'Brownis Glossy',
 'Black Forest Ukuran 11',
 'Black Forest Ukuran 15',
 'Red Valvet Ukuran 17',
 'Red Velvet 15',
 'Double Coklat Uk.15',
 'Lilin Magic',
 'Lilin Angka',
 'Black Forest Ukuran 17',
 'Black Forest Ukuran 19',
 'Red Velvet 11',
 'Tiramissu Uk.11',
 'Tiramissu Uk.15',
 'Tiramissu Uk.17',
 'Double Coklat Uk.11',
 'Double Coklat Uk.17',
 'Mocca Uk.11',
 'Mocca Uk.15',
 'Klepon 15',
 'Klepon 17',
 'Cake Cokelat',
 'Cake Tape',
 'Bogor Banana',
 'Kotak Cokelat',
 'Kotak Pandan',
 'Muffin Mini',
 'Donat Mini',
 'Bika Ambon',
 'Cake Pisang',
 'Cake Marmer',
 'Pisang Bolen Cokelat',
 'Cheese Stik',
 'Strudle Brownis',
 'Pisang Bolen Keju',
 'Banana Cheese Roll',
 'Swiss Roll Red Velvet',
 'Swiss Roll Cokelate Oreo',
 'Swiss Roll Keju',
 'Cream Keju',
 'Keju Susu',
 'Double Cheese',
 'Polo Cokelat Chip',
 'Strawberry Mountain',
 'Bluebarry Mountain',
 'Roti Kismis',
 'Long Cokelat',
 'Sarikaya',
 'Roti Unyil',
 'Roti Kacang Hijau',
 'Coklat Kacang',
 'Kacang Merah',
 'Kelapa Gula Malaka',
 'Long Cheese Cream',
 'Strawberry Cream',
 'Mocca',
 'Bluebarry Cheese Roll',
 'Sosis Cheese',
 'Smoke Beef',
 'Roti Pizza',
 'Coklat Roll',
 'Roti Coklat',
 'Roti Mickey',
 'Cream Coklat',
 'Kura Kura',
 'Cokelat Keju',
 'Roti Pisang',
 'Roti Bun',
 'Coklat Meksiko',
 'Coffe Caramel',
 'Abon Roll',
 'Abon Sapi',
 'Sobek Cokelat Combine',
 'Melxic Keju',
 'Melxic Coklat',
 'Sobek Sweet Cheese',
 'Sobek Smokeebeef',
 'Tawar Susu',
 'Tawar Cokelat',
 'Tawar Keju',
 'Lapis Black Forest',
 'Bogor Banana',
 'Swiss Roll Coklat Oreo',
 'Swiss Roll Keju',
 'Bolu Susu Oreo',
 'Bolu Susu Red Velvet',
 'Bika Ambon',
 'Brownies Glossy',
 'Cake Coklat',
 'Cake Marmer',
 'Cake Pisang',
 'Cake Tape',
 'Kotak Pandan',
 'Kotak Coklat',
 'Muffin Mini',
 'Swiss Roll Red Velvet',
 'Black Forest 18',

In [9]:
clean_gofood = []

for item in raw_food:
    item = re.sub(r'\(.*?\)', '', item).strip()

    short_item = " ".join(item.split()[:3]).lower()
    clean_gofood.append(short_item)

In [10]:
clean_gofood

['hot almara kopi',
 'ice almara kopi',
 'hot millsis',
 'ice millsis',
 'hot millbro',
 'ice millbro',
 'hot 330 helateh',
 'ice 330 helateh',
 'hot ilusi kopi',
 'ice ilusi kopi',
 'kopi jelly',
 'hot americano',
 'ice americano',
 'hot latte',
 'ice latte',
 'hot cappucino',
 'ice cappucino',
 'hot mocacino',
 'ice mocacino',
 'hot caramel latte',
 'ice frappucino',
 'ice caramel latte',
 'hot hazelnut latte',
 'ice hazelnut latte',
 'hot vanilla latte',
 'ice vanilla latte',
 'vietnam drip',
 'kopi tarik',
 'kopi matcha',
 'kopi charcoal',
 'hot matcha',
 'ice matcha',
 'hot charcoal',
 'ice charcoal',
 'hot coklat',
 'ice coklat',
 'hot lemon tea',
 'ice lemon tea',
 'ice yakult squash',
 'kopi beer',
 'teh jelly',
 'lemon squash',
 'ocean blue',
 'chocomint',
 'lychee squash',
 'chocoreo',
 'pisang lumer coklat',
 'roti bakar',
 'kentang goreng',
 'paket ngemil 1',
 'paket ngemil 2',
 'paket ngemil 3',
 'paket mix bento',
 'paket bento shrimp',
 'paket bento ebi',
 'paket bento ekkado',
 'paket chicken teriyaki',
 'paket chicken blackpaper',
 'paket beff teriyaki',
 'paket beff blackpaper',
 'paket mie ayam',
 'paket mie ayam',
 'paket mie yamin',
 'paket mie yamin',
 'hemat berdua',
 'hemat 1',
 'hemat combo 3',
 'hemat combo 2',
 'hemat combo 1',
 'hemat super 5',
 'chicken steak pops',
 'sirloin steak beef',
 'tenderloin steak beef',
 'chicken crispy',
 'tenderloin crispy',
 'sirloin steak crispy',
 'chicken double',
 'sirloin double',
 'tenderloin double',
 'beef steak',
 'blackpepper',
 'chicken mushroom',
 'chicken pepper',
 'sirloin import 175',
 'rib eye import',
 'chicken steak geprek',
 'sirloin steak geprek',
 'tenderloin steak geprek',
 'steak cumi',
 'steak tuna pepper',
 'steak tuna mushroom',
 'steak dori crispy',
 'nasi',
 'kuah steak',
 'chicken drumstick',
 'spaghetty',
 'kentang lokal',
 'frenchfries',
 'lemon tea',
 'es tea manis',
 'lemon squash',
 'es jeruk',
 'teh tawar',
 'capucino float',
 'avocado float',
 'orange float',
 'milkshake vanila',
 'milkshake strawberry',
 'milkshake coklat',
 'milkshake vanila spesial',
 'milkshake coklat spesial',
 'milkshake strawberry spesial',
 'orange',
 'es capucino',
 'milkshake mocca',
 'milkshake mocca spesial',
 'lemon fresh',
 'chicken drumstick',
 'tas abuba',
 'lychee popping boba',
 'peach popping boba',
 'choco volcano',
 'oreo fruit blast',
 'bread pudding classic',
 'guava juice',
 'honeydew juice',
 'mango juice',
 'sourmint',
 'soursop juice',
 'strawberry juice',
 'watermelon juice',
 'orange juice',
 'avocado juice',
 'oreo milkshake',
 'strawbeery milkshake',
 'vanilla milkshake',
 'chocolate milkshake',
 'ice age melt',
 'lychee tea',
 'mojito classic',
 'peach tea',
 'the genjer',
 'the passion',
 'air mineral',
 'coca cola',
 'hot chocolate',
 'hot lemonade',
 'hot tea',
 'hot tea sweet',
 'hot lemontea',
 'ice chocolate',
 'ice lemonade',
 'ice tea',
 'ice tea sweet',
 'sprite',
 'ice lemontea',
 'rib eye wagyu',
 'rib eye wagyu',
 'tenderloin wagyu',
 'sirloin wagyu 4-5',
 'sirloin wagyu 6-7',
 'tenderloin local',
 'tenderloin nz',
 'tenderloin us',
 'sirloin nz',
 'sirloin us',
 'sirloin lokal',
 'rib eye nz',
 'rib eye us',
 'lamb chop nz',
 'battered dory fish',
 'battered dory spicy',
 'salmon steak',
 'fish bite regular',
 'fish bite spicy',
 't-bone local',
 't-bone nz',
 'boneless fried chicken',
 'boneless fried chicken',
 'grilled chicken steak',
 'grilled chicken wings',
 'chicken pop corn',
 'chicken pop corn',
 'chicken wings crush',
 'chicken wings crush',
 'chicken pop corn',
 'spaghetti bolognese kids',
 'grilled meatball vegetable',
 'beef patty steak',
 'grilled meatball',
 'mix beef rice',
 'abuba signature salad',
 'creamy fun fries',
 'spicy fun fries',
 'veggie fruit salad',
 'french fries original',
 'veggie fruit salad',
 'beef lasagna',
 'fettuccine carbonara',
 'spaghetti bolognese',
 'sweet corn',
 'mix vegetables',
 'potato wedges',
 'mashed potato',
 'mushroom sauce',
 'tartar sauce',
 'blackpepper sauce',
 'barbecue sauce',
 'lychee popping boba',
 'peach popping boba',
 'crunchy vegan fried',
 'crunchy vegan fried',
 'vegan beef mix',
 'vegan beef steak',
 'vegan chi-pop',
 'vegan chic mix',
 'vegan chicken steak',
 'bakwan sayur',
 'tempe crispi',
 'tahu jeletot',
 'tahu pong',
 'risole',
 'cireng',
 'piscok lumer',
 'gorengan ubi',
 'pisang goreng',
 'tape goreng',
 'tempe basah',
 'singkong goreng',
 'combro ranjau',
 'pisang molen',
 'loncom',
 'lonsay',
 'es buah segar',
 'es pukat',
 'es lemon tea',
 'es nutri sari,es',
 'es nutri sari,jeruk',
 'es nutri sari',
 'es nutri sari,sweet',
 'es nutri sari,sweet',
 'es nutri sari,sirsak',
 'es nutri sari,jeruk',
 'es nutri sari,anggur',
 'es nutri sari,leci',
 'es nutri sari,lemon',
 'es nutri sari,blewah',
 'nutri sari,es rujak',
 'es capucino',
 'bakso ceker mercon',
 'ceker mercon',
 'bakso mercon',
 'dimsum',
 'tiam mie',
 'tiammie',
 'nasi goreng sapi',
 'kwetiaw sapi',
 'telur ceplok',
 'kwetiaw kengci',
 'ayam full',
 'nasi',
 'ayam dada',
 'ayam paha',
 'kepala ayam',
 'ceker ayam',
 'ati ampela ayam',
 'usus ayam',
 'ati ampela bebek',
 'paha bebek',
 'kepala bebek',
 'dada bebek',
 'tempe',
 'tahu',
 'pete',
 'peyek',
 'kulit ayam',
 'sosis kecil bakar/',
 'sosis bakar/goreng jumbo',
 'sosis bakar/goreng sedang',
 'sosis bakar/goreng sedang',
 'sosis bakar/goreng sedang',
 'lobster bakar/goreng',
 'cikuwa bakar/goreng',
 'dampling cheese bakar/goreng',
 'bakso bakar/goreng',
 'bola udang bakar/goreng',
 'crabstik bakar',
 'skelep bakar/goreng',
 'baso ikan bakar/goreng',
 'bakso salmon bakar/goreng',
 'otak-otak singapur bakar/goreng',
 'otak-otak bakar/goreng',
 'udang bakar/goreng',
 'maklor',
 'cireng',
 'tokoyaki isi 5',
 'telur gulung original',
 'cilor tusuk',
 'telor gulung isi',
 'sempol isi 5',
 'kaki naga isi',
 'naget cham isi',
 'kentang goreng',
 'cilor',
 'mielor',
 'omlet',
 'martabak telur loyang',
 'martabak telur terigu',
 'martabak telur puyuh',
 'lumpia telor ayam',
 'lumpia telor bebek',
 'otak-otak kriuk',
 'bakso kriuk',
 'makaroni pedas',
 'kripik kaca',
 'makaroni spiral',
 'es pop ice',
 'es teh manis',
 'es milo',
 'es drink beng-beng',
 'aqua',
 'es good day',
 'es good day',
 'es good day',
 'dancow panas/dingin',
 'indomi kuah +',
 'indomie goreng +',
 'indomie kuah +',
 'indomie soto telur',
 'super bihun kuah',
 'indomi goreng mix',
 'indomie goreng mix',
 'indomie soto telur',
 'otak-otak mercon',
 'bakso mercon',
 'ceker mercon',
 'ceker mix bakso',
 '275 gr tenderloin',
 'chicken croffle truffle',
 'single serve croffle',
 'cinnamon rolls ovomaltine',
 'ovomaltine raspberry tart',
 'black coffee 1',
 'black coffee 500',
 'kopi nusantara 1',
 'kopi nusantara 500',
 'caffe latte 1',
 'caffe latte 500',
 'almond croissant',
 'bacon & cheese',
 'butter croissant',
 'choco lava croissant',
 'nutella pain au',
 'peanut butter &',
 'salted egg yolk',
 'triple cheese croissant',
 'truffle mushroom croissant',
 'garlic cheese bread',
 'bacon & cheese',
 'spinach mushroom quiche',
 'beef pie',
 'chicken mushroom pie',
 'pain au raisin',
 'pain au praline',
 'vanilla bomboloni',
 'chocolate brownies bomboloni',
 'biscoff lotus bomboloni',
 'lemon meringue bomboloni',
 'nutella bomboloni',
 'salted caramel bomboloni',
 'peanut butter &',
 'strawberry cheesecake bomboloni',
 'plain croffle',
 'cinnamon sugar croffle',
 'maple croffle',
 'nutella croffle',
 'salted caramel croffle',
 'biscoff lotus croffle',
 'assorted croffle box',
 'peanut butter &',
 'kaya toast croffle',
 'hot espresso',
 'hot long black',
 'hot macchiato /',
 'hot cappucino /',
 'hot caffe latte',
 'hot mocha',
 'hot magic',
 'add soy milk',
 'add almond milk',
 'add oat milk',
 'iced americano',
 'iced caffe latte',
 'iced caffe latte',
 'iced mocha',
 'iced mocha with',
 'iced matha espresso',
 'classic affogato',
 'es kopi nusantara',
 'kopi nusantara granita',
 'loose leaf tea',
 'matcha latte',
 'lychee / peach',
 'lemon iced tea',
 'signature chocolate',
 'pure orange juice',
 'pure apple juice',
 'orange + apple',
 'fresh brewed ice',
 'avocado float',
 'avocado affogato',
 'avocado with kopi',
 'loose leaf tea',
 'triple berry smoothies',
 'banana & co',
 'mango tango smoothies',
 'nashville hot chiken',
 'house fries',
 'beef brisket ball',
 'oriental roasted duck',
 'fried calamari',
 'spaghetti',
 'tagliatelle oxtail ragu',
 'spagethetti carbonara',
 'clam linguine',
 'add lobster tail',
 'mac and cheese',
 'cavatelli',
 'black truffle tagliarini',
 'lasagna verde',
 'osso buco agnolotti',
 'crab spaghetti',
 'charred corn ribs',
 'house , parmesan',
 'truffle mashed potato',
 'asparagus , hollandaise',
 'creamed or wilted',
 'steamed sea bass',
 'balinese fried duck',
 'chargrilled cabe ijo',
 'bbq char siu',
 'nasi goreng gila',
 'chargrilled jumbo king',
 'black truffle wagyu',
 'mushroom soup',
 'burrata',
 'bakers caesar',
 'new england clam',
 'cajun rub hot',
 'buttermilk fried chicken',
 'avocado toast',
 'bakers breakfast',
 'crab omelette',
 'scramble egg &',
 'baked eggs',
 'eeg benedict',
 'garlic cheese',
 'valrhona chocolate tart',
 'verlhona flourless cake',
 'brie caramel',
 'pistachio fragipane',
 'pear tart',
 'peach tart',
 'lemon tart',
 'caramel pecan',
 'apple tart',
 'milk chocolate hazelnut',
 'croissant eeg tart',
 'varlhona dark chocolate',
 'dark chocolate fondant',
 'crispy skin salmon',
 'steak and frites',
 'half roasted chicken',
 'nashville fried lobster',
 'lobster thermidor',
 'black angus striploin',
 'black angus ribeye',
 'bourbon beef &',
 'black angus tenderloin',
 "baker's burger",
 'lobster roll',
 'egg sandwich',
 'cheeseburger',
 'french dip roast',
 'reuben sandwich',
 'elderflower grape',
 'berry blast',
 'jasmine citrus mojito',
 'chamomile strawberry spritzer',
 'lemongrass & guava',
 'coffee crumb cinnamon',
 'lotus biscoff cinnamon',
 'choco nutella cinnamon',
 'peanut nougat cinnamon',
 'walnut caramel cinnamon',
 'bakmi istimewa',
 'bakmi special',
 'bakmi bebek peking',
 'bakmi campur',
 'bakmi ayam kampung',
 'bakmi ayam cincang',
 'bakmi ayam kampung',
 'bakmi bebek peking',
 'bakso sapi 1',
 'bakso sapi 1/2',
 'bakso sapi',
 'bakso goreng',
 'pangsit rebus 1',
 'pangsit rebus 1/2',
 'pangsit rebus',
 'bebek peking 1',
 'bebek peking 1/2',
 'bebek peking 1/4',
 'ayam kampung 1',
 'ayam kampung 1/2',
 'ayam kampung 1/4',
 'air mineral 600',
 'teh pucuk',
 'bakmi rebus kalimantan',
 'bakmi goreng kalimantan',
 'bakmi kuah kalimantan',
 'bakmi goreng kari',
 'bakmi siram kalimantan',
 'kwetiaw rebus kalimantan',
 'kwetiaw goreng kalimantan',
 'kwetiaw goreng kari',
 'kwetiaw siram kalimantan',
 'bihun rebus kalimantan',
 'bihun goreng kalimantan',
 'nasi goreng kalimantan',
 'nasi goreng kusut',
 'nasi goreng singapore',
 'nasi goreng kari',
 'nasi siram kalimantan',
 'nasi telor kalimantan',
 'nasi muntahu lopui',
 'locupan jam',
 'locupan tek-tek',
 'pangsit kuah isi',
 'pangsit kuah isi',
 'pangsit tek -',
 'pangsit tek -',
 'susu kacang 500ml',
 'ayam kampung goreng',
 'ayam kampung goreng',
 'bakso mie campur',
 'bakso soun/bihun/mie kuning',
 'bakso spesial',
 'bakso kuah',
 'bakso urat besar',
 'bakso telur',
 'bakso setengah porsi',
 'nasi putih',
 'mie ayam bakso',
 'mie ayam bakso',
 'mie ayam bakso',
 'mie ayam bakso',
 'mie ayam pangsit',
 'mie ayam pangsit',
 'mie ayam',
 'mie ayam bakso',
 'mie ayam pangsit',
 'sop daging sapi',
 'siomay',
 'siomay goreng',
 'krupuk',
 'kelapa bulat ala',
 'soda susu',
 'es alpukat',
 'es kelapa jeruk',
 'es alpukat kelapa',
 'es campur',
 'es kelapa',
 'es jeruk',
 'es teh manis',
 'es teh tawar',
 'teh manis panas',
 'teh tawar',
 'jeruk panas',
 'lemon tea',
 'juas buah naga',
 'jus alpukat',
 'jus sirsak',
 'jus melon',
 'jus strawberry',
 'jus tomat',
 'jus jambu',
 'air mineral',
 'coca cola',
 'sprite',
 'fanta',
 'fruite tea',
 'teh botol',
 'jus mangga',
 'prima gelas',
 'pulpy orange',
 'fresh tea',
 'happiness bento set',
 'happiness bento set',
 'oishii set 1',
 'oishii set 2',
 'chicken katsu curry',
 'chicken karaage nanban',
 'beef hamburg curry',
 'chicken karaage mentai',
 'cheesy beef cutlet',
 'fish katsu mentai',
 'double hamburg curry',
 'cheesy hamburg curry',
 'es matcha mindfulness',
 'es mango yakult',
 'es lychee yakult',
 'cinnamon roll',
 'choco lava cake',
 'dark chocolate',
 'tiramisu cheesecake',
 'chicken karaage curry',
 'chicken katsu nanban',
 'beef teriyaki bento',
 'chicken teriyaki bento',
 'chicken katsu mentai',
 'extra cheesy beef',
 'cheesy chicken cutlet',
 'extra cheesy chicken',
 'fish katsu nanban',
 'fish katsu curry',
 'hemat set',
 'ekkado set',
 'cheesy chicken set',
 'chicken katsu set',
 'chicken popcorn bento',
 'chicken popcorn bento',
 'coffee brownie',
 'almond brownie',
 'coconut pandan',
 'red velvet',
 'original cheesecake',
 'blueberry cheesecake',
 'raspberry cheesecake',
 'extra sambal sachet',
 'extra mayonnaise sachet..',
 'es kopi cheer',
 'es cokelat cozy',
 'es teh joyful',
 '1ltr es kopi',
 'mineral water 330',
 'es sukur -',
 'es cendol ceria',
 'coca-cola',
 'bakso bakar',
 'bakso salmon bakar',
 'crabstick bakar',
 'dumpling bakar',
 'fishroll bakar',
 'ikan kue pedas',
 'rolade bakar',
 'scallope bakar',
 'sosis bakar',
 'sosis bakar jumbo',
 'tofu seafood bakar',
 'chikuwa bakar',
 'otak - otak',
 'mie oyeng',
 'sosis + kyentang',
 'kyentang oyeng',
 'sotang oyeng',
 'otak-otak oyeng',
 'bebek goreng',
 'bebek belur cabe',
 'bebek bakar bumbu',
 'bebek bakar kacang',
 'ayam kota goreng',
 'ayam kota belur',
 'ayam kota bakar',
 'ayam kota bakar',
 'ayam kampung belur',
 'ayam kampung goreng',
 'ayam kampung bakar',
 'ayam kampung bakar',
 'udang goreng tepung',
 'cumi goreng tepung',
 'cumi tumis cabe',
 'udang tumis cabe',
 'cumi asin tumis',
 'nila belur',
 'nila goreng.',
 'nila bakar kacang',
 'nila bakar rica',
 'sayur asem',
 'cah kangkung polos',
 'cah kangkung teri',
 'cah kangkung seafood',
 'terong goreng tepung',
 'tumis jamur tiram',
 'plencing kangkung',
 'telur penyet',
 'telur dadar',
 'sosis goreng',
 'tahu goreng',
 'tempe goreng',
 'telur bakar',
 'sosis bakar',
 'nasi a',
 'nasi b',
 'nasi putih',
 'sambal korek',
 'sambal ijo',
 'sambal mangga',
 'sambal teri',
 'sambal terasi',
 'sambal terong',
 'es jeruk',
 'jeruk murni',
 'es lidah buaya',
 'es timun',
 'es jeruk nipis',
 'es lemon tea',
 'es milo',
 'mineral botol',
 'es teh manis',
 'es teh tawar',
 'es alpukat susu',
 'jus alpukat',
 'teh botol',
 'es kosong',
 'es mangga boedjang',
 'jus mangga',
 'bebek goreng',
 'bebek belur cabe',
 'bebek bakar bumbu',
 'bebek bakar kacang',
 'ayam kota goreng',
 'ayam kota belur',
 'ayam kota bakar',
 'ayam kota bakar',
 'ayam kampung belur',
 'ayam kampung goreng',
 'ayam kampung bakar',
 'ayam kampung bakar',
 'udang goreng tepung',
 'cumi goreng tepung',
 'cumi tumis cabe',
 'udang tumis cabe',
 'cumi asin tumis',
 'nila belur',
 'nila goreng.',
 'nila bakar kacang',
 'nila bakar rica',
 'sayur asem',
 'cah kangkung polos',
 'cah kangkung teri',
 'cah kangkung seafood',
 'terong goreng tepung',
 'tumis jamur tiram',
 'plencing kangkung',
 'telur penyet',
 'telur dadar',
 'sosis goreng',
 'tahu goreng',
 'tempe goreng',
 'telur bakar',
 'sosis bakar',
 'nasi a',
 'nasi b',
 'nasi putih',
 'sambal korek',
 'sambal ijo',
 'sambal mangga',
 'sambal teri',
 'sambal terasi',
 'sambal terong',
 'es jeruk',
 'jeruk murni',
 'es lidah buaya',
 'es timun',
 'es jeruk nipis',
 'es lemon tea',
 'es milo',
 'mineral botol',
 'es teh manis',
 'es teh tawar',
 'es alpukat susu',
 'jus alpukat',
 'teh botol',
 'es kosong',
 'es mangga boedjang',
 'jus mangga',
 'original topokki',
 'mozzarellatopokki',
 'kimmari topokki',
 'ganjeong topokki',
 'rapokki',
 'roze topokki',
 'kimchi kimbab',
 'odeng',
 'original package',
 'mozzarella package',
 'roze package',
 'sharing package',
 'kimchi stir friced',
 'bulgogi rice',
 'a bowl of',
 'bulgogi japchae',
 'jeyuk bokkeum',
 'mineral water',
 'coke',
 'sprite',
 'chilsung cider',
 'milkis banana',
 'milkis melon',
 'milkis milk',
 'milkis strawberry',
 'lapis original',
 'cokelat keju',
 'bolu susu oreo',
 'bolu susu red',
 'cokelat',
 'pandan keju',
 'full talas',
 'lapis blackforest',
 'brownis glossy',
 'black forest ukuran',
 'black forest ukuran',
 'red valvet ukuran',
 'red velvet 15',
 'double coklat uk.15',
 'lilin magic',
 'lilin angka',
 'black forest ukuran',
 'black forest ukuran',
 'red velvet 11',
 'tiramissu uk.11',
 'tiramissu uk.15',
 'tiramissu uk.17',
 'double coklat uk.11',
 'double coklat uk.17',
 'mocca uk.11',
 'mocca uk.15',
 'klepon 15',
 'klepon 17',
 'cake cokelat',
 'cake tape',
 'bogor banana',
 'kotak cokelat',
 'kotak pandan',
 'muffin mini',
 'donat mini',
 'bika ambon',
 'cake pisang',
 'cake marmer',
 'pisang bolen cokelat',
 'cheese stik',
 'strudle brownis',
 'pisang bolen keju',
 'banana cheese roll',
 'swiss roll red',
 'swiss roll cokelate',
 'swiss roll keju',
 'cream keju',
 'keju susu',
 'double cheese',
 'polo cokelat chip',
 'strawberry mountain',
 'bluebarry mountain',
 'roti kismis',
 'long cokelat',
 'sarikaya',
 'roti unyil',
 'roti kacang hijau',
 'coklat kacang',
 'kacang merah',
 'kelapa gula malaka',
 'long cheese cream',
 'strawberry cream',
 'mocca',
 'bluebarry cheese roll',
 'sosis cheese',
 'smoke beef',
 'roti pizza',
 'coklat roll',
 'roti coklat',
 'roti mickey',
 'cream coklat',
 'kura kura',
 'cokelat keju',
 'roti pisang',
 'roti bun',
 'coklat meksiko',
 'coffe caramel',
 'abon roll',
 'abon sapi',
 'sobek cokelat combine',
 'melxic keju',
 'melxic coklat',
 'sobek sweet cheese',
 'sobek smokeebeef',
 'tawar susu',
 'tawar cokelat',
 'tawar keju',
 'lapis black forest',
 'bogor banana',
 'swiss roll coklat',
 'swiss roll keju',
 'bolu susu oreo',
 'bolu susu red',
 'bika ambon',
 'brownies glossy',
 'cake coklat',
 'cake marmer',
 'cake pisang',
 'cake tape',
 'kotak pandan',
 'kotak coklat',
 'muffin mini',
 'swiss roll red',
 'black forest 18',
 'double chocolate 16',
 'double chocolate 18',
 'red velvet 12',
 'tiramisu 12',
 'tiramisu 16',
 'black forest 12',
 'black forest 16',
 'bf 20',
 'cupcake',
 'double chocolate 12',
 'mocca 12',
 'mocca 16',
 'rainbow cake',
 'red velvet 16',
 'red velvet 18',
 'tiramisu 18',
 'donat mini',
 'donat kentang',
 'cokelat',
 'cokelat keju',
 'full talas',
 'original keju',
 'pandan keju',
 'lilin magic',
 'lilin angka',
 'cheese stick',
 'pisang bolen cokelat',
 'strudel brownies',
 'almond pastry',
 'banana cheese roll',
 'pisang bolen keju',
 'roti abon roll',
 'roti abon sapi',
 'roti pizza',
 'roti smoked beef',
 'roti sosis keju',
 'roti blueberry mountain',
 'roti cokelat',
 'roti cokelat roll',
 'roti cream coklat',
 'roti cream keju',
 'roti double cheese',
 'roti kacang hijau',
 'roti kelapa gula',
 'roti kismis',
 'roti long cheese',
 'roti long cokelat',
 'roti mickey',
 'roti polo chip',
 'roti sarikaya',
 'roti strawberry cheese',
 'roti blueberry cheese',
 'roti chocobun',
 'roti coffe caramel',
 'roti cokelat kacang',
 'roti cokelat keju',
 'roti cokelat mexico',
 'roti kacang merah',
 'roti keju susu',
 'roti kura-kura',
 'roti mocca',
 'roti pisang cokelat',
 'roti strawberry mountain',
 'roti unyil',
 'roti vanilla',
 'roti melxic cokelat',
 'roti melxic keju',
 'roti sobek smoked',
 'roti sobek sweet',
 'roti sobek chocolate',
 'roti tawar cokelat',
 'roti tawar keju',
 'roti tawar susu',
 'brobagi 1 -',
 'brobagi 2 -',
 'brobagi 3 -',
 'the brothers',
 'the cheesy chicken',
 'the chicken burger',
 'best of chicken',
 'the o.g. chicken',
 'asian chicken burger',
 'she caught ol',
 'chicago beef burger',
 ...]

In [11]:
df_alergen= pd.read_csv(makanan_dir)
df_alergen.head()

,Product,Label_Text,Allergen
0,Selera Roti Tawar,Diproduksi menggunakan bahan yang mengandung T...,['Telur']
1,Bintang Nugget Ayam Cokelat,Mengandung Gluten. Diproduksi dalam pabrik yan...,['Gluten']
2,Prima Es Krim,"Mengandung Gluten, Susu, dan Krustasea dan dip...","['Gluten', 'Susu', 'Krustasea']"
3,Santap Saus Stroberi,Mengandung Susu.,"['Susu', 'Kacang tanah', 'Telur']"
4,Makmur Kerupuk Ayam Bawang,Mengandung Kacang tanah dan diproses di fasili...,['Kacang tanah']

In [12]:
raw_alergen = df_alergen['Product'].dropna().tolist()
raw_alergen

['Selera Roti Tawar',
 'Bintang Nugget Ayam Cokelat',
 'Prima Es Krim',
 'Santap Saus Stroberi',
 'Makmur Kerupuk Ayam Bawang',
 'Bintang Selai',
 'Prima Kue Tart Stroberi',
 'Selera Yoghurt',
 'Indo Roti Burger',
 'Santap Mi Instan Vanila',
 'Rasa Keripik Kari',
 'Indo Kopi Instan',
 'Rasa Tahu Siap Saji Kari',
 'Alami Keripik',
 'Sehat Sereal',
 'Santap Roti Burger',
 'Bintang Cokelat Batangan',
 'Prima Biskuit Vanila',
 'Alami Minuman Bubuk Kari',
 'Santap Mayones',
 'Prima Mi Instan Vanila',
 'Nutra Kue Tart Vanila',
 'Prima Sosis',
 'Makmur Kue Tart',
 'Selera Kopi Instan Vanila',
 'Alami Kecap Vanila',
 'Nutra Sereal',
 'Alami Snack Jagung',
 'Indo Biskuit Ayam Bawang',
 'Selera Yoghurt Keju',
 'Bintang Mi Instan',
 'Rasa Snack Jagung',
 'Alami Keripik Stroberi',
 'Selera Saus Cokelat',
 'Prima Snack Jagung',
 'Santap Biskuit Keju',
 'Alami Roti Tawar Kari',
 'Sehat Saus Stroberi',
 'Indo Minuman Bubuk',
 'Sehat Roti Tawar Stroberi',
 'Santap Sereal',
 'Prima Roti Burger',
 'Santap Kue Tart Stroberi',
 'Nutra Kecap',
 'Sehat Yoghurt',
 'Indo Nugget Ayam Kari',
 'Alami Susu Kental Manis',
 'Sehat Snack Jagung',
 'Alami Roti Burger Stroberi',
 'Prima Tepung Pancake',
 'Prima Sosis Cokelat',
 'Makmur Nugget Ayam',
 'Nutra Minuman Bubuk',
 'Nutra Kerupuk Cokelat',
 'Makmur Yoghurt',
 'Makmur Es Krim Keju',
 'Santap Es Krim Stroberi',
 'Prima Mayones',
 'Sehat Biskuit Ayam Bawang',
 'Makmur Roti Tawar',
 'Alami Kue Kacang',
 'Indo Snack Jagung',
 'Bintang Kerupuk Ayam Bawang',
 'Makmur Sereal Ayam Bawang',
 'Selera Snack Vanila',
 'Nutra Kopi Instan Cokelat',
 'Bintang Selai',
 'Santap Kecap',
 'Selera Bumbu Penyedap',
 'Bintang Sosis Vanila',
 'Selera Nugget Ayam',
 'Bintang Sosis',
 'Indo Kue Tart Cokelat',
 'Indo Roti Tawar',
 'Alami Roti Tawar',
 'Alami Minuman Bubuk Ayam Bawang',
 'Santap Kopi Instan',
 'Sehat Kue Kacang',
 'Indo Kecap',
 'Makmur Keripik',
 'Santap Kopi Instan',
 'Rasa Tahu Siap Saji',
 'Makmur Es Krim Cokelat',
 'Selera Bumbu Penyedap',
 'Selera Kopi Instan Ayam Bawang',
 'Makmur Susu Kental Manis',
 'Prima Tahu Siap Saji Kari',
 'Sehat Es Krim',
 'Prima Keripik',
 'Santap Roti Burger Cokelat',
 'Makmur Kecap',
 'Makmur Mi Instan',
 'Santap Bumbu Penyedap Keju',
 'Bintang Nugget Ayam',
 'Indo Cokelat Batangan',
 'Alami Biskuit',
 'Alami Es Krim',
 'Makmur Minuman Bubuk Stroberi',
 'Selera Roti Tawar',
 'Selera Kopi Instan',
 'Santap Tepung Pancake',
 'Makmur Kerupuk Keju',
 'Sehat Cokelat Batangan',
 'Rasa Es Krim',
 'Prima Puding Instan Ayam Bawang',
 'Rasa Snack',
 'Selera Tepung Pancake',
 'Selera Snack',
 'Alami Mayones',
 'Prima Tahu Siap Saji',
 'Selera Minuman Bubuk',
 'Nutra Susu Kental Manis',
 'Rasa Sereal Ayam Bawang',
 'Prima Es Krim',
 'Santap Snack Jagung',
 'Sehat Puding Instan Stroberi',
 'Prima Mayones',
 'Santap Roti Tawar',
 'Prima Yoghurt',
 'Selera Tahu Siap Saji',
 'Santap Cokelat Batangan',
 'Alami Tepung Pancake',
 'Indo Sosis Cokelat',
 'Alami Bolu Kukus Ayam Bawang',
 'Bintang Mayones',
 'Nutra Yoghurt',
 'Selera Saus Cokelat',
 'Sehat Es Krim',
 'Makmur Yoghurt',
 'Makmur Es Krim',
 'Nutra Mayones Cokelat',
 'Bintang Roti Tawar Stroberi',
 'Selera Roti Burger',
 'Indo Minuman Bubuk Vanila',
 'Rasa Kecap',
 'Bintang Cokelat Batangan Stroberi',
 'Makmur Es Krim',
 'Bintang Biskuit',
 'Makmur Kue Tart',
 'Selera Cokelat Batangan',
 'Sehat Yoghurt',
 'Sehat Es Krim',
 'Indo Nugget Ayam Stroberi',
 'Selera Mi Instan',
 'Rasa Kerupuk Vanila',
 'Nutra Susu Kental Manis',
 'Alami Bolu Kukus Stroberi',
 'Bintang Snack Jagung',
 'Rasa Kue Tart Kari',
 'Selera Kue Kacang',
 'Bintang Yoghurt Cokelat',
 'Makmur Snack Jagung',
 'Selera Susu Kental Manis',
 'Santap Selai',
 'Rasa Mayones',
 'Makmur Mi Instan',
 'Selera Mayones Stroberi',
 'Selera Nugget Ayam',
 'Santap Kue Kacang Stroberi',
 'Indo Bolu Kukus',
 'Selera Sereal',
 'Bintang Tahu Siap Saji',
 'Makmur Tahu Siap Saji Stroberi',
 'Indo Roti Burger Kari',
 'Bintang Kerupuk',
 'Indo Yoghurt',
 'Selera Tepung Pancake',
 'Indo Bolu Kukus',
 'Indo Mi Instan Vanila',
 'Indo Mi Instan',
 'Santap Kerupuk',
 'Sehat Tepung Pancake',
 'Makmur Selai Keju',
 'Alami Minuman Bubuk',
 'Rasa Sereal Kari',
 'Indo Snack Jagung',
 'Santap Sosis',
 'Makmur Minuman Bubuk Ayam Bawang',
 'Bintang Saus',
 'Alami Kue Tart Cokelat',
 'Sehat Mi Instan',
 'Sehat Biskuit',
 'Prima Roti Tawar Cokelat',
 'Makmur Yoghurt Cokelat',
 'Selera Minuman Bubuk Stroberi',
 'Selera Kecap',
 'Rasa Susu Kental Manis',
 'Alami Bolu Kukus Vanila',
 'Nutra Tahu Siap Saji',
 'Indo Kopi Instan',
 'Makmur Tahu Siap Saji Keju',
 'Nutra Cokelat Batangan',
 'Nutra Kue Tart',
 'Makmur Mayones Keju',
 'Selera Kue Kacang',
 'Selera Mi Instan Stroberi',
 'Indo Yoghurt',
 'Nutra Saus',
 'Indo Mayones',
 'Indo Es Krim',
 'Rasa Snack',
 'Bintang Susu Kental Manis',
 'Selera Es Krim Kari',
 'Indo Puding Instan Vanila',
 'Indo Tepung Pancake Keju',
 'Alami Bumbu Penyedap',
 'Bintang Mi Instan Stroberi',
 'Rasa Roti Burger',
 'Alami Kue Tart Cokelat',
 'Alami Susu Kental Manis',
 'Alami Tahu Siap Saji Vanila',
 'Nutra Mi Instan Kari',
 'Alami Susu Kental Manis',
 'Santap Es Krim Cokelat',
 'Indo Yoghurt Kari',
 'Indo Tepung Pancake',
 'Nutra Susu Kental Manis',
 'Prima Minuman Bubuk Vanila',
 'Sehat Tepung Pancake',
 'Santap Kerupuk Cokelat',
 'Indo Biskuit',
 'Sehat Tepung Pancake',
 'Indo Kerupuk',
 'Nutra Biskuit Stroberi',
 'Indo Yoghurt Ayam Bawang',
 'Bintang Susu Kental Manis',
 'Bintang Susu Kental Manis',
 'Nutra Bumbu Penyedap',
 'Prima Roti Tawar',
 'Alami Minuman Bubuk',
 'Alami Cokelat Batangan',
 'Alami Bolu Kukus',
 'Prima Susu Kental Manis',
 'Santap Kecap',
 'Santap Biskuit Kari',
 'Prima Selai',
 'Alami Kopi Instan',
 'Nutra Kerupuk',
 'Santap Cokelat Batangan Cokelat',
 'Rasa Biskuit',
 'Bintang Yoghurt Stroberi',
 'Alami Es Krim Cokelat',
 'Nutra Kue Kacang Stroberi',
 'Sehat Tepung Pancake Ayam Bawang',
 'Nutra Keripik',
 'Bintang Kue Kacang',
 'Selera Es Krim Ayam Bawang',
 'Prima Saus',
 'Alami Sosis',
 'Alami Es Krim',
 'Rasa Cokelat Batangan',
 'Selera Tepung Pancake',
 'Bintang Biskuit',
 'Nutra Nugget Ayam Cokelat',
 'Makmur Biskuit Keju',
 'Makmur Kue Tart',
 'Indo Kecap Vanila',
 'Nutra Minuman Bubuk Stroberi',
 'Prima Es Krim Stroberi',
 'Prima Mi Instan Cokelat',
 'Prima Kerupuk Cokelat',
 'Prima Susu Kental Manis',
 'Santap Biskuit',
 'Nutra Bolu Kukus',
 'Santap Mayones Vanila',
 'Nutra Kerupuk',
 'Prima Cokelat Batangan',
 'Nutra Keripik',
 'Indo Susu Kental Manis',
 'Makmur Kopi Instan',
 'Sehat Es Krim',
 'Makmur Kecap',
 'Nutra Bumbu Penyedap',
 'Santap Saus Keju',
 'Santap Minuman Bubuk',
 'Rasa Saus',
 'Nutra Minuman Bubuk Keju',
 'Indo Biskuit',
 'Alami Kerupuk',
 'Nutra Tepung Pancake',
 'Prima Selai',
 'Makmur Bumbu Penyedap Kari',
 'Selera Mayones',
 'Sehat Tahu Siap Saji',
 'Prima Kue Tart',
 'Alami Bumbu Penyedap',
 'Sehat Mi Instan Vanila',
 'Sehat Minuman Bubuk',
 'Nutra Kecap',
 'Indo Roti Tawar',
 'Selera Minuman Bubuk',
 'Indo Bolu Kukus Cokelat',
 'Selera Saus Ayam Bawang',
 'Bintang Yoghurt',
 'Alami Kopi Instan',
 'Rasa Mi Instan Stroberi',
 'Santap Kopi Instan',
 'Santap Roti Tawar',
 'Makmur Cokelat Batangan',
 'Makmur Cokelat Batangan Ayam Bawang',
 'Indo Mayones Ayam Bawang',
 'Alami Roti Tawar',
 'Selera Roti Burger',
 'Santap Snack Jagung Ayam Bawang',
 'Bintang Mayones',
 'Alami Yoghurt',
 'Rasa Tahu Siap Saji',
 'Santap Kopi Instan',
 'Makmur Minuman Bubuk',
 'Selera Susu Kental Manis',
 'Santap Cokelat Batangan',
 'Indo Mi Instan Kari',
 'Prima Tepung Pancake Keju',
 'Sehat Tahu Siap Saji Kari',
 'Makmur Bumbu Penyedap',
 'Alami Sereal',
 'Bintang Mayones',
 'Santap Yoghurt',
 'Rasa Tepung Pancake',
 'Makmur Susu Kental Manis Stroberi',
 'Rasa Selai',
 'Sehat Puding Instan',
 'Santap Biskuit Vanila',
 'Alami Tepung Pancake Cokelat',
 'Makmur Kerupuk Ayam Bawang',
 'Indo Kue Tart',
 'Prima Sosis',
 'Prima Sosis Stroberi',
 'Alami Snack Jagung',
 'Rasa Puding Instan',
 'Makmur Saus',
 'Selera Mayones',
 'Indo Bumbu Penyedap Kari',
 'Selera Sosis',
 'Santap Cokelat Batangan',
 'Indo Snack Jagung',
 'Nutra Nugget Ayam Kari',
 'Rasa Biskuit',
 'Selera Roti Tawar Cokelat',
 'Nutra Roti Tawar',
 'Sehat Mi Instan',
 'Rasa Mayones',
 'Selera Tepung Pancake',
 'Rasa Nugget Ayam',
 'Bintang Kue Kacang',
 'Selera Kopi Instan',
 'Santap Selai',
 'Makmur Mayones Ayam Bawang',
 'Indo Cokelat Batangan Vanila',
 'Nutra Bumbu Penyedap Stroberi',
 'Alami Susu Kental Manis',
 'Selera Tahu Siap Saji',
 'Sehat Bumbu Penyedap',
 'Nutra Kopi Instan Ayam Bawang',
 'Rasa Puding Instan Ayam Bawang',
 'Santap Kue Kacang',
 'Alami Mi Instan Vanila',
 'Makmur Kue Tart',
 'Prima Kue Kacang',
 'Rasa Kue Tart Kari',
 'Selera Bumbu Penyedap',
 'Makmur Kue Tart Stroberi',
 'Bintang Kopi Instan',
 'Rasa Roti Tawar',
 'Indo Roti Tawar',
 'Nutra Saus',
 'Indo Es Krim',
 'Selera Bumbu Penyedap',
 'Indo Cokelat Batangan',
 'Rasa Es Krim',
 'Makmur Susu Kental Manis',
 'Rasa Mi Instan',
 'Santap Roti Burger',
 'Selera Es Krim Keju',
 'Rasa Selai',
 'Selera Roti Tawar',
 'Indo Kecap Ayam Bawang',
 'Makmur Roti Tawar',
 'Makmur Saus Vanila',
 'Nutra Mi Instan Keju',
 'Sehat Sosis',
 'Nutra Cokelat Batangan',
 'Rasa Kecap Keju',
 'Bintang Kue Tart',
 'Bintang Roti Tawar',
 'Makmur Kerupuk Ayam Bawang',
 'Nutra Cokelat Batangan',
 'Nutra Roti Tawar Kari',
 'Indo Puding Instan',
 'Makmur Tahu Siap Saji Kari',
 'Sehat Susu Kental Manis',
 'Bintang Biskuit Stroberi',
 'Rasa Cokelat Batangan',
 'Makmur Roti Tawar Keju',
 'Nutra Mayones',
 'Sehat Bolu Kukus',
 'Rasa Es Krim Cokelat',
 'Rasa Mayones Cokelat',
 'Rasa Yoghurt',
 'Santap Susu Kental Manis Cokelat',
 'Santap Roti Burger',
 'Selera Snack',
 'Selera Tahu Siap Saji',
 'Nutra Keripik',
 'Selera Mi Instan',
 'Alami Snack Jagung',
 'Sehat Kue Tart',
 'Prima Saus Cokelat',
 'Bintang Keripik Kari',
 'Santap Tepung Pancake',
 'Santap Kue Tart',
 'Nutra Sereal Keju',
 'Prima Biskuit',
 'Santap Keripik',
 'Bintang Tahu Siap Saji Ayam Bawang',
 'Nutra Tepung Pancake',
 'Prima Roti Burger Cokelat',
 'Indo Roti Burger',
 'Indo Snack',
 'Indo Sereal',
 'Prima Tahu Siap Saji Keju',
 'Makmur Saus',
 'Sehat Kue Tart Stroberi',
 'Bintang Kecap Kari',
 'Makmur Mi Instan Stroberi',
 'Prima Saus',
 'Indo Snack Jagung Cokelat',
 'Sehat Kue Kacang Kari',
 'Alami Tahu Siap Saji',
 'Santap Kecap',
 'Prima Bolu Kukus Stroberi',
 'Makmur Kue Tart Cokelat',
 'Alami Susu Kental Manis',
 'Selera Snack Keju',
 'Makmur Sosis',
 'Sehat Snack',
 'Indo Minuman Bubuk',
 'Prima Puding Instan',
 'Rasa Mi Instan',
 'Sehat Snack Jagung',
 'Rasa Sosis',
 'Selera Bolu Kukus',
 'Selera Tahu Siap Saji',
 'Selera Kerupuk Kari',
 'Bintang Yoghurt',
 'Santap Kecap',
 'Indo Puding Instan',
 'Indo Kopi Instan Kari',
 'Rasa Mi Instan',
 'Makmur Susu Kental Manis Cokelat',
 'Indo Sosis',
 'Rasa Cokelat Batangan',
 'Indo Roti Burger Cokelat',
 'Rasa Kecap Kari',
 'Rasa Yoghurt',
 'Makmur Snack Ayam Bawang',
 'Indo Tepung Pancake',
 'Makmur Bolu Kukus',
 'Nutra Tahu Siap Saji',
 'Selera Minuman Bubuk',
 'Sehat Roti Burger Ayam Bawang',
 'Makmur Kue Kacang',
 'Bintang Yoghurt',
 'Indo Roti Burger Keju',
 'Makmur Kecap Kari',
 'Alami Tepung Pancake',
 'Selera Keripik',
 'Selera Minuman Bubuk',
 'Bintang Tepung Pancake Ayam Bawang',
 'Bintang Snack',
 'Selera Mayones',
 'Bintang Puding Instan',
 'Rasa Saus',
 'Alami Tahu Siap Saji Keju',
 'Alami Kerupuk',
 'Bintang Bumbu Penyedap',
 'Alami Kecap Keju',
 'Rasa Roti Burger Stroberi',
 'Selera Yoghurt',
 'Prima Tepung Pancake',
 'Sehat Nugget Ayam',
 'Prima Yoghurt',
 'Bintang Kerupuk',
 'Rasa Sereal',
 'Rasa Sereal',
 'Nutra Saus',
 'Selera Sosis',
 'Sehat Kerupuk',
 'Indo Bolu Kukus Vanila',
 'Nutra Snack Jagung',
 'Nutra Tepung Pancake',
 'Prima Cokelat Batangan',
 'Prima Snack Jagung',
 'Alami Roti Burger',
 'Nutra Es Krim',
 'Santap Nugget Ayam',
 'Bintang Mi Instan',
 'Santap Sosis',
 'Sehat Roti Burger',
 'Rasa Susu Kental Manis',
 'Selera Biskuit Vanila',
 'Rasa Sereal Stroberi',
 'Alami Es Krim',
 'Indo Bolu Kukus Kari',
 'Indo Snack',
 'Indo Nugget Ayam Stroberi',
 'Santap Roti Burger',
 'Santap Snack',
 'Alami Selai Kari',
 'Bintang Bumbu Penyedap',
 'Sehat Kopi Instan',
 'Sehat Bolu Kukus',
 'Rasa Sereal',
 'Nutra Kopi Instan',
 'Prima Tepung Pancake',
 'Nutra Tahu Siap Saji Kari',
 'Sehat Tahu Siap Saji',
 'Indo Roti Burger',
 'Alami Saus',
 'Bintang Puding Instan',
 'Makmur Selai',
 'Rasa Tahu Siap Saji',
 'Bintang Bumbu Penyedap',
 'Makmur Sereal Ayam Bawang',
 'Rasa Kue Kacang',
 'Sehat Saus Keju',
 'Rasa Snack',
 'Bintang Kerupuk',
 'Alami Nugget Ayam Ayam Bawang',
 'Sehat Saus Keju',
 'Santap Selai Kari',
 'Sehat Bolu Kukus Ayam Bawang',
 'Bintang Bolu Kukus',
 'Rasa Bolu Kukus',
 'Rasa Kue Tart',
 'Selera Selai',
 'Selera Roti Burger Vanila',
 'Sehat Mayones',
 'Makmur Es Krim Kari',
 'Bintang Sereal',
 'Santap Minuman Bubuk',
 'Selera Kerupuk Vanila',
 'Bintang Roti Tawar Ayam Bawang',
 'Selera Sosis',
 'Bintang Snack',
 'Makmur Kecap Ayam Bawang',
 'Sehat Bolu Kukus',
 'Selera Kerupuk',
 'Makmur Kue Kacang Kari',
 'Bintang Bolu Kukus Cokelat',
 'Bintang Roti Tawar',
 'Bintang Cokelat Batangan',
 'Sehat Kopi Instan',
 'Alami Bolu Kukus',
 'Indo Puding Instan Kari',
 'Prima Keripik',
 'Sehat Puding Instan',
 'Bintang Snack Jagung Cokelat',
 'Prima Saus',
 'Makmur Susu Kental Manis Vanila',
 'Prima Roti Burger Kari',
 'Indo Roti Tawar',
 'Santap Bolu Kukus Vanila',
 'Bintang Susu Kental Manis',
 'Bintang Bumbu Penyedap',
 'Santap Es Krim',
 'Nutra Saus',
 'Makmur Kerupuk Ayam Bawang',
 'Santap Kopi Instan Stroberi',
 'Indo Kue Tart',
 'Rasa Puding Instan',
 'Alami Tahu Siap Saji',
 'Selera Es Krim Ayam Bawang',
 'Makmur Kerupuk Ayam Bawang',
 'Santap Yoghurt Cokelat',
 'Sehat Kopi Instan Kari',
 'Santap Tahu Siap Saji',
 'Santap Puding Instan',
 'Santap Keripik Ayam Bawang',
 'Santap Sosis',
 'Rasa Biskuit Ayam Bawang',
 'Selera Minuman Bubuk',
 'Selera Tepung Pancake',
 'Indo Sereal',
 'Prima Kecap Ayam Bawang',
 'Sehat Sosis Cokelat',
 'Selera Kopi Instan Cokelat',
 'Indo Tahu Siap Saji Vanila',
 'Sehat Bolu Kukus',
 'Alami Susu Kental Manis',
 'Makmur Keripik',
 'Santap Roti Burger Stroberi',
 'Bintang Kue Tart',
 'Alami Saus',
 'Rasa Kue Tart Cokelat',
 'Nutra Bolu Kukus Kari',
 'Makmur Sosis',
 'Bintang Keripik',
 'Selera Kue Kacang Ayam Bawang',
 'Alami Kue Kacang',
 'Selera Sereal',
 'Indo Cokelat Batangan',
 'Indo Yoghurt Vanila',
 'Makmur Mayones Cokelat',
 'Nutra Susu Kental Manis',
 'Selera Biskuit',
 'Prima Keripik',
 'Selera Kue Kacang Ayam Bawang',
 'Nutra Kue Kacang',
 'Indo Roti Burger',
 'Sehat Biskuit Cokelat',
 'Sehat Es Krim',
 'Rasa Saus Ayam Bawang',
 'Sehat Tepung Pancake',
 'Sehat Tahu Siap Saji',
 'Selera Snack Jagung',
 'Rasa Bolu Kukus',
 'Prima Selai',
 'Santap Roti Tawar Cokelat',
 'Prima Kerupuk',
 'Nutra Mayones',
 'Nutra Es Krim',
 'Selera Roti Tawar Kari',
 'Indo Snack',
 'Nutra Kopi Instan',
 'Nutra Bolu Kukus',
 'Sehat Roti Burger',
 'Sehat Snack Jagung Kari',
 'Sehat Susu Kental Manis',
 'Rasa Susu Kental Manis',
 'Indo Mi Instan',
 'Rasa Kue Kacang Stroberi',
 'Rasa Minuman Bubuk Keju',
 'Bintang Kopi Instan Cokelat',
 'Rasa Kue Tart',
 'Santap Nugget Ayam Kari',
 'Makmur Kue Tart',
 'Bintang Kue Kacang',
 'Alami Kecap',
 'Alami Mayones',
 'Rasa Nugget Ayam Cokelat',
 'Selera Kue Kacang',
 'Makmur Roti Tawar Vanila',
 'Selera Puding Instan',
 'Sehat Kerupuk',
 'Rasa Kue Tart Kari',
 'Selera Saus',
 'Bintang Snack Vanila',
 'Prima Kerupuk Kari',
 'Nutra Saus',
 'Selera Nugget Ayam',
 'Makmur Kue Kacang',
 'Indo Mayones',
 'Santap Cokelat Batangan',
 'Bintang Kue Kacang',
 'Sehat Yoghurt',
 'Alami Kue Kacang',
 'Santap Selai Cokelat',
 'Bintang Nugget Ayam',
 'Santap Sosis Stroberi',
 'Indo Cokelat Batangan',
 'Nutra Tahu Siap Saji Keju',
 'Nutra Roti Burger',
 'Bintang Snack Jagung Stroberi',
 'Alami Roti Burger Vanila',
 'Indo Puding Instan Ayam Bawang',
 'Prima Tepung Pancake Cokelat',
 'Makmur Tepung Pancake Ayam Bawang',
 'Indo Saus',
 'Alami Kecap Cokelat',
 'Selera Tepung Pancake',
 'Indo Selai Stroberi',
 'Rasa Sereal Cokelat',
 'Alami Cokelat Batangan Kari',
 'Rasa Roti Tawar',
 'Bintang Bolu Kukus Keju',
 'Selera Roti Burger',
 'Rasa Kue Tart',
 'Indo Es Krim',
 'Rasa Susu Kental Manis',
 'Santap Kerupuk',
 'Selera Cokelat Batangan Kari',
 'Rasa Snack Jagung',
 'Indo Kerupuk Ayam Bawang',
 'Indo Snack',
 'Rasa Snack Jagung Vanila',
 'Sehat Puding Instan',
 'Rasa Kue Tart Stroberi',
 'Selera Kue Tart Cokelat',
 'Sehat Mayones',
 'Alami Mayones',
 'Selera Tahu Siap Saji Kari',
 'Makmur Tepung Pancake',
 'Prima Puding Instan',
 'Indo Kecap',
 'Makmur Tepung Pancake Vanila',
 'Alami Sosis',
 'Makmur Tepung Pancake',
 'Santap Sereal Vanila',
 'Bintang Biskuit',
 'Santap Keripik Stroberi',
 'Bintang Kue Kacang Ayam Bawang',
 'Alami Kue Tart Cokelat',
 'Sehat Kopi Instan',
 'Nutra Tahu Siap Saji Cokelat',
 'Makmur Kue Kacang',
 'Makmur Keripik Ayam Bawang',
 'Alami Snack Jagung',
 'Bintang Tahu Siap Saji',
 'Bintang Mayones',
 'Alami Cokelat Batangan',
 'Selera Roti Tawar',
 'Santap Selai Vanila',
 'Selera Mi Instan',
 'Santap Susu Kental Manis',
 'Indo Keripik Cokelat',
 'Nutra Keripik',
 'Rasa Tahu Siap Saji',
 'Selera Biskuit Vanila',
 'Nutra Biskuit',
 'Alami Puding Instan',
 'Alami Kopi Instan Kari',
 'Indo Snack Jagung Cokelat',
 'Selera Roti Burger',
 'Prima Susu Kental Manis',
 'Prima Saus Cokelat',
 'Makmur Kerupuk',
 'Prima Sosis',
 'Selera Biskuit',
 'Prima Puding Instan',
 'Makmur Yoghurt Vanila',
 'Sehat Cokelat Batangan',
 'Indo Roti Burger',
 'Selera Kecap Ayam Bawang',
 'Prima Bumbu Penyedap Cokelat',
 'Rasa Mi Instan',
 'Rasa Selai Stroberi',
 'Bintang Sereal',
 'Indo Nugget Ayam Keju',
 'Makmur Minuman Bubuk',
 'Makmur Sereal Cokelat',
 'Nutra Kecap',
 'Makmur Tepung Pancake Keju',
 'Prima Kecap Ayam Bawang',
 'Nutra Nugget Ayam Vanila',
 'Prima Tahu Siap Saji',
 'Selera Kue Tart',
 'Bintang Kerupuk',
 'Bintang Snack',
 'Prima Cokelat Batangan',
 'Sehat Biskuit Ayam Bawang',
 'Selera Es Krim',
 'Prima Saus',
 'Bintang Kue Kacang',
 'Rasa Sosis',
 'Indo Tepung Pancake Ayam Bawang',
 'Nutra Tepung Pancake',
 'Bintang Biskuit',
 'Rasa Cokelat Batangan Cokelat',
 'Indo Bolu Kukus',
 'Makmur Snack',
 'Makmur Yoghurt',
 'Selera Mi Instan',
 'Makmur Saus',
 'Sehat Es Krim',
 'Sehat Bumbu Penyedap Kari',
 'Makmur Susu Kental Manis',
 'Indo Susu Kental Manis',
 'Rasa Sereal',
 'Makmur Keripik',
 'Rasa Bolu Kukus',
 'Makmur Minuman Bubuk Ayam Bawang',
 'Santap Snack',
 'Selera Kue Kacang',
 'Indo Mi Instan Vanila',
 'Prima Roti Tawar Ayam Bawang',
 'Indo Yoghurt',
 'Indo Mayones',
 'Prima Kue Kacang',
 'Sehat Kue Kacang',
 'Selera Bumbu Penyedap',
 'Sehat Sereal',
 'Nutra Roti Burger',
 'Nutra Sosis Stroberi',
 'Prima Roti Tawar Stroberi',
 'Bintang Snack',
 'Santap Sereal',
 'Indo Sereal Stroberi',
 'Alami Selai',
 'Alami Cokelat Batangan',
 'Selera Kerupuk',
 'Selera Selai Keju',
 'Rasa Roti Tawar',
 'Rasa Puding Instan Kari',
 'Prima Saus',
 'Prima Kecap Kari',
 'Nutra Mi Instan Cokelat',
 'Nutra Mi Instan Kari',
 'Alami Bumbu Penyedap Vanila',
 'Selera Selai',
 'Selera Sereal',
 'Sehat Kecap',
 'Santap Kerupuk',
 'Makmur Kopi Instan',
 'Indo Sereal Kari',
 'Selera Saus',
 'Selera Bolu Kukus',
 'Bintang Bumbu Penyedap Kari',
 'Makmur Tepung Pancake Ayam Bawang',
 'Rasa Roti Tawar Cokelat',
 'Bintang Snack Jagung Stroberi',
 'Makmur Snack',
 'Sehat Kecap',
 'Nutra Sereal',
 'Santap Puding Instan',
 'Makmur Kerupuk',
 'Santap Cokelat Batangan Vanila',
 'Sehat Kecap',
 'Prima Kopi Instan',
 'Nutra Es Krim',
 'Sehat Bumbu Penyedap',
 'Indo Snack',
 'Sehat Selai',
 'Prima Yoghurt',
 'Selera Bumbu Penyedap',
 'Alami Sosis Kari',
 'Bintang Tepung Pancake',
 'Bintang Snack Kari',
 'Alami Selai',
 'Sehat Nugget Ayam Cokelat',
 'Santap Snack Jagung',
 'Makmur Snack',
 'Santap Snack Jagung',
 'Nutra Kue Tart',
 'Indo Snack Jagung',
 'Makmur Mi Instan Cokelat',
 'Prima Nugget Ayam Cokelat',
 'Bintang Biskuit',
 'Santap Sosis',
 'Bintang Biskuit',
 'Santap Kerupuk',
 'Makmur Mayones Ayam Bawang',
 'Santap Selai',
 'Nutra Keripik',
 'Sehat Roti Burger Keju',

In [13]:
clean_alergen = []

for item in raw_alergen:
    item = re.sub(r'\(.*?\)', '', item).strip()

    short_item = " ".join(item.split()[:3]).lower()
    clean_alergen.append(short_item)

In [14]:
clean_alergen

['selera roti tawar',
 'bintang nugget ayam',
 'prima es krim',
 'santap saus stroberi',
 'makmur kerupuk ayam',
 'bintang selai',
 'prima kue tart',
 'selera yoghurt',
 'indo roti burger',
 'santap mi instan',
 'rasa keripik kari',
 'indo kopi instan',
 'rasa tahu siap',
 'alami keripik',
 'sehat sereal',
 'santap roti burger',
 'bintang cokelat batangan',
 'prima biskuit vanila',
 'alami minuman bubuk',
 'santap mayones',
 'prima mi instan',
 'nutra kue tart',
 'prima sosis',
 'makmur kue tart',
 'selera kopi instan',
 'alami kecap vanila',
 'nutra sereal',
 'alami snack jagung',
 'indo biskuit ayam',
 'selera yoghurt keju',
 'bintang mi instan',
 'rasa snack jagung',
 'alami keripik stroberi',
 'selera saus cokelat',
 'prima snack jagung',
 'santap biskuit keju',
 'alami roti tawar',
 'sehat saus stroberi',
 'indo minuman bubuk',
 'sehat roti tawar',
 'santap sereal',
 'prima roti burger',
 'santap kue tart',
 'nutra kecap',
 'sehat yoghurt',
 'indo nugget ayam',
 'alami susu kental',
 'sehat snack jagung',
 'alami roti burger',
 'prima tepung pancake',
 'prima sosis cokelat',
 'makmur nugget ayam',
 'nutra minuman bubuk',
 'nutra kerupuk cokelat',
 'makmur yoghurt',
 'makmur es krim',
 'santap es krim',
 'prima mayones',
 'sehat biskuit ayam',
 'makmur roti tawar',
 'alami kue kacang',
 'indo snack jagung',
 'bintang kerupuk ayam',
 'makmur sereal ayam',
 'selera snack vanila',
 'nutra kopi instan',
 'bintang selai',
 'santap kecap',
 'selera bumbu penyedap',
 'bintang sosis vanila',
 'selera nugget ayam',
 'bintang sosis',
 'indo kue tart',
 'indo roti tawar',
 'alami roti tawar',
 'alami minuman bubuk',
 'santap kopi instan',
 'sehat kue kacang',
 'indo kecap',
 'makmur keripik',
 'santap kopi instan',
 'rasa tahu siap',
 'makmur es krim',
 'selera bumbu penyedap',
 'selera kopi instan',
 'makmur susu kental',
 'prima tahu siap',
 'sehat es krim',
 'prima keripik',
 'santap roti burger',
 'makmur kecap',
 'makmur mi instan',
 'santap bumbu penyedap',
 'bintang nugget ayam',
 'indo cokelat batangan',
 'alami biskuit',
 'alami es krim',
 'makmur minuman bubuk',
 'selera roti tawar',
 'selera kopi instan',
 'santap tepung pancake',
 'makmur kerupuk keju',
 'sehat cokelat batangan',
 'rasa es krim',
 'prima puding instan',
 'rasa snack',
 'selera tepung pancake',
 'selera snack',
 'alami mayones',
 'prima tahu siap',
 'selera minuman bubuk',
 'nutra susu kental',
 'rasa sereal ayam',
 'prima es krim',
 'santap snack jagung',
 'sehat puding instan',
 'prima mayones',
 'santap roti tawar',
 'prima yoghurt',
 'selera tahu siap',
 'santap cokelat batangan',
 'alami tepung pancake',
 'indo sosis cokelat',
 'alami bolu kukus',
 'bintang mayones',
 'nutra yoghurt',
 'selera saus cokelat',
 'sehat es krim',
 'makmur yoghurt',
 'makmur es krim',
 'nutra mayones cokelat',
 'bintang roti tawar',
 'selera roti burger',
 'indo minuman bubuk',
 'rasa kecap',
 'bintang cokelat batangan',
 'makmur es krim',
 'bintang biskuit',
 'makmur kue tart',
 'selera cokelat batangan',
 'sehat yoghurt',
 'sehat es krim',
 'indo nugget ayam',
 'selera mi instan',
 'rasa kerupuk vanila',
 'nutra susu kental',
 'alami bolu kukus',
 'bintang snack jagung',
 'rasa kue tart',
 'selera kue kacang',
 'bintang yoghurt cokelat',
 'makmur snack jagung',
 'selera susu kental',
 'santap selai',
 'rasa mayones',
 'makmur mi instan',
 'selera mayones stroberi',
 'selera nugget ayam',
 'santap kue kacang',
 'indo bolu kukus',
 'selera sereal',
 'bintang tahu siap',
 'makmur tahu siap',
 'indo roti burger',
 'bintang kerupuk',
 'indo yoghurt',
 'selera tepung pancake',
 'indo bolu kukus',
 'indo mi instan',
 'indo mi instan',
 'santap kerupuk',
 'sehat tepung pancake',
 'makmur selai keju',
 'alami minuman bubuk',
 'rasa sereal kari',
 'indo snack jagung',
 'santap sosis',
 'makmur minuman bubuk',
 'bintang saus',
 'alami kue tart',
 'sehat mi instan',
 'sehat biskuit',
 'prima roti tawar',
 'makmur yoghurt cokelat',
 'selera minuman bubuk',
 'selera kecap',
 'rasa susu kental',
 'alami bolu kukus',
 'nutra tahu siap',
 'indo kopi instan',
 'makmur tahu siap',
 'nutra cokelat batangan',
 'nutra kue tart',
 'makmur mayones keju',
 'selera kue kacang',
 'selera mi instan',
 'indo yoghurt',
 'nutra saus',
 'indo mayones',
 'indo es krim',
 'rasa snack',
 'bintang susu kental',
 'selera es krim',
 'indo puding instan',
 'indo tepung pancake',
 'alami bumbu penyedap',
 'bintang mi instan',
 'rasa roti burger',
 'alami kue tart',
 'alami susu kental',
 'alami tahu siap',
 'nutra mi instan',
 'alami susu kental',
 'santap es krim',
 'indo yoghurt kari',
 'indo tepung pancake',
 'nutra susu kental',
 'prima minuman bubuk',
 'sehat tepung pancake',
 'santap kerupuk cokelat',
 'indo biskuit',
 'sehat tepung pancake',
 'indo kerupuk',
 'nutra biskuit stroberi',
 'indo yoghurt ayam',
 'bintang susu kental',
 'bintang susu kental',
 'nutra bumbu penyedap',
 'prima roti tawar',
 'alami minuman bubuk',
 'alami cokelat batangan',
 'alami bolu kukus',
 'prima susu kental',
 'santap kecap',
 'santap biskuit kari',
 'prima selai',
 'alami kopi instan',
 'nutra kerupuk',
 'santap cokelat batangan',
 'rasa biskuit',
 'bintang yoghurt stroberi',
 'alami es krim',
 'nutra kue kacang',
 'sehat tepung pancake',
 'nutra keripik',
 'bintang kue kacang',
 'selera es krim',
 'prima saus',
 'alami sosis',
 'alami es krim',
 'rasa cokelat batangan',
 'selera tepung pancake',
 'bintang biskuit',
 'nutra nugget ayam',
 'makmur biskuit keju',
 'makmur kue tart',
 'indo kecap vanila',
 'nutra minuman bubuk',
 'prima es krim',
 'prima mi instan',
 'prima kerupuk cokelat',
 'prima susu kental',
 'santap biskuit',
 'nutra bolu kukus',
 'santap mayones vanila',
 'nutra kerupuk',
 'prima cokelat batangan',
 'nutra keripik',
 'indo susu kental',
 'makmur kopi instan',
 'sehat es krim',
 'makmur kecap',
 'nutra bumbu penyedap',
 'santap saus keju',
 'santap minuman bubuk',
 'rasa saus',
 'nutra minuman bubuk',
 'indo biskuit',
 'alami kerupuk',
 'nutra tepung pancake',
 'prima selai',
 'makmur bumbu penyedap',
 'selera mayones',
 'sehat tahu siap',
 'prima kue tart',
 'alami bumbu penyedap',
 'sehat mi instan',
 'sehat minuman bubuk',
 'nutra kecap',
 'indo roti tawar',
 'selera minuman bubuk',
 'indo bolu kukus',
 'selera saus ayam',
 'bintang yoghurt',
 'alami kopi instan',
 'rasa mi instan',
 'santap kopi instan',
 'santap roti tawar',
 'makmur cokelat batangan',
 'makmur cokelat batangan',
 'indo mayones ayam',
 'alami roti tawar',
 'selera roti burger',
 'santap snack jagung',
 'bintang mayones',
 'alami yoghurt',
 'rasa tahu siap',
 'santap kopi instan',
 'makmur minuman bubuk',
 'selera susu kental',
 'santap cokelat batangan',
 'indo mi instan',
 'prima tepung pancake',
 'sehat tahu siap',
 'makmur bumbu penyedap',
 'alami sereal',
 'bintang mayones',
 'santap yoghurt',
 'rasa tepung pancake',
 'makmur susu kental',
 'rasa selai',
 'sehat puding instan',
 'santap biskuit vanila',
 'alami tepung pancake',
 'makmur kerupuk ayam',
 'indo kue tart',
 'prima sosis',
 'prima sosis stroberi',
 'alami snack jagung',
 'rasa puding instan',
 'makmur saus',
 'selera mayones',
 'indo bumbu penyedap',
 'selera sosis',
 'santap cokelat batangan',
 'indo snack jagung',
 'nutra nugget ayam',
 'rasa biskuit',
 'selera roti tawar',
 'nutra roti tawar',
 'sehat mi instan',
 'rasa mayones',
 'selera tepung pancake',
 'rasa nugget ayam',
 'bintang kue kacang',
 'selera kopi instan',
 'santap selai',
 'makmur mayones ayam',
 'indo cokelat batangan',
 'nutra bumbu penyedap',
 'alami susu kental',
 'selera tahu siap',
 'sehat bumbu penyedap',
 'nutra kopi instan',
 'rasa puding instan',
 'santap kue kacang',
 'alami mi instan',
 'makmur kue tart',
 'prima kue kacang',
 'rasa kue tart',
 'selera bumbu penyedap',
 'makmur kue tart',
 'bintang kopi instan',
 'rasa roti tawar',
 'indo roti tawar',
 'nutra saus',
 'indo es krim',
 'selera bumbu penyedap',
 'indo cokelat batangan',
 'rasa es krim',
 'makmur susu kental',
 'rasa mi instan',
 'santap roti burger',
 'selera es krim',
 'rasa selai',
 'selera roti tawar',
 'indo kecap ayam',
 'makmur roti tawar',
 'makmur saus vanila',
 'nutra mi instan',
 'sehat sosis',
 'nutra cokelat batangan',
 'rasa kecap keju',
 'bintang kue tart',
 'bintang roti tawar',
 'makmur kerupuk ayam',
 'nutra cokelat batangan',
 'nutra roti tawar',
 'indo puding instan',
 'makmur tahu siap',
 'sehat susu kental',
 'bintang biskuit stroberi',
 'rasa cokelat batangan',
 'makmur roti tawar',
 'nutra mayones',
 'sehat bolu kukus',
 'rasa es krim',
 'rasa mayones cokelat',
 'rasa yoghurt',
 'santap susu kental',
 'santap roti burger',
 'selera snack',
 'selera tahu siap',
 'nutra keripik',
 'selera mi instan',
 'alami snack jagung',
 'sehat kue tart',
 'prima saus cokelat',
 'bintang keripik kari',
 'santap tepung pancake',
 'santap kue tart',
 'nutra sereal keju',
 'prima biskuit',
 'santap keripik',
 'bintang tahu siap',
 'nutra tepung pancake',
 'prima roti burger',
 'indo roti burger',
 'indo snack',
 'indo sereal',
 'prima tahu siap',
 'makmur saus',
 'sehat kue tart',
 'bintang kecap kari',
 'makmur mi instan',
 'prima saus',
 'indo snack jagung',
 'sehat kue kacang',
 'alami tahu siap',
 'santap kecap',
 'prima bolu kukus',
 'makmur kue tart',
 'alami susu kental',
 'selera snack keju',
 'makmur sosis',
 'sehat snack',
 'indo minuman bubuk',
 'prima puding instan',
 'rasa mi instan',
 'sehat snack jagung',
 'rasa sosis',
 'selera bolu kukus',
 'selera tahu siap',
 'selera kerupuk kari',
 'bintang yoghurt',
 'santap kecap',
 'indo puding instan',
 'indo kopi instan',
 'rasa mi instan',
 'makmur susu kental',
 'indo sosis',
 'rasa cokelat batangan',
 'indo roti burger',
 'rasa kecap kari',
 'rasa yoghurt',
 'makmur snack ayam',
 'indo tepung pancake',
 'makmur bolu kukus',
 'nutra tahu siap',
 'selera minuman bubuk',
 'sehat roti burger',
 'makmur kue kacang',
 'bintang yoghurt',
 'indo roti burger',
 'makmur kecap kari',
 'alami tepung pancake',
 'selera keripik',
 'selera minuman bubuk',
 'bintang tepung pancake',
 'bintang snack',
 'selera mayones',
 'bintang puding instan',
 'rasa saus',
 'alami tahu siap',
 'alami kerupuk',
 'bintang bumbu penyedap',
 'alami kecap keju',
 'rasa roti burger',
 'selera yoghurt',
 'prima tepung pancake',
 'sehat nugget ayam',
 'prima yoghurt',
 'bintang kerupuk',
 'rasa sereal',
 'rasa sereal',
 'nutra saus',
 'selera sosis',
 'sehat kerupuk',
 'indo bolu kukus',
 'nutra snack jagung',
 'nutra tepung pancake',
 'prima cokelat batangan',
 'prima snack jagung',
 'alami roti burger',
 'nutra es krim',
 'santap nugget ayam',
 'bintang mi instan',
 'santap sosis',
 'sehat roti burger',
 'rasa susu kental',
 'selera biskuit vanila',
 'rasa sereal stroberi',
 'alami es krim',
 'indo bolu kukus',
 'indo snack',
 'indo nugget ayam',
 'santap roti burger',
 'santap snack',
 'alami selai kari',
 'bintang bumbu penyedap',
 'sehat kopi instan',
 'sehat bolu kukus',
 'rasa sereal',
 'nutra kopi instan',
 'prima tepung pancake',
 'nutra tahu siap',
 'sehat tahu siap',
 'indo roti burger',
 'alami saus',
 'bintang puding instan',
 'makmur selai',
 'rasa tahu siap',
 'bintang bumbu penyedap',
 'makmur sereal ayam',
 'rasa kue kacang',
 'sehat saus keju',
 'rasa snack',
 'bintang kerupuk',
 'alami nugget ayam',
 'sehat saus keju',
 'santap selai kari',
 'sehat bolu kukus',
 'bintang bolu kukus',
 'rasa bolu kukus',
 'rasa kue tart',
 'selera selai',
 'selera roti burger',
 'sehat mayones',
 'makmur es krim',
 'bintang sereal',
 'santap minuman bubuk',
 'selera kerupuk vanila',
 'bintang roti tawar',
 'selera sosis',
 'bintang snack',
 'makmur kecap ayam',
 'sehat bolu kukus',
 'selera kerupuk',
 'makmur kue kacang',
 'bintang bolu kukus',
 'bintang roti tawar',
 'bintang cokelat batangan',
 'sehat kopi instan',
 'alami bolu kukus',
 'indo puding instan',
 'prima keripik',
 'sehat puding instan',
 'bintang snack jagung',
 'prima saus',
 'makmur susu kental',
 'prima roti burger',
 'indo roti tawar',
 'santap bolu kukus',
 'bintang susu kental',
 'bintang bumbu penyedap',
 'santap es krim',
 'nutra saus',
 'makmur kerupuk ayam',
 'santap kopi instan',
 'indo kue tart',
 'rasa puding instan',
 'alami tahu siap',
 'selera es krim',
 'makmur kerupuk ayam',
 'santap yoghurt cokelat',
 'sehat kopi instan',
 'santap tahu siap',
 'santap puding instan',
 'santap keripik ayam',
 'santap sosis',
 'rasa biskuit ayam',
 'selera minuman bubuk',
 'selera tepung pancake',
 'indo sereal',
 'prima kecap ayam',
 'sehat sosis cokelat',
 'selera kopi instan',
 'indo tahu siap',
 'sehat bolu kukus',
 'alami susu kental',
 'makmur keripik',
 'santap roti burger',
 'bintang kue tart',
 'alami saus',
 'rasa kue tart',
 'nutra bolu kukus',
 'makmur sosis',
 'bintang keripik',
 'selera kue kacang',
 'alami kue kacang',
 'selera sereal',
 'indo cokelat batangan',
 'indo yoghurt vanila',
 'makmur mayones cokelat',
 'nutra susu kental',
 'selera biskuit',
 'prima keripik',
 'selera kue kacang',
 'nutra kue kacang',
 'indo roti burger',
 'sehat biskuit cokelat',
 'sehat es krim',
 'rasa saus ayam',
 'sehat tepung pancake',
 'sehat tahu siap',
 'selera snack jagung',
 'rasa bolu kukus',
 'prima selai',
 'santap roti tawar',
 'prima kerupuk',
 'nutra mayones',
 'nutra es krim',
 'selera roti tawar',
 'indo snack',
 'nutra kopi instan',
 'nutra bolu kukus',
 'sehat roti burger',
 'sehat snack jagung',
 'sehat susu kental',
 'rasa susu kental',
 'indo mi instan',
 'rasa kue kacang',
 'rasa minuman bubuk',
 'bintang kopi instan',
 'rasa kue tart',
 'santap nugget ayam',
 'makmur kue tart',
 'bintang kue kacang',
 'alami kecap',
 'alami mayones',
 'rasa nugget ayam',
 'selera kue kacang',
 'makmur roti tawar',
 'selera puding instan',
 'sehat kerupuk',
 'rasa kue tart',
 'selera saus',
 'bintang snack vanila',
 'prima kerupuk kari',
 'nutra saus',
 'selera nugget ayam',
 'makmur kue kacang',
 'indo mayones',
 'santap cokelat batangan',
 'bintang kue kacang',
 'sehat yoghurt',
 'alami kue kacang',
 'santap selai cokelat',
 'bintang nugget ayam',
 'santap sosis stroberi',
 'indo cokelat batangan',
 'nutra tahu siap',
 'nutra roti burger',
 'bintang snack jagung',
 'alami roti burger',
 'indo puding instan',
 'prima tepung pancake',
 'makmur tepung pancake',
 'indo saus',
 'alami kecap cokelat',
 'selera tepung pancake',
 'indo selai stroberi',
 'rasa sereal cokelat',
 'alami cokelat batangan',
 'rasa roti tawar',
 'bintang bolu kukus',
 'selera roti burger',
 'rasa kue tart',
 'indo es krim',
 'rasa susu kental',
 'santap kerupuk',
 'selera cokelat batangan',
 'rasa snack jagung',
 'indo kerupuk ayam',
 'indo snack',
 'rasa snack jagung',
 'sehat puding instan',
 'rasa kue tart',
 'selera kue tart',
 'sehat mayones',
 'alami mayones',
 'selera tahu siap',
 'makmur tepung pancake',
 'prima puding instan',
 'indo kecap',
 'makmur tepung pancake',
 'alami sosis',
 'makmur tepung pancake',
 'santap sereal vanila',
 'bintang biskuit',
 'santap keripik stroberi',
 'bintang kue kacang',
 'alami kue tart',
 'sehat kopi instan',
 'nutra tahu siap',
 'makmur kue kacang',
 'makmur keripik ayam',
 'alami snack jagung',
 'bintang tahu siap',
 'bintang mayones',
 'alami cokelat batangan',
 'selera roti tawar',
 'santap selai vanila',
 'selera mi instan',
 'santap susu kental',
 'indo keripik cokelat',
 'nutra keripik',
 'rasa tahu siap',
 'selera biskuit vanila',
 'nutra biskuit',
 'alami puding instan',
 'alami kopi instan',
 'indo snack jagung',
 'selera roti burger',
 'prima susu kental',
 'prima saus cokelat',
 'makmur kerupuk',
 'prima sosis',
 'selera biskuit',
 'prima puding instan',
 'makmur yoghurt vanila',
 'sehat cokelat batangan',
 'indo roti burger',
 'selera kecap ayam',
 'prima bumbu penyedap',
 'rasa mi instan',
 'rasa selai stroberi',
 'bintang sereal',
 'indo nugget ayam',
 'makmur minuman bubuk',
 'makmur sereal cokelat',
 'nutra kecap',
 'makmur tepung pancake',
 'prima kecap ayam',
 'nutra nugget ayam',
 'prima tahu siap',
 'selera kue tart',
 'bintang kerupuk',
 'bintang snack',
 'prima cokelat batangan',
 'sehat biskuit ayam',
 'selera es krim',
 'prima saus',
 'bintang kue kacang',
 'rasa sosis',
 'indo tepung pancake',
 'nutra tepung pancake',
 'bintang biskuit',
 'rasa cokelat batangan',
 'indo bolu kukus',
 'makmur snack',
 'makmur yoghurt',
 'selera mi instan',
 'makmur saus',
 'sehat es krim',
 'sehat bumbu penyedap',
 'makmur susu kental',
 'indo susu kental',
 'rasa sereal',
 'makmur keripik',
 'rasa bolu kukus',
 'makmur minuman bubuk',
 'santap snack',
 'selera kue kacang',
 'indo mi instan',
 'prima roti tawar',
 'indo yoghurt',
 'indo mayones',
 'prima kue kacang',
 'sehat kue kacang',
 'selera bumbu penyedap',
 'sehat sereal',
 'nutra roti burger',
 'nutra sosis stroberi',
 'prima roti tawar',
 'bintang snack',
 'santap sereal',
 'indo sereal stroberi',
 'alami selai',
 'alami cokelat batangan',
 'selera kerupuk',
 'selera selai keju',
 'rasa roti tawar',
 'rasa puding instan',
 'prima saus',
 'prima kecap kari',
 'nutra mi instan',
 'nutra mi instan',
 'alami bumbu penyedap',
 'selera selai',
 'selera sereal',
 'sehat kecap',
 'santap kerupuk',
 'makmur kopi instan',
 'indo sereal kari',
 'selera saus',
 'selera bolu kukus',
 'bintang bumbu penyedap',
 'makmur tepung pancake',
 'rasa roti tawar',
 'bintang snack jagung',
 'makmur snack',
 'sehat kecap',
 'nutra sereal',
 'santap puding instan',
 'makmur kerupuk',
 'santap cokelat batangan',
 'sehat kecap',
 'prima kopi instan',
 'nutra es krim',
 'sehat bumbu penyedap',
 'indo snack',
 'sehat selai',
 'prima yoghurt',
 'selera bumbu penyedap',
 'alami sosis kari',
 'bintang tepung pancake',
 'bintang snack kari',
 'alami selai',
 'sehat nugget ayam',
 'santap snack jagung',
 'makmur snack',
 'santap snack jagung',
 'nutra kue tart',
 'indo snack jagung',
 'makmur mi instan',
 'prima nugget ayam',
 'bintang biskuit',
 'santap sosis',
 'bintang biskuit',
 'santap kerupuk',
 'makmur mayones ayam',
 'santap selai',
 'nutra keripik',
 'sehat roti burger',
 'makmur puding instan',
 'nutra mayones stroberi',
 'bintang snack jagung',
 'santap sereal',
 'sehat mayones',
 'selera es krim',
 'rasa mi instan',
 'selera kopi instan',
 'prima yoghurt stroberi',
 'santap kopi instan',
 'nutra snack stroberi',
 'sehat kue kacang',
 'bintang snack jagung',
 'rasa kerupuk keju',
 'rasa mi instan',
 'santap kue kacang',
 'alami cokelat batangan',
 'alami kue tart',
 'nutra snack kari',
 'nutra es krim',
 'selera bolu kukus',
 'bintang snack jagung',
 'sehat mi instan',
 'bintang kecap',
 'makmur tahu siap',
 'indo kue kacang',
 'indo sosis cokelat',
 'selera roti tawar',
 'makmur sosis',
 'makmur es krim',
 'sehat tahu siap',
 'rasa snack',
 'makmur susu kental',
 'alami mi instan',
 'bintang roti burger',
 'rasa sosis ayam',
 'indo bumbu penyedap',
 'rasa selai kari',
 'nutra mayones keju',
 'santap yoghurt',
 'prima kecap',
 'sehat roti burger',
 'nutra kecap keju',
 'bintang kopi instan',
 'nutra snack',
 'sehat bumbu penyedap',
 'makmur yoghurt',
 'indo es krim',
 'rasa susu kental',
 'makmur sosis',
 'rasa sereal vanila',
 'santap kopi instan',
 'rasa roti burger',
 'selera kerupuk stroberi',
 'rasa kue tart',
 'makmur roti burger',
 'rasa tahu siap',
 'selera saus',
 'nutra kopi instan',
 'santap bolu kukus',
 'sehat nugget ayam',
 'selera cokelat batangan',
 'bintang biskuit',
 'indo bolu kukus',
 'alami yoghurt',
 'prima susu kental',
 'prima mi instan',
 'nutra roti tawar',
 'nutra roti burger',
 'bintang kue kacang',
 'santap snack jagung',
 'selera cokelat batangan',
 'sehat roti burger',
 'prima es krim',
 'sehat es krim',
 'makmur puding instan',
 'makmur biskuit',
 'selera kecap',
 'makmur roti tawar',
 'makmur roti tawar',
 'bintang es krim',
 'rasa tepung pancake',
 'selera sosis',
 'alami biskuit',
 'bintang tahu siap',
 'bintang kerupuk',
 'selera snack jagung',
 'selera sosis',
 'indo nugget ayam',
 'santap saus cokelat',
 'bintang cokelat batangan',
 'santap mayones',
 'makmur tepung pancake',
 'selera snack kari',

In [15]:
df_steakhouse = pd.read_csv(menu_dir, sep=';')
df_steakhouse.head()

,no,restaurant_name,city,district,place,unique_menu,price,google_rating,google_count,platform_rating,...,dessert,other_poultry,takeaway,delivery,outdoor,smoking_area,alcohol_served,wifi,reservation,other
0,1,Tucano's Churrascaria,Central Jakarta,Sudirman,Senayan City,Classic Beef 90 minutes,268000,4.7,330.0,4.7,...,ice cream,no,yes,yes,yes,yes,"cocktail, wine, beer, highball",yes,yes,"buffet, bar, live entertainment, private dining"
1,2,Kitchenette,South Jakarta,Senayan,Senayan City,Kitchenette Steak Frites,205000,4.5,745.0,4.1,...,"crepe, cake, pie",seafood,yes,no,no,no,"wine, beer, cocktail, liquor, spirit",yes,yes,no
2,3,Tony Roma's,Central Jakarta,Thamrin,UOB Plaza,Baby Back Ribs with Fish Fillet,170000,4.5,559.0,4.6,...,"ice cream, cake, special etc.","pork, seafood",no,no,no,no,"liquor, rum, tequila, gin, vodka, whiskey etc",yes,yes,no
3,4,Gandy Steak House,Central Jakarta,Menteng,Owned place,Grilled Australian Tenderloin,191000,4.5,2041.0,4.3,...,"ice cream, gelato","seafood, lamb",yes,no,no,no,"cocktail, wine, beer",yes,yes,bakery
4,5,Joni Steak,Central Jakarta,Gajah Mada,Owned place,Wagyu Top Side,72000,4.5,5093.0,4.1,...,"banana split, cream brulee",seafood,yes,yes,no,no,no,no,no,no

In [16]:
raw_steakhouse = df_steakhouse['unique_menu'].dropna().tolist()
raw_steakhouse

['Classic Beef 90 minutes',
 'Kitchenette Steak Frites',
 'Baby Back Ribs with Fish Fillet',
 'Grilled Australian Tenderloin',
 'Wagyu Top Side',
 'Tomahawk Bone In Rib Eye Steak',
 'Chivito Plato',
 'Sirloin Double with Brown Sauce',
 "Wagyu Rib Eye Ranger's Valley",
 'Australian Prime Tenderloin',
 'Round Steak',
 'Wagyu Rib Eye',
 'Tenderloin Steak',
 'Filet Amigon TM & Steak',
 'Prime Sirloin Original Regular',
 'Brisket 100gr',
 'Sirloin Steak',
 'Hokubee Sirloin 200gr',
 'New York Strip',
 'Sirloin Strip',
 'Sirloin Cheese Steak',
 'Saikoro Tenderloin Steak',
 'Braised Beef',
 'US Prime Sirloin Steak',
 'Waterfall Sirloin on Hot Plate',
 'Wagyu Beef Tagliata',
 'Australian Gras Fed Tenderloin 160gr',
 'Wagyu Beef Sirloin Grade 5',
 'Filetto di Manzo in Salsa Al Gorgonzola',
 'La Spada ',
 'Kobe Beef 200gr',
 'Porterhouse Steak Florentine Style',
 'Angus Rib Eye',
 'Tenderloin 200gr',
 'Grilled Steak Sandwich with Black Angus Tenderloin',
 'USDA Prime Rib Eye Pepper Steak',
 'Fileto Al Pepe 130gr',
 'Dry Aged Beef',
 'Prime Sirloin Original Regular',
 'Steak aus Champignons',
 'Australian Wagyu Tomahawk',
 'Petite Filet and Shrimp',
 'Beef Parmigiana',
 'Beef Ribs Lollipop',
 'Meatville Australian PR Striploin (per gram)',
 'Steak Platter (Grilled Sirloin & Tomahawk)',
 'Southern Styles Beef Ribs Half Rack (2 sides)',
 'Hickhory Back Ribs',
 'New York Striploin 300gr',
 "Wagyu Tenderloin Ranger's Valley",
 'Tenderloin',
 'New Zealand T-Bone ',
 'The Original Baby Back Ribs Regular',
 'Wagyu Riserva 9+ Picanha 100gr',
 'Wagyu Back Ribs 4 Bones',
 'Vins Aust Special',
 'AUS Tenderloin',
 'Sirloin Double Mushroom',
 'Filetto Al Pepe Verde',
 'Grilled Australian Tenderloin',
 'Sirloin Double',
 'Wagyutaki Steak',
 'Tenderloin Lokal Besar',
 'Porterhouse for Two',
 'Black Angus Sirloin',
 'Bifes Con Cebolla',
 'Outback Special 6oz',
 'USDA Choice Beef Striploin 300gr',
 'Tenderloin Mushroom Steak',
 'Sirloin Australian 180gr',
 'Beef Sirloin Marsala Sauce',
 'A5 Level Prime Wagyu Sirloin Steak',
 'Steak Lidah',
 'Sirloin Steak',
 '30 Days NY Strip',
 'AUS Chateaubriand',
 'Aussie Lamb Chop',
 'Premium T-Bone',
 'Denver Steak 200gr',
 'The Middleweight',
 'T-Bone Steak',
 'Prime Kuroge Chateaubriand',
 'Braised Beef Pie and Chips',
 'Signature Beef Ribs Half Rack',
 'Australian Wagyu T-Bone Steak',
 "M9 J'S Wagyu Striploin 200gr",
 'Beef Stroganof',
 'Porcini Coffee Rubbed Steak',
 'Crispy Breaded Chicken Steak',
 'Wagyu Brisket 200gr',
 'Prime Rib Eye 200gr',
 'Sirloin Wagyu 200gr',
 'Angus Sirloin 150gr + Chicken Steak',
 'Tokusen Wagyu Rib Eye',
 'Jujuyaki Steak',
 'Steak Combo Jumbo Keju Mayonaise',
 'Filet Amignon & Malibu Chicken',
 'WB Steak Tokusen Rib Eye 160gr',
 'Norwegian Salmon Steak',
 'Tatsuya Course',
 'Salmon Steak',
 'Wagyu Minute Steak',
 "Buddy's Special",
 'Honey Baby Back Ribs Large',
 'Triple Sirloin',
 'Grilled Australian Lamb Leg',
 'DS Steak Platter',
 'Chicken Cheese HP',
 'Rib Eye New Zealand',
 'Full Rack BBQ Baby Back Ribs',
 'Sanchoku Wagyu Rib Eye 200gr',
 'Australian Prime Big Bite Sirloin',
 'Park Lane Steak 200gr',
 'Victorian Tenderloin',
 'Honey Baby Back Ribs Regular',
 'Rib Eye Australia',
 'Secondary Cut Wagyu 200gr',
 'Volcano and The Ring of Fire',
 'Wagyu Rib Eye Steak',
 'New Zealand Lamb Chop',
 'Kolonel Burger Steak',
 'Paket C Supreme',
 'Rib Eye Large',
 'Wagyu OZ',
 'Sheriff Steak',
 'Norwegian Salmon Grill',
 'Wagyu Brisket Fatty 180gr (meat only)',
 'Parkiran T-Bone 200gr',
 'Pleasure Pork Ribs',
 'Hibachi Steak Hokubee Sirloin',
 'Salmon Trout',
 'Tomahawk',
 'US T-Bone Steak',
 'Australian Prime Big Bite Sirloin',
 'Wagyu Tenderloin 200gr',
 'New Zealand Sirloin ',
 'AUS Wagyu Meltique Rib Eye 150gr',
 'Prime Sirloin Original Regular',
 'Prime Sirloin Original Regular',
 'Wagyu Top Blade',
 'Steak Waroeng with Cheese Sauce',
 'Wagyutaki Steak',
 'Burger Steak',
 'Steak Tepung Beef Double',
 'Australian Prime Big Bite Sirloin',
 'Sirloin Crispy Steak',
 'Mozarella Sirloin',
 'Fried Chicken Steak',
 'Grill Ribs Large 1000gr',
 'Chicken Steak']

In [17]:
clean_steakhouse = []

for item in raw_steakhouse:
    item = re.sub(r'\(.*?\)', '', item).strip()

    short_item = " ".join(item.split()[:3]).lower()
    clean_steakhouse.append(short_item)

In [18]:
clean_steakhouse

['classic beef 90',
 'kitchenette steak frites',
 'baby back ribs',
 'grilled australian tenderloin',
 'wagyu top side',
 'tomahawk bone in',
 'chivito plato',
 'sirloin double with',
 'wagyu rib eye',
 'australian prime tenderloin',
 'round steak',
 'wagyu rib eye',
 'tenderloin steak',
 'filet amigon tm',
 'prime sirloin original',
 'brisket 100gr',
 'sirloin steak',
 'hokubee sirloin 200gr',
 'new york strip',
 'sirloin strip',
 'sirloin cheese steak',
 'saikoro tenderloin steak',
 'braised beef',
 'us prime sirloin',
 'waterfall sirloin on',
 'wagyu beef tagliata',
 'australian gras fed',
 'wagyu beef sirloin',
 'filetto di manzo',
 'la spada',
 'kobe beef 200gr',
 'porterhouse steak florentine',
 'angus rib eye',
 'tenderloin 200gr',
 'grilled steak sandwich',
 'usda prime rib',
 'fileto al pepe',
 'dry aged beef',
 'prime sirloin original',
 'steak aus champignons',
 'australian wagyu tomahawk',
 'petite filet and',
 'beef parmigiana',
 'beef ribs lollipop',
 'meatville australian pr',
 'steak platter',
 'southern styles beef',
 'hickhory back ribs',
 'new york striploin',
 "wagyu tenderloin ranger's",
 'tenderloin',
 'new zealand t-bone',
 'the original baby',
 'wagyu riserva 9+',
 'wagyu back ribs',
 'vins aust special',
 'aus tenderloin',
 'sirloin double mushroom',
 'filetto al pepe',
 'grilled australian tenderloin',
 'sirloin double',
 'wagyutaki steak',
 'tenderloin lokal besar',
 'porterhouse for two',
 'black angus sirloin',
 'bifes con cebolla',
 'outback special 6oz',
 'usda choice beef',
 'tenderloin mushroom steak',
 'sirloin australian 180gr',
 'beef sirloin marsala',
 'a5 level prime',
 'steak lidah',
 'sirloin steak',
 '30 days ny',
 'aus chateaubriand',
 'aussie lamb chop',
 'premium t-bone',
 'denver steak 200gr',
 'the middleweight',
 't-bone steak',
 'prime kuroge chateaubriand',
 'braised beef pie',
 'signature beef ribs',
 'australian wagyu t-bone',
 "m9 j's wagyu",
 'beef stroganof',
 'porcini coffee rubbed',
 'crispy breaded chicken',
 'wagyu brisket 200gr',
 'prime rib eye',
 'sirloin wagyu 200gr',
 'angus sirloin 150gr',
 'tokusen wagyu rib',
 'jujuyaki steak',
 'steak combo jumbo',
 'filet amignon &',
 'wb steak tokusen',
 'norwegian salmon steak',
 'tatsuya course',
 'salmon steak',
 'wagyu minute steak',
 "buddy's special",
 'honey baby back',
 'triple sirloin',
 'grilled australian lamb',
 'ds steak platter',
 'chicken cheese hp',
 'rib eye new',
 'full rack bbq',
 'sanchoku wagyu rib',
 'australian prime big',
 'park lane steak',
 'victorian tenderloin',
 'honey baby back',
 'rib eye australia',
 'secondary cut wagyu',
 'volcano and the',
 'wagyu rib eye',
 'new zealand lamb',
 'kolonel burger steak',
 'paket c supreme',
 'rib eye large',
 'wagyu oz',
 'sheriff steak',
 'norwegian salmon grill',
 'wagyu brisket fatty',
 'parkiran t-bone 200gr',
 'pleasure pork ribs',
 'hibachi steak hokubee',
 'salmon trout',
 'tomahawk',
 'us t-bone steak',
 'australian prime big',
 'wagyu tenderloin 200gr',
 'new zealand sirloin',
 'aus wagyu meltique',
 'prime sirloin original',
 'prime sirloin original',
 'wagyu top blade',
 'steak waroeng with',
 'wagyutaki steak',
 'burger steak',
 'steak tepung beef',
 'australian prime big',
 'sirloin crispy steak',
 'mozarella sirloin',
 'fried chicken steak',
 'grill ribs large',
 'chicken steak']

In [19]:
df_prod = pd.read_csv(prod_dir)
df_prod.head()

,review_text,review_date,review_id,product_name,product_category,product_variant,product_price,product_url,product_id,rating,sold_count,shop_id,sentiment_label
0,baru sekali ini terima brg dr belanja online d...,2024-12-22,1134256160,Telur Ayam Kampung Asli - Telur Mengandung Ome...,Makanan & Minuman,Box Polos,87000,https://www.tokopedia.com/indofarmproduct/telu...,4601033481,5,1000000,8672687,positive
1,cocok bgt aku sama telur nya. nga Amis menurut...,2025-02-25,1242584634,Telur Ayam Kampung Asli - Telur Mengandung Ome...,Makanan & Minuman,Box Polos,87000,https://www.tokopedia.com/indofarmproduct/telu...,4601033481,5,1000000,8672687,positive
2,Telornya sudah sampai di rumah dengan kemasan ...,2025-07-15,1573444677,Telur Ayam Kampung Asli - Telur Mengandung Ome...,Makanan & Minuman,Box Polos,87000,https://www.tokopedia.com/indofarmproduct/telu...,4601033481,5,1000000,8672687,positive
3,Telor sudah diterima dengan baik dan tidak ada...,2025-07-20,1581728541,Telur Ayam Kampung Asli - Telur Mengandung Ome...,Makanan & Minuman,Box Polos,87000,https://www.tokopedia.com/indofarmproduct/telu...,4601033481,5,1000000,8672687,positive
4,"Alhamdulillah penjual amanah,Telor nya terbaik...",2023-04-24,881041355,Telur Ayam Kampung Asli - Telur Mengandung Ome...,Makanan & Minuman,Box Full Design,87000,https://www.tokopedia.com/indofarmproduct/telu...,4601033481,5,1000000,8672687,positive

In [20]:
raw_prod = df_prod['product_name'].dropna().tolist()
clean_prod = []

for item in raw_prod:
    item = str(item).split('-')[0].strip()

    short_item = " ".join(item.split()[:3]).lower()
    clean_prod.append(short_item)
    
clean_prod

['telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur omega 3',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur hijau dari',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 'telur ayam kampung',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'frisian flag omega',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti tawar gendut',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'roti bunting beef',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'paikut super sop',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'roti tawar kentang',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'sedaap mie instan',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'milku susu uht',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'ensure gold hmb',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'kraft keju all',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'gepuk ny ong',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'kraft keju leleh',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'sasa tepung bumbu',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'kraft cheese cheddar',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'dough lab',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene actifit 3x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'haan wippy cream',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'ritz cracker biskuit',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'mondelez ritz cracker',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 '(bundling 2 box)',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 'anlene gold 5x',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 '(paket 3 botol)',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'chiki ball ayam',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 'daging giling babi',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 '[ hadiah ]',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'gepuk ny.ong rasa',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'tomat',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'ikan salmon trout',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'hungry alana',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'telur putih premium',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'kobe tepung ayam',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',
 'sedaap baked mie',

In [21]:
df_prod2 = pd.read_csv(produk_dir)
df_prod2.head()

,Nama Produk,Nama Toko,Lokasi Toko,Terjual,Jumlah Ulasan,Rating,Harga (IDR),Diskon (%),Produk URL
0,Raw Food Beef Bone-In / Daging Giling / Dog Fo...,Lazy Dog Supply,Jakarta Selatan,1rb+ terjual,10 ulasan,5.0,35000,0.0,https://www.tokopedia.com/lazy-dog-supply/raw-...
1,Turkey Meat ONLY NO BONE - 1KG - Daging Kalkun...,RumahBully,Jakarta Timur,250+ terjual,NaN,5.0,79999,0.0,https://www.tokopedia.com/rumahbully/turkey-me...
2,Chicken mix Salmon Raw Food ayam mix salmon ma...,RumahBully,Jakarta Barat,26 terjual,NaN,5.0,33000,0.0,https://www.tokopedia.com/rumahbully/chicken-m...
3,PROMO BULANAN - SOSIS CHOP PREMIUM RAW - DOG F...,RumahBully,Tangerang Selatan,100+ terjual,NaN,5.0,29900,0.0,https://www.tokopedia.com/rumahbully/promo-bul...
4,Premium Dog Food / Daging Sapi Giling / Raw Fo...,RumahBully,Jakarta Selatan,1rb+ terjual,NaN,5.0,39000,0.0,https://www.tokopedia.com/rumahbully/premium-d...

In [22]:
raw_prod2 = df_prod2['Nama Produk'].dropna().tolist()
clean_prod2 = []

for item in raw_prod2:
    item = str(item).split('-')[0].strip()

    short_item = " ".join(item.split()[:3]).lower()
    clean_prod2.append(short_item)
    
clean_prod2

['raw food beef',
 'turkey meat only',
 'chicken mix salmon',
 'promo bulanan',
 'premium dog food',
 'complete dog raw',
 'dog & cat',
 'raw food chicken/cat',
 'papillon makanan anjing',
 'paket turkey meat',
 'rawfood',
 'dog food daging',
 'rumahbully | smoke',
 'pure sirloin beef',
 'premium dog food',
 'raw food pork',
 'dogma raw food',
 'daging bebek giling',
 'kin dog food',
 'vitayang raw meal',
 'rawfood',
 'super premium beef',
 'chicken reguler',
 'ayam daging giling',
 'pure turkey meat',
 'rabbit all in',
 'ayam mix sapi',
 'primal kibble in',
 'the honest recipe',
 'life cat plus',
 'san pet kitchen',
 'nutriale chicken with',
 'ayrus cat food',
 'raw rawr lamb',
 'domba – lamb',
 'coucou dog food',
 'raw rawr lamb',
 'nutriale chicken with',
 'papillon makanan anjing',
 'pet kingdom papillon',
 'papillon goat milk',
 'raw food daging',
 'premium raw food',
 'raw food dog',
 'daging raw food',
 'paket promo 5kg',
 'raw dog food',
 'beef reguler –',
 'dog & cat',
 'beef & buffalo',
 'rawfood filet dada',
 'rumahbully | cat',
 'pure turkey meat',
 'termurah',
 'rawfood',
 'raw food chicken',
 'raw food lamb',
 'nutriale liver support',
 'dog & cat',
 'super weight booster',
 'complete dog raw',
 'raw rawr kangaroo',
 'rawrawr freeze dried',
 '[5 kg] all',
 'j.d raw food',
 'j.d raw food',
 'meatime salmon 100%',
 'meatime tenderloin daging',
 'meatime briscat paket',
 'the honest recipe',
 'nutriale skin support',
 'diskon dog /',
 'fresh beef burger',
 'duck roasted bone',
 'duck floss (50gr/pack)',
 'turkey sosis (90gr/pack)',
 'the honest recipe',
 'organic lamb liver',
 'raw food pork',
 'goat original //',
 'dog & cat',
 'premium dog food',
 'super beef boneless',
 'premium boneless chicken',
 'premium dog food',
 'raw food rr',
 'raw food pawdeli',
 'raw food kucing',
 'rockbros arm sleeve',
 'rockbros manset lengan',
 'mambobaby sun shield',
 'hotshow handsock manset',
 'arm sleeve manset',
 'manset lengan panjang',
 'aonijie e4122 arm',
 'aonijie 4039 arm',
 'aonijie e4121 arm',
 'zou9 manset tangan',
 'manset tangan pendek',
 'bisa cod manset',
 '3 pcs manset',
 'manset baju /',
 'manset tangan jumbo/',
 'manset premium basic',
 'manset tangan sambung',
 'manset tangan bolero',
 'lintang handsock',
 'new handsock jempol',
 'diskon handsock jempol',
 'diskon handsock tanpa',
 'hia everywear bassama',
 'sepasang handsock /',
 'valmar',
 'cufflinks cufflinks manset',
 'baselayer manset waldos',
 'rockbros xt060 manset',
 'manset outdoor manset',
 'manset menyusui busui',
 'manset atasan turtle',
 'manset bolero lengan',
 'inner span long',
 'manset gamis jersey',
 'manset hamil menyusui',
 'biiu kaos manset',
 'manset lengan unisex',
 'manset kaos lengan',
 'inner tunik satin/inner',
 'manset buntung |',
 'manset premium basic',
 'manset jumbo rayon',
 'manset baju manset',
 'manset tanpa lengan',
 'manset tangan sepeda',
 'hia everywear deerya',
 'lozy hijab',
 'savana manset outdoor',
 'terrel sportswear basic',
 'antarestar official',
 'bisa cod baselayer',
 'dhaulagiri baselayer t',
 'biiu manset gamis',
 'yasta fashion',
 'diario',
 'avtech',
 'hotshow handsock manset',
 'fame | 9911054',
 'tulandut anti uv',
 'alif calla manset',
 'hijaberies',
 'lozy hijab',
 'hijaberlin',
 'handsock manset tangan',
 'nabnib',
 'manset tangan handsock',
 'hia everywear bassama',
 'hia everywear deerya',
 'baju manset anak',
 'miranda manset anak',
 'baju manset anak',
 'hijaberlin',
 'manset spendek lengan',
 'manset baju polos',
 'manset tangan sambung',
 'handsock renda semua',
 'hijaberlin',
 'diskon 12.12 manset',
 'hia everywear bassama',
 'manset tangan tebal',
 'manset tangan tebal',
 'manset / deker',
 'diskon handsock tanpa',
 'manset tangan panjang',
 'diskon 12.12 manset',
 'sepasang handsock /',
 'manset tangan panjang',
 'noxious base layer',
 'rockbros arm sleeve',
 'aonijie e4122 arm',
 'aonijie 4039 arm',
 'baselayer manset tiento',
 '[hot product] baselayer',
 'baselayer manset tiento',
 'tiento hand sleeve',
 'rockbros manset kaki',
 'aonijie 4036 arm',
 'yellowcorn yas',
 'manset tangan jaco',
 'firecast | leg',
 'dhaulagiri arm sleeve',
 'manset kaki aolikes',
 'waldo east (original)',
 '[hot product] baselayer',
 'cosmos blender 3',
 'blendjet 2 usa',
 'de_best.store juicy stay',
 'nutribullet blender combo',
 'tergacor tnw jus',
 'philips hr2042/33 blender',
 'baru',
 'miyako blender 1.5',
 'miyako blender bl',
 'mitochiba ch 200',
 'kirin blender juicer',
 'mitochiba chopper blender',
 'lunalife chopper mini',
 'advance chp',
 'philips blender series',
 'ecentio 2 cup',
 'mitochiba ch',
 'mitochiba ch 200',
 'blender philips plastik',
 'miisoo blender tarik',
 '[ advance x',
 'ecentio mini chopper',
 'chopper blender daging',
 'philips blender 5000',
 '[cod] han river',
 '【tokopedia exclusive】simplus chopper',
 'turbo blender plastik',
 'samono mini chopper',
 '【exclusive kingkevin】advance bl',
 'lunalife chopper mini',
 'miyako blender 1.5',
 'cosmos blender blenz',
 'sharp blender plastik',
 'han river blender',
 'philips blender 5000',
 'philips blender plastik',
 'philips blender 5000',
 'ecentio mini portable',
 'miyako blender plastik',
 'cosmos blender cb',
 'sharp | em',
 'panasonic mx',
 'samono sw',
 'philips blender series',
 'blender turbo lengkap',
 'advance 1003t stand',
 'alltou blender portable',
 'maimeite chopper &',
 'informa kels 500',
 '[garansi murah] cosmos',
 '[garansi murah] miyako',
 '[garansi murah] cosmos',
 'getra heavy duty',
 'hand blender panasonic',
 'blender cosmos csm',
 'sonifer hand blender',
 'ninja foodi power',
 'steven stenly x',
 'cosmos blender blenz',
 'miyako blender kaca',
 'beaute basique blender',
 'beaba baby babycook',
 'blender cosmos gelas',
 '[cod] cosmos blender',
 'cosmos cb',
 'philips hr2116 blender',
 'philips blender hr',
 'philips blender plastik',
 'philips blender 1l',
 'miyako bl101gs blender',
 'miyako blender kaca',
 'miyako blender 1.5',
 'blender national omega',
 'miyako blender plastik',
 'sharp cookwear em',
 'cosmos blender kaca',
 'sharp blender em',
 'philips hr2042 33',
 'ecentio slow juicer',
 'ecentio slow juicer',
 'ecentio slow juicer',
 'ecentio chopper blender',
 'promo termurah blender',
 'miyako blender bl',
 'cosmos blender kaca',
 'philips blender glass',
 'blender cantik unik',
 'barang unik gelas',
 'samono chopper magic',
 'mason juicer blender',
 'blender 3in1 glass',
 'promo olike blender',
 'beaute basique blender',
 'cermin kamar mandi',
 'kaca cermin kamar',
 'kaca cermin serbaguna',
 'cermin rias aesthetic',
 '12 pcs kaca',
 'cermin rias lipat',
 'cermin aesthetic dinding',
 'cermin bevel kapsul',
 'cermin bulat dinding',
 'minimaly cermin rotan',
 'cermin dinding minimalis',
 'cermin badan standing',
 'cermin klasik aestetic',
 'cermin berdiri standing',
 'cermin dinding klasik',
 'kaca dinding kayu',
 'cermin dinding ukiran',
 'wall mirror cermin',
 'cermin dinding industrial',
 'cermin full body',
 'lbt cermin bulat',
 'standing mirror cermin',
 'kaca cermin rias',
 'cermin oval kapsul',
 'bisa cod 831',
 'standing mirror/cermin berdiri',
 'cermin standing frameless',
 'cermin bulat aesthetic',
 'pasang kaca cermin',
 'kaca cermin 120x40cm',
 'adapta',
 'scoop dekorasi dinding',
 'ikea enhet cermin',
 'meth 6 pcs',
 'daiso hanging and',
 'dekoruma kika standing',
 'figura bulat estetik',
 'dekorasi dinding stiker',
 'cermin rias make',
 'cermin kayu jati',
 'cermin dinding/ cermin',
 'aesthetic mirror cermin',
 'rak cermin gantung',
 'kaca cermin gantung',
 'adapta lemari tas',
 'fantasy cermin dinding',
 'olympic lemari pakaian',
 'cermin aesthetic cermin',
 'adapta',
 'cermin dinding kayu',
 'cermin wastafel toilet',
 'cermin gantung bulat',
 'stockayu.id',
 'stockayu.id',
 'cermin led touchscreen',
 '[custom] cermin bevel',
 'cermin full body',
 'standing mirror mee',
 'ikea enhet cermin',
 'ikea metro cermin',
 'ikea drommare cermin',
 'azko fosa 70x50',
 'azko forhom cermin',
 'dekoruma mika cermin',
 'kaca cermin 120x40cm',
 'cermin standing full',
 'antbox lemari pakaian',
 'informa cermin lantai',
 'kaca cermin 80x60cm',
 'kaca cermin 60x40cm',
 'kaca cermin rias',
 '[custom po] cermin',
 'standing mirror full',
 'standing mirror frameless',
 'cermin dinding besar',
 'cermin dinding gantung',
 'cermin gantung ovale',
 'irregular mirror mr.',
 'cermin kaca estetik',
 'cermin dinding aesthetic',
 'cermin empuk standing',
 'kaca cermin arch',
 '[custom] cermin bevel',
 'cermin setengah oval',
 'cigemoy.xxi cermin bulat',
 'kaca cermin bulat',
 'cermin persegi',
 'cermin dinding besar',
 'cermin oval kapsul',
 'cermin bulat frame',
 'diskon cermin standing',
 'cermin / kaca',
 'cermin / kaca',
 'micton lion star',
 'cermin dinding berkualitas',
 '(sale!) cermin gantung',
 'cermin aesthetic dinding',
 'cermin led aesthetic',
 'cermin kayu jati',
 'kaca spion 5',
 'cermin cermin dinding',
 'jas hujan raincoat',
 'basiclusive',
 'jas hujan plastik',
 'jas hujan ponco',
 'size m merah',
 'mantel bayi karakter',
 'jas hujan ponco',
 'jas hujan bintang',
 'jas hujan dewasa',
 'isi 12 jas',
 'jas hujan plastik',
 'jas hujan plastik',
 'jas hujan ponco',
 'jas hujan security',
 'jas hujan jaket',
 'jas hujan akula',
 'zaltan raincoat setelan',
 'jubah set topi',
 'jas hujan pvc',
 'jas hujan ponco',
 'jubah drakula kostum',
 'kostum jubah labu',
 'nikolai gogol',
 'jubah dino cosplay',
 'jas hujan ponco',
 'jas hujan muslimah',
 'pita reflektif skotlet',
 'azko otto klasse',
 'omg long coat',
 'hijacket belva',
 'jubah emas kostum',
 'zaltan raincoat setelan',
 'jaket kulit casual',
 'mantel ibu sweater',
 'mantel ibu rajut',
 'blus atasan wanita',
 'dhaulagiri jas hujan',
 'coat blazer panjang',
 'jaket bulu imitasi',
 'jas hujan oseal',
 'goto [cod] inari',
 'avetch',
 'grosir jas hujan',
 'jas hujan ponco',
 'toko lucky 88',
 'jas hujan dewasa',
 'acold raintol kangaroo',
 'jas hujan mantel',
 'axio raincoat xin',
 'elmondo ponco celana',
 'jas hujan mantel',
 'dhaulagiri jas hujan',
 'jas hujan ponco',
 'mantel jas hujan',
 'promo jas hujan',
 'raincoat akula jas',
 'mantel hujan |',
 'nikolai gogol',
 'jas hujan akula',
 'tas ransel sekolah',
 'hanke tas ransel',
 'nfbandung new arrival..!!',
 'tas ransel karakter',
 'tas ransel anak',
 'tas ransel sekolah',
 '[yumnahanabags] tas ransel',
 'tas ransel anak',
 'tas grosir surabaya',
 'tas sekolah anak',
 'tas ransel wanita',
 'nfbandung *cod* tas',
 'tas ransel sekolah',
 'rafatar',
 'cod&ready tas ransel',
 'tas ransel sekolah',
 'roygasstore',
 'tas ransel laptop',
 'tas ransel sekolah',
 'tas ransel sekolah',
 'tas ransel anak',
 'aimilo tas sekolah',
 'tas ransel sekolah',
 'paket hemat 5in1',
 'tas ransel sekolah',
 'tas sekolah kuromi',
 'tas ransel sekolah',
 'tas ransek sekolah',
 'tas ransel sekolah',
 'hyena x hytrix',
 'tas ransel anak',
 'samata tas ransel',
 'tas selempang tas',
 'mommykiddo terlaris tas',
 'kedaibutik (495) tas',
 'lmb tas anak',
 'tas ransel sekolah',
 'jansport tas ransel',
 'ransel premium tas',
 'tas ransel sekolah',
 '(bisa cod)tas ransel',
 'onebear y2k backpack',
 'tas ransel pria',
 'best seller tas',
 'tas ransel /',
 'ransel gendong pria',
 'onebear tas ransel',
 'tas sekolah sd',
 'tas ransel sekolah',
 'ransel sekolah sd',
 'hyena (sja68)',
 'hytrix (dh29)',
 'adinata tas sekolah',
 'polo alvis',
 'velatric official store',
 'kanemochi bag ransel',
 'inficlo tas ransel',
 'speeds store official',
 'buffback tas ransel',
 'sakumini tas ransel',
 'goldies tas ransel',
 'skoola tas sekolah',
 'pushop authentic',
 'jims honey official',
 'okatz tas ransel',
 'nionbagshop tas ransel',
 'newtonkids',
 'skoola backpack',
 'backpack harian tas',
 'tas ransel tnf',
 'betterhalf',
 'excellent',
 'mlf goods',
 'cinnamoroll cute backpack',
 'teeva tas ransel',
 'tas sekolah anak',
 'tas sekolah anak',
 'tas ransel anak',
 'tas ransel sekolah',
 'fashion byi tas',
 'wwh26 tas anak',
 'paket komplit tas',
 'tas 3 in',
 'kedaibutik (495) tas',
 '{ promo }',
 'tas ransel laptop',
 '{ promo }',
 'promo back to',
 '[promo spesial 12.12]',
 '【promo 12.12】mkmc shop',
 'tas anti maling/"ready',
 'harga diskon !!!',
 '[diskon 50%] miniso',
 'ready big diskon',
 'promo tas ransel',
 'lumina backpack tas',
 'tas ransel warna',
 'siena backpack tas',
 'promo back to',
 'mkmc tas ransel',
 'mkmc shop mini',
 'tas ransel sekolah',
 'tas ransel backpack',
 'oxigen albany o',
 'micals',
 'paket sound system',
 'paket sound system',
 'toa sound system',
 'paket sound system',
 'paket sound system',
 'speaker corong toa',
 'corong toa zh',
 'paket sound system',
 'paket sound system',
 'paket sound system',
 'paket sound system',
 'paket speaker toa',
 'paket sound system',
 'ampli toa 120',
 'power mixer amplifier',
 'speaker toa 30',
 'toa horn speaker',
 'cod sunbuck amplifier',
 'speaker toa zs',
 'amplifier ampli toa',
 'speaker corong toa',
 'paket toa masjid',
 'toa speaker corong',
 'corong speaker masjid',
 'paket sound system',
 'paket sound system',
 'paket sound system',
 'paket sound system',
 'paket sound system',
 "paket sound system'",
 'paket sound system',
 'paket sound masjid',
 'paket salon toa/paket',
 'paket sound toa',
 'paket sound system',
 'paket speaker toa',
 'paket sound system',
 'toa speaker corong',
 'paket sound system',
 'paket sound system',
 'paket sound system',
 'paket sound system',
 'paket sound masjid',
 'paket salon toa/paket',
 'paket speaker toa',
 'corong speaker masjid',
 'toa paket tata',
 'toa paket tata',
 'toa paket tata',
 'toa paket tata',
 'toa paket set',
 'toa paket set',
 'toa zh',
 'toa za',
 'toa zm',
 'toa zh',
 'horn speaker toa',
 'corong speaker masjid',
 'toa zm',
 'toa za',
 'paket sound system',
 'paket sound system',
 'paket sound masjid',
 'paket toa masjid',
 'paket sound system',
 'paket sound toa',
 'paket sound system',
 'paket sound system',
 'toa speaker corong',
 'paket speaker toa',
 'paket sound system',
 'paket sound system',
 'paket toa masjid',
 'paket toa masjid',
 'toa megaphone megaphone',
 'sound system toa',
 'sound system toa',
 'toa horn speaker',
 'paket speaker toa',
 'toa speaker corong',
 'corong speaker masjid',
 'paket sound system',
 'paket toa masjid',
 'power amplifier ashley',
 'amplifier toa za',
 'amplifier fc a8240',
 'paket sound toa',
 'paket sound toa',
 'paket sound toa',
 'paket sound toa',
 'e196 paket sound',
 'paket sound system',
 'paket sound system',
 'mineral botanica thermo',
 'ecer!! 794b eyeshadow',
 'chocolate glitter eyeshadow',
 '40 color eyeshadow',
 'eyeshadow palette korean',
 'implora urban eyeshadow',
 'eyeshadow implora 12',
 'eyeshadow palette nvu',
 'beauty glazed |',
 'mac x patric',
 'eyeshadow palette 9',
 'inez eye shadow',
 'lameila 12 colour',
 'wardah eyeshadow classic',
 'eyeshadow dompet',
 'dikalu milk tea',
 'eyeshadow 3 warna',
 'rose all day',
 'urracx eyeshadow palette',
 'salsa galaxy eyeshadow',
 'eyeshadow palette korean',
 'eyeshadow mini mugeleen',
 'pinkflash 4in1 multiple',
 'eyeshadow pallete matte',
 'novo eye shadow',
 '(promo) focallure pro',
 'pinkflash pinkdessert eyeshadow',
 'wardah eyexpert eye',
 'make over trivia',
 'esqa goddess eyeshadow',
 'emina pop rouge',
 'saniye exclusive live',
 'wardah colorfit quad',
 'make over eye',
 'pinkflash',
 'focallure sunset eyeshadow',
 'pinkflash multi',
 'inez loose eye',
 'make over eye',
 'sada hybrid beauty',
 'salsa rhapsody amber',
 'just miss wonder',
 'blp',
 'la girl keep',
 'flormar eyeshadow palette',
 'somethinc the marionette',
 'wardah eyexpert eyeshadow',
 'make over trivia',
 'thebalm male order',
 'jacquelle eyeshadow pigmented',
 'maybelline tone on',
 'muge leen eyeshadow',
 'thebalm voyage',
 'eyeshadow pencil 2',
 'flame eyeshadow glitter',
 'pixy 3 shades',
 'maybelline the nudes',
 '[dapat 3 pcs]',
 'amara magical heart',
 'esqa goddess eyeshadow',
 'focallure tropical vacation',
 'urban decay naked',
 'tarte tartelette in',
 'saniye exclusive live',
 'eyeshadow 3 warna',
 'viva eye shadow',
 'viva queen eye',
 'viva queen perfect',
 'salsa galaxy eyeshadow',
 'ohsome',
 'esqa goddess eyeshadow',
 'dazzle me the',
 'focallure shimmer eyeshadow',
 'chocolate glitter eyeshadow',
 'eyeshadow pensil double',
 'gietin pro eyeshadow',
 'thebalm male order',
 'la colors beauty',
 'focallure 18 colors',
 'saniye 9 warna',
 'make over trivia',
 'maybelline the blushed',
 'eyeshadow huda beauty',
 'viva eyeshadow cream',
 'eyeshadow 2tone stick',
 'hanasui eyemazing eye',
 'fanbo love letter',
 'eyeshadow rainbow colors',
 'dazzle me the',
 'povstoreid | just',
 'mac art library',
 'mac connect in',
 'latulipe eye shadow',
 'canmake plumpuku coordinate',
 'lacikosme viva eyeshadow',
 'make over paket',
 'implora day to',
 'romand better than',
 'kebaya panjang kebaya',
 'kebaya slendang motif',
 'kebaya slendang//kebaya pengantin',
 'kebaya panjang kebaya',
 'kebaya wisuda kebaya',
 'kebaya polos by',
 'kebaya penyanyi kebaya',
 'kebaya rempel tulle',
 'kebaya jawa kebaya',
 'kebaya bali kebaya',
 'kebaya jadi bordir',
 'baju kebaya bali',
 'kebaya bordir bintang',
 'kebaya paskah /',
 'kebaya encim putih',
 'kebaya panjang putih',
 'kebaya modern jadi',
 'ada bigsize kebaya',
 'kebaya kutubaru tille',
 'kebaya bunga katun',
 'kebaya kutubaru bludru',
 'kebaya kutubaru polos',
 'setelan kebaya modern',
 'parling laris! kebaya',
 'terbaru kebaya kutu',
 'outfit kebaya encim',
 'setelan kebaya tunik',
 'kebaya modern tunik',
 'kebaya wanita modern',
 'set kebaya janggan',
 'baju kurung melayu',
 'promo! kebaya bali',
 'hadju tunik brukat',
 '2024',
 'rok lilit batik',
 'stelan kebaya melisa',
 'kebaya akita brokat',
 'dy kebaya promo',
 'rok lilit batik',
 'set kebaya blouse',
 'setelan kebaya marsya',
 'atasan kebaya brokat',
 'terlaris kebaya brokat',
 'kebaya bali brokat',
 'nusa kebaya setelan',
 'radia fashion kebaya',
 'dalilah lengan pendek',
 'nusa kebaya atasan',
 'ready kebaya model',
 'nona rara',
 'kebaya sita',
 'tebus murah kebaya',
 'satu set kebaya',
 'baju kebaya anak',
 'atasan kebaya encim',
 'kebaya payet lamaran',
 'kebaya anak perempuan',
 'kebaya jadi /',
 '[new arrival]atasan kebaya',
 'kebaya brukat sella',
 'surau kebaya',
 'pusat kebayaku set',
 'blouse kebaya brokat',
 'kebaya bordir bintang',
 'kebaya wisuda kelulusan',
 'stelan kebaya aurora/kebaya',
 'kebaya kutubaru polos',
 'kebaya bunga katun',
 'adrie basuki |',
 'sulina style',
 'nona rara',
 'nona rara',
 'nona rara',
 '[exclusive launch] nona',
 'nona rara',
 'nona rara',
 'kebaya puan wiji',
 'kebaya santai wiji',
 'kebaya panjang "untaian',
 'kebaya pendek daur',
 'kebaya encim tumbuh',
 'kebaya stelan slendang',
 'dress duyung akasha',
 'kebaya setelan seroza',
 'kebaya pengantin ekslusif',
 'nona rara',
 'nona rara',
 'nona rara',
 'nona rara',
 'nona rara',
 'nona rara',
 'nona rara',
 'nona rara',
 'nona rara',
 'margaria batik',
 'original bronik tunik',
 'kebaya modern brukat',
 'setelan kebaya kutubaru',
 'kebaya jumbo ld',
 'kebaya kutubaru bludru',
 'kebaya bali viral',
 'nusa kebaya kebaya',
 'kebaya original//kebaya modern//gamis',
 '{zona kebaya} stelan',
 'aini kebaya batik',
 'kebaya kutubaru kekinian',
 'blus kutubaru motif',
 'odzaclassic odza set',
 'batik kebaya kutubaru',
 'kebaya original rdz',
 'toyota avanza program',
 'new honda brio',
 'booking fee untuk',
 'new toyota avanza',
 'new honda brio',
 'honda brio satya',
 'mainan binatang roda',
 'mainan mobil mobilan',
 'yoli toys mainan',
 'hotwheels murah grosir',
 'mainan anak mobil',
 'hotwheels murah loose',
 'laki mobil mobilan',
 'mainan mobil mobilan',
 'mainan mobil mobilan',
 'mainan anak mobil',
 '【gstar】( bisa cod',
 'mainan anak mobil',
 'wpl d12 suzuki',
 'mobilan polisi ride',
 'welly jeep wrangler',
 'oli mesin',
 'wanted gta bintang',
 'hot wheels track',
 'mainan mobil hotwheels',
 'aki accu lithium',
 'alas dasbor cover',
 'wuling air ev',
 'honda brio satya',
 'hyundai ioniq 5',
 'sakura cabin filter',
 'wuling air ev',
 'toyota raize 1.0t',

In [23]:
df_names = pd.read_csv(names_dir)
df_names.head()

,Unnamed: 0,NAMA,Count,Kategori,Jumlah Suku Kata,jumlah kata,Jumlah Huruf Vokal,Jumlah Huruf Konsonan,Jumlah Huruf
0,0,ANJAR SUROTO,1,Pribadi,5,2,5,6,11
1,1,REINHARD RUDIYANTO SIHITE,1,Pribadi,9,3,10,13,23
2,2,ABD RAHIM NANI,1,Pribadi,5,3,5,7,12
3,3,DRS MUSTAPHA AFIFF,1,Pribadi,5,3,5,11,16
4,4,FAIZ FIRDAUS,1,Pribadi,3,2,5,6,11

In [24]:
raw_names = df_names['NAMA']
raw_names.head()

0                 ANJAR SUROTO
1    REINHARD RUDIYANTO SIHITE
2               ABD RAHIM NANI
3           DRS MUSTAPHA AFIFF
4                 FAIZ FIRDAUS
Name: NAMA, dtype: str

In [25]:
raw_names.tolist()

['ANJAR SUROTO',
 'REINHARD RUDIYANTO SIHITE',
 'ABD RAHIM NANI',
 'DRS MUSTAPHA AFIFF',
 'FAIZ FIRDAUS',
 'RIKI YULISMAN',
 'JUNARIO HP SRG. A',
 'M.ROBBY',
 'MIRHAN',
 'J.PARDEDE IV',
 'SUKARTINAH',
 'ELI SONALIA',
 'MOCH SODIKIN',
 'I KETUT WARDIANA',
 'TRINDO JUNAEDI',
 'ARI FATIMAH',
 'I DEWA GEDE WISASTA',
 'HUSAIN JAYA',
 'AHMAD SYAEFULLOH',
 'MUHAMAD KHOLIL',
 'ROCHADI C',
 'HARTON SE',
 'DANI FIQIH 06',
 'KAMRIL',
 'EKO NOVAN SAPUTRO(CUCIAN)',
 'SAMSUDIN. A',
 'SUKLI',
 'NURLELI SAGITA',
 'CHANDRA WINARSIH',
 'NI WAYAN SUDARIATI',
 'M.ZAIDI',
 'RIWOTO',
 'MIYAR / NIYAR',
 'AL HOERIAH',
 'DRS SUBAHI IDRIS MM',
 'HENDRA JAYA 02',
 'LIE ANDY KUSMANTO',
 'PETRUS APRIANTO 01',
 'HASANUDDIN S',
 'HUZEIN NOOR',
 'NURBIYANTONI',
 'DIDIET RADITYO',
 'SITI SUWARTIK',
 'ANDRE YULIUS TJAHYA S',
 'ADE MULYANI',
 'SALMAN PARSI',
 'ARI MINDAYANI',
 'LA HANUGA',
 'H. NASRUDDIN',
 'SITI HANDRIANI',
 'IIN ABDUL SALEH',
 'DAVY LENSOEN TJOMAN',
 'SETYA NINGRUM',
 'INFAN ANNUR NAGA',
 'WIBAWA SAPUTRA',
 'ZAINUDDIN HUSIN',
 'NICO SECIO',
 'INTAN MUTHIA',
 'AMIN THOHARI',
 'ELLIANIS 3',
 'KEVIN JOSUA SIRAIT',
 'YUSTINA SURATINI',
 'NI WAYAN PUSPINI',
 'HARDY WIRAWAN RUTON',
 'DAVID HENDRI LIEM',
 'NI KADEK PUTRI INTARI',
 'TEDY SUBIYARSONO U/APOTIK',
 'H M SUBANDI',
 'PAWIT ALFADI',
 'SUROYONO',
 'WAHYUDI A',
 'J KUSNADI',
 'SUTJIPTO 2',
 'AMRI GUSMAN',
 'MOHD PUJI ALFAED 10',
 'DESAK MADE ASRI YUNI',
 'SAIFUL BAHRI/NAGA',
 'INDRA NUR ASRAFFI',
 'UNU HIDAYAT',
 'DEDE JUANDA',
 'ERLINA,SH',
 'LAWIDIN',
 'MARIE ABDULLAH',
 'S U M A',
 'YOPPIE BUDIONO',
 'SATIYAH 2',
 'KHALIMI',
 'GITO YEKTINI',
 'TENRI VADA EDA',
 'WAHYUDIN BIN H UCIN',
 'EKO PRIYO',
 'BAYU REDA ALDIO PURNOMO',
 'A H U I',
 'MARTANTO SULISTIO',
 'NURDIN ADAM',
 'CUT NURAIDA',
 'JUMSIH',
 'TUTIK ALFIYAH',
 'HARI RISDIYANTO',
 'SARIYEM/BLOK E',
 'NOVIYATUL QIFTISAROH',
 'MUHAMMAD NAUFAL A.A',
 'WIDYA WULANDARI',
 'HERY GUNAWAN (2)',
 'DIYAH SETYANINGRUM',
 'TRI ISMAN ROHADI',
 'M SAHWA',
 'SONNI SUSANTO',
 'NUNUNG NURHALIMAH',
 'H KASMI',
 'I GEDE ARJANA',
 'IIN SOLINAR',
 'ANNA PRIHARTATI',
 'RAMLI YS',
 'HNS GINTING',
 'RAHADIAN RACHMAN',
 'YETI HANDAYANI',
 'IDA FITRIA NINGSIH',
 'YUDIANTO B. ANDRIAWAN',
 'ROSLENA',
 "HJ DUHAETI BT MA'RUP /TOK",
 'NURHAYAT',
 'THONG LENA',
 'HJ.NUROHMAH',
 'DIDIK MUFRIANTO/A',
 'RENI NURAENI (KEBIDANAN)',
 'HERMAN SETIA BUDI. B',
 'HJ. SITI JULAEHA 3',
 'YUSUF WARDOYO',
 'TJONG DJOEN KHOEI',
 'ISWAN LASIKI',
 'INDAH FIRDASARI',
 'MOHAMAD MUHOLIB',
 'YAKIMAN',
 'CHRIS CHANDRA (B)',
 'SEPTIONO INDRASARI SAPUTR',
 'LAIMAN MARGONO',
 'SUHERMAN U/USAHA UDANG',
 'ASMIYANI',
 'JENAL ARIFIN (REST AREA)',
 'H. M WAWAN PRIYANTO',
 'PUPUT RIANA',
 'TJOE KHE BENG',
 'LILY GUNAWAN',
 'PAMSIMAS PANJI TIRTA',
 'CHANDRA SIBARANI II',
 'SUSY ANDAYANI',
 'AGUNAWAN HADI SUSANTO',
 'MUHAMMAD NUR 04',
 'ARDI SUBADRA',
 'HERRY V',
 'M. DANANG ERIAN KOI',
 'LONG BENG LONG',
 'RATIM (AYAM POTONG)',
 'HENDRIK JAYA. S',
 'MAHMANI',
 'RY SUYOTO',
 'NEVY RAHMI NURJANA',
 'H.PAHRUDDIN',
 'NURLIS M.NUR',
 'DESTRO/JOHAN NURKOLIS',
 'AHMAD BAGIR',
 'HJ CICI MUNTASIROH',
 'ARJA',
 'SAHALA.M.LBN.TOBING',
 'ABSAR',
 'EVAN SUTIONO',
 'KUSNIAH',
 'M RIDWANULLOH',
 'IRA SINTAWATI',
 'GRAFIALDI FAKS RIZZA',
 'H. MUYOTO',
 'ISMAIL MARZUQI',
 'IR H AMBO APPE',
 'IVAN MARCO',
 'WAHYU ITA KRISTINA',
 'AHMAD NUROCHMAN',
 'SURASIT',
 'LUKMAN YACUB',
 'I PUTU DARMIKA',
 'H. DAMERI A',
 'DADAN ALI SADIKIN',
 'YOGI YUSWANDI',
 'SUTRA AKMALISA',
 'A.AGUNG SRI SARTIKA SSN',
 'MAR JOHAN',
 'MAMAY SUMINAR',
 'RENALDO TAMBUNAN',
 'ITIN JUBAEDAH RINATA',
 'SELAH AL JUHRI',
 'SAMSUDI LUMBAN BATU',
 'ACHMAD MUCHTAROM',
 'SILVANA LENGGOGENI',
 'RUHIMAT',
 'JONI CAHYOKO 4',
 'ANISATUL WAHYUNI',
 'YANTI AFRIANI',
 'ROPIKA AULIA',
 'ELLY KARTIKA SARI',
 'LIRA DIAN NOFITA 4',
 'GEDE DANA',
 'DESI IRMAYANI',
 'VERONIKA ATIK ANDARWATI',
 'SUNOTO NAGA',
 'HENGKY SIAKIMAN ALI',
 'JAJANG SUPARMAN 2',
 'NUR FUAD HASAN',
 'NY IDAH MUNGSIDAH',
 'HENDRA DINATA/T.BUKU',
 'SUAIB GENI',
 'BUDI BRAMANTYO',
 'JONNER SIBUEA',
 'R. SYAMSUDIRMAN 3',
 'BUDIDAYA ABD KODIR',
 'IRWAN WAHYU ARYANTO',
 'ZULFAZLI',
 'CHANDRA ISKANDAR',
 'NI KETUT MIRAH DWIADI',
 'H. SUTIKMO',
 'ARIE NATANAEL 2',
 'ANGGI TRIYONO/ PECEL LELE',
 'MOCH. ROCHIN ( ABU MOTOR',
 'MIMIN SUKARMIN 2',
 'MICKY LEKATOMPESSY',
 'PENGINAPAN HIDAYAH',
 'ARFIN NUR HENDITYA',
 'TOPAN FRANDITIO',
 'ASAI 1',
 'HERI KUSWARA',
 'AMAT YASIN',
 'ENOK SUMARNI',
 'M. INSYAH',
 'SUKAENI',
 'AGUNG RIANDY',
 'WIYOTO',
 'LISNA DEAHANA',
 'YUSUF ALGAFUR 13',
 'DONNA PURBA',
 'EKA DIAN YULIANTI',
 'IDA BGS MADE SUGIARTA',
 'EPON SUMARTINI',
 'FATMA YULIATI 1',
 'ALBASI PARAHYANGAN',
 'LULUK ANDINI',
 'KATRIN WIDIYANTI',
 'KRIS BUDI HARTANTI',
 'DULWARMAN',
 'DARMAWAN YAHYA SURYA',
 'DINI APRILIYANTINI',
 'ERWAN SAMSIYANTO',
 'FADHLAN SALAMI PUTRA',
 'DWI RUBIYO',
 'HERWIN 10',
 'CING',
 'SUMAUL FIYANI',
 'KUSNUN SARIF',
 'LYSA MAYA SARI (3 )',
 'SRI RETNOWATI L,S.KOM',
 'JESNOS SANDOS',
 'NORIS PRATAMA',
 'H ZUBAIR AL MUDJAHID SH 5',
 'DMT_TSEL_SEL144_AIKMEL2',
 'JAJANG JAELANI',
 'ANJASMARA (A)',
 'LILIK DARYANTO',
 'SALVIDA',
 'YATI SUSANTI',
 'ZAENUDIN CHALMA',
 'IRWAN MBUINGA',
 'NURLELA TAHIR,SP',
 'LASANA',
 'ANI YULIANI',
 'ANGGAR WISNANDARI',
 'AHMAD MUZHOFFAL.SE.MAF.4',
 'CATUR ANDI SUTRISNO',
 'PEK TAW KIE',
 'KEMBAR BROILER',
 'IRIGASI SAWAH ANTON',
 'TIKA MERI VIONA',
 'SIMON WANGDRA',
 'ELYGIA',
 'SITI WARYATI',
 'ADI PUTRA SENTAS PRASETYA',
 'HEULEUR GABAH',
 'NATALY SH',
 'RUHAENI',
 'MELLY YANA SAPUTRI',
 'PRADANARIAN YUFLIK H.',
 'JOKO ISTIYONO',
 'SARDY TANTIONO',
 'HAPRIANSYAH NOOR',
 'TAN TJOEN JOE',
 'IRIGASI SAWAH MUKAIR',
 'ALPIAN NOR M',
 'YANCHE',
 'NURZAJEFRY. SH',
 'HJ SITI AISAH NST',
 'H.NURZAIDI.4',
 'WANDI SUHENDI 3',
 'SYAMSYUDDIN H SYAKUNI',
 'RATNASARI II',
 'NY IDRIS',
 'VENILIA THERESIA',
 'INGIN JAYA',
 'IWAN PITOYO',
 'KADANG AYA RUKIMIN',
 'MUHAMMAD ZUL AFKAR',
 'IWAN REGITO SIREGAR',
 'CHUMAIRI C',
 'DR.H SAAD S NST.SPOG',
 'SARANG WALET SAFRI',
 'M.R FAKHRURROZI',
 'IMAM SANOESI AB',
 'NI KADEK RAI WIRYANINGSIH',
 'ARYANTO DALIH',
 'H ADI JUHADI B',
 'MUZAKIR TUMU',
 'HERMAWAN SETIYONO',
 'ABDULLAH 5',
 'MOH NURCHOLIK',
 'ELVI ZULGANDI',
 'KATIMUN EKO SUSANTO',
 'ANSTHELABEL FASHION',
 'KHABIB YUDI',
 'SYAHRIR DG LILI',
 'ERIK FERDIANSYAH M',
 'I NENGAH DODIT SETIAWAN',
 'ABDUL KHOLIG',
 'ADE OBIANTI 1',
 'MARDALINDA',
 'DRS AMANDUS NAHAS',
 'KUSNADI D',
 'SUYONO NAGA 03',
 'ARIYANTO GOZALY',
 'AA NGR SUENDA',
 'ASMAN LB MARBUN',
 'MUHAMMAD IRSYAD NAJI',
 'SUKIMAN BIN MARSIDIN',
 'IYAN HERYANTO BENGKE',
 'ALWI SETIAWAN A2-8',
 'KUSYANTO HALIM',
 'SURODJO',
 'DILA MEIDAWATI',
 'YANET PRIMA YANI',
 'YASID KHAROMI',
 'AGUS HERI WIDODO B',
 'NRFOOD',
 'ISKANDAR PARIADI',
 'AULIAK',
 'MUHAMAD GHOFARUL IKHSAN',
 'ROSMANIDAR,A MD',
 'RAMP',
 'LO KIUK ME .',
 'DJAROTDJAROTUN',
 "ARBA'IEN",
 'MARDJONI TATSHIR',
 'KAEFIYAH',
 'YOHAN PAMOSANGKA',
 'I NYOMAN GERIAWAN',
 'NUR DIANA AL VIDA',
 'ERNA YUSNITA',
 'NI WAYAN KOMEKAYANTHI',
 'LIS FERADEWI',
 'ZUBEIR ABDAT',
 'A MUKHSIN',
 'ANGGORO LA ANGKA',
 'SAWIN II',
 'OEY DJOEI ING',
 'MOH IHSAN/PERCETAKAN',
 'NI WAYAN SURYATI',
 'NONY YOLANDA/JET PAM',
 'CLAUDIA CITRADEWI',
 'KHABIB MUSTOFA / NAGA',
 'TOYIBUL BANI (A)',
 'KALIMASADA',
 'SUMARNI 01',
 'KANTIN KUA SEPATAN',
 'I KETUT SUDARMA YASA',
 'SITI AISIYAH BT MUNDAKIR',
 'KHOIRI NAGA KOL TGLDLIMO',
 'DAVID TRISNO ST A',
 'FRITS FERI FELLE',
 'IKBAL SAIFUL BAHRI',
 'JOHANURI.E',
 'NGARDAM',
 "YYS DARUL MA'ARIF AL INSA",
 'SELAMAT UDIN',
 'AGUS SUHANDI',
 'FATHAN ACHSAN',
 'J I O',
 'DIDA FARM',
 'JLITENG SUSILO',
 'EKO CHRIS MARTONO',
 'ZACKY SYAHPUTRA',
 'AYU SUNDARI AZIZAH',
 'M.AZMIEN',
 'OEI BING TWAN',
 'H.M MUDIYASIN',
 'ENTI SAPTI 3',
 'ANIP',
 'MUBARIZI ARIFIN 5',
 'ADABI',
 'MOKHAMAD ROSYIDI',
 'MULHAM RAHMAN',
 'H MUSTAJAB AM',
 'EKO DIANTORO 7',
 'ARI JINU PURWANTO4',
 'KHOSIM WIBOWO',
 'WARNAS PUTRA SUNDA',
 'JUNAIDI SETIAWAN',
 'SAEFUL AKHYAR',
 'APIN HERNAWAN',
 'ACHMAD ROFIQI MASHUDIYANT',
 'DONI CARLOS',
 'ALIMUDDIN NASUTION',
 'H JENAB',
 'JIMMI TRAPILO',
 'SAUD MUHAMMAD AL SAHRI',
 'FALTA YUPITA SARI',
 'KRT CHRISNA ATMADJI',
 'NY YUNIDAR',
 'RUSLI AG',
 'NI NENGAH GATRI',
 'LAJUARDI',
 'MARINI 1',
 'LAZUARDI MUHARAM SETIAWAN',
 'JUNIH BIN SOAN',
 'EVA ULLY MARISKA',
 'PUTU EKA KRISNA',
 'ADITYA SRI ADRIAN',
 'DIAN DARMANTO',
 'SAHILAL ARIMI',
 'TRI BUDI CAHAYA',
 'RIFKI PERMANA 2',
 'WALYAMAH',
 'ALI KHOIRUL KHUBIBAH',
 'LESEHAN RIZKI PUTRA',
 'ZAMHUR ZAMZAMI',
 "ROBI'ATU SHOLIHAH 2",
 'SANGGAR TANI',
 'SADAR RIYANTO',
 'WONG PAN TJIAUW',
 'M. SADIKUN',
 'VICKY SANJAYA',
 'YENNY RUSTAM',
 'MURLIANA A - TAJJALI',
 'MUNZIR SAPUTRA',
 'M SOLEH MA',
 'SATRIO AJI NUGROHO',
 'NITA REHANI',
 'ROSYANA (U/MEUBEUL KUSEN)',
 'RAMPEANI RACHMAN',
 'NAIMUN',
 'AGIT ASBIYANTO',
 'SEPNIWATI',
 'HENGKY TJONG',
 'YUNITAWATI',
 'AHMAD THAHA',
 'MENG KHIANG',
 'SIDUHU ZEGA',
 'DALPEREF 2',
 'I KADEK RICKY SUJANA',
 'DWI PUTRI ARSIH K SH 1',
 'RATINGIN',
 'MARIANIE 3',
 'FIPIN ANDRIAS',
 'SIWI ASTUTI',
 'TJOENG LENG TJUI',
 'I GUSTI KETUT MUSTIKA',
 'IRSAN PARLAUNGAN',
 'ACHMAD MAEMUN',
 'ROCKY JEFF MAICHEL SAUPAL',
 'ERIKA NURFATMAWATI',
 'SIYAMA',
 'HERLIKA ( 1 )',
 'I NYOMAN ARIADI',
 'H S ADANG',
 'MADARI',
 'SANIN H.SANIP SOLO',
 'AKHMAD ALBAR',
 'DEDDY ROYADI BAC',
 'BADERUDDIN, S. SOS., MM',
 'SULAIMAN ABAS',
 'AGUSSTIN OEMAR I',
 'ASEP SUWANDI',
 'AHMAD PATAAN',
 'SYEKH NUR AWALUDIN',
 'MUHAMMAD JAWAD. (A)',
 'HAFIS ZUCHRODI',
 'PAIMAN SAPTO RAHARJO C',
 'YUDIS PERMANA',
 'BISMI HAYATI',
 'EFENDI SUSANTO',
 'PAM KKM KEDAK MAKMUR',
 'PATOLIK',
 'WAHYU ARIWIBOWO',
 'AMRUL MUKMININ/SABLON',
 'DEWIYANTO',
 'MUNDARI HASAN',
 'KODIRUL ANAM',
 'M. Z. ABIDIN/MZSTIKER',
 'AHMAD ITSNADI',
 'MOHAMAD ADI MULYONO',
 'ANGGI NURJAYANTI',
 'I KADEK KRISNA',
 'YANA SOPYANA',
 'ACHMAD KOSASSIH',
 'ROKHMAH U/PENJAHIT',
 'MOH.FEBIE PRIMA',
 'RIZAL FAHMI',
 'DRS. AHMAD TURMUDZI',
 'AMRI JAMALUDIN',
 'DRS. N. WAMBRAUW',
 'TONI MALAU',
 'ABU HAMID MASKUR RIDWAN',
 'SURONO BUET SERVASIUS 2',
 'DEDRINALDI',
 'BINTANG SUPRIYANTO',
 'SYARIF HIDAYAT IBNU JAUZI',
 'CICI IKA SRI RAHAYU',
 'SAHRIJAL',
 'MARIOS PURWADI',
 'PURWANTA INDRABAKTI',
 'ADE HARDETO',
 'DENAL',
 'TJOE HAI YEN',
 'MARCEL LAY',
 'DWI NUR HAYATI',
 'JAJANG MUHTADIN',
 'ERVIN SABAR SIANTURI',
 'BUDI EKO SETIAWAN',
 'SEPTIAN HADIONO',
 'YUNIADI EKA PRATAMA 1',
 'FETRI YENI',
 'AMIRIN',
 'I KT MANIK A PRIANTARA Y',
 'REFRIZAL',
 'NI MADE KONTASIH B',
 'PENGASAPAN IKAN SUMIATI',
 'CARTAM WIRTADIJAYA',
 'RESERVOIR MOTORIZED VALVE',
 'UTA BIN PIONG',
 'JONI SOLFRUS NENO',
 'H.R HARDJA DIDJAJA 2',
 'PONIJAN KASIYONO',
 'PAMSIMAS SARIMULYO',
 'MUHAMMAT ATHARI / BEDAK',
 'TNK KA KHAMIMAH',
 'NI KETUT WISMAYANTI',
 'DWI NINGSIH',
 'JOEKI ANNA',
 'AKHMAD.E',
 'GANDHIES DYAH PITALOKA /',
 'M ILHAM FACHRUDIN',
 'SLAMET WURYADI',
 'ILHAM S LUBIS',
 'JAUW WALUDIN IWAN',
 'MISNO RUDI',
 'AGUS KURNIAWAN, ST',
 'MUDIARTA,I NYOMAN',
 'ESTER MATANA',
 'IMAM TAUFIK.ST',
 'ROMADONA',
 'BETSY ERIA SULASTRI',
 'SANTOSO JOHAN ( A )',
 'EDI KUNTADI',
 'CANDRA WIJAYA',
 'ALDONI HASAN',
 'APRIYONAL',
 'MUHAMMAD IFTIKAAR PASHA',
 'PNPM MANDIRI SULISWANTO',
 'RAMA TAUFIK RAMADHAN',
 'DASLIM TAMBUNAN',
 'AGR SMSWH MUHAMMAD WIDODO',
 'KHO SIE KING',
 'HJ. DIANA DARMAWANTI',
 'SERI AGUSTINA MELINDA -1',
 'ARIF RUSTIAWAN NAGA',
 'DWI RANGGA SEPTIANA FAJAR',
 'H ARIF HIDAYAT',
 'H.T KARIMUDDIN',
 'JONI OFRYA',
 'ANDRUTAMA ALS ANDREW H',
 'HERI DIAN PERMANA',
 'FERA SEPTI RAHAYU 1',
 'ENDANG JATMIYATI',
 'RENDI U/KONVENSI',
 'PRANOTO LATIF',
 'I KETUT WARTA',
 'PEMBENIHAN PANGAN',
 'ANDHI HERWANTO.S.SOS',
 'ELIA AFRIANI,SE',
 'FEBRI SUBIYANTO',
 'DEBORA DEISY',
 'TIRTA BALAWARA',
 'H.AGUS SUPARMIN',
 'T SAFWAN A',
 'ELLY SUGIANTO',
 'ADI KURDI',
 'ANGELIA TANTRA',
 'SAFTA HADI',
 'APRIRIANTI',
 'MARIA MARITA KEWA',
 'DENNY SETYAWAN',
 'IBRAHIM ST MUDO',
 'FARIZ ANGGA OKTAVIAN, SH',
 'IMAM SOEROSO',
 'AN. AIDA KARTIKA SANTI',
 'FLORENSIUS ROSENO',
 'NURZADIAN',
 'WIDI HARSONO B',
 'SIAUW WIE KONG',
 'PETRUS MUSTAMU',
 'NENENG (B)',
 'MISBAH IBRAHIM',
 'SUKASAH',
 'DL SITORUS (KANTIN A',
 'YOGGIE GM',
 'RUDIAN',
 'CUT WARDATI',
 'SOFYAN S SKMMPM',
 'KOMANG SUDIANTA',
 'I WAYAN VIVI OVITA',
 'AGR SMR SAWAH YUSUF HARIS',
 'LAI BUI MIN(A)',
 'KHAIRUL ANWAR',
 'RUMADJA LUSUH',
 'DYBYO HARTONO',
 'DEDI SUNARNO',
 'ANFAL AULIYA',
 'AHMAD SAHUDI',
 'NAYI NI WAYAN',
 'T.M. DAUD AR',
 'HERU RYANTARA',
 'NI PUTU SUMETRI',
 'ONG TJHING HONG',
 'ROHMAN BASUKI',
 'PUTU GEDE WIARTHA',
 'ANOM SUJITO',
 'DWI ALDI SUKMA',
 'AGUNG WIERYANTO THEDY',
 'DEWI MURTIANI',
 'GILANG RAHADIAN M.A',
 'ANGKY PATTY',
 'DIKI PRANATA',
 'ELY DESWITA ANIS',
 'M A D I O N O',
 'JAITI',
 'YULIA ANDRIANI',
 'IRWAN ESEKTRA',
 'WAWAN AYAM',
 'RAFI DIFA ALMAS 1',
 'TRI MAYA ARINI',
 'NANI AGUSTINI',
 'HONNA',
 'NETTY NURHAYATI SIAHAAN',
 'NI MADE PUSPITAYANTI',
 'RONNY LIM',
 'THORIQ AHMAD FAUZAN',
 'YANI A44',
 'GAUNG ADAKA',
 'ERIK ISAKANDAR',
 'RUSLAN BN-9',
 'SITI SHARAH',
 'QARLINAH',
 'MUHAMMAD GIBRAN PALUPI (H',
 'NOPENDI YUPITER',
 'DIDIK SETIAWAN NAGA',
 'H SONHAJI',
 'DARMITA',
 'TUTIK LESTARI AND. KEB',
 'SLAMET AGUS SURYANI',
 'M.FAHRUDIN NOOR',
 'ELYUSRITA',
 'SANECI',
 'ACHAMD',
 'M ZULYADAINI',
 'HJ.YENI.M.SE 2',
 'IYAH, A',
 'ADI JHON',
 'TAN GIE IEN',
 'ERNAWATI.II',
 'DARTO WAHAB',
 'OTONG SYAMSUDIN',
 'JUMAIDAH',
 'ANI YATI MENARA TELOR',
 'I WAYAN LIDUG',
 'ANDI ILHAM',
 'ASMAL JUNUN',
 'SUKRI KACCA',
 'NURLELAWATI',
 'SYAEFUL ANHAR',
 'JANAR',
 'I SAFIA',
 'LUKITO SANTOSO',
 'AAM BADRUTTAMAM',
 'A HERI PURWANTO',
 'SUDIN SIBURIAN',
 'SUDIRMAN H - 2',
 'BOBBY ESA PUTRA C',
 'ENDANG DAMANHURI',
 'SITI ZUMAROTUL CHOIROH',
 'WARNET AGUS RUSMAN',
 'POMPANISASI ANSAR BASIR',
 'NENENG KUSMIATI',
 'KPU KAB. ALOR',
 'PARAHDIBA.SH',
 'AGUS RIYONO NAGA',
 'NUR IMAN,S.KOM',
 'BIDAN ERNA SUSILAWATI',
 'SUMRIYAH. I.',
 'LAW TIANG HWAT',
 'I NENGAH PARNA',
 'SUN SUMANTO',
 'H PIPIH LUTFI SPBU',
 'LAS JWS',
 'JUNAYYAH',
 'AZKIA KARET',
 'RIZMAR NAZIR',
 'JOKO WASITO.A',
 'HA DJAN NI',
 'JAMRONI / NAGA',
 'MHD.BAWA',
 'SATRIANTOS',
 'ERWAN KURNIA',
 'TASBEHUL HOER',
 'SOEPARNO,DRS',
 'MERI ELIZARNI',
 'NUR RABAIYAH',
 'RIKA YUHANA 1',
 'MASDIA II',
 'ASROPIK',
 'DRS IDA BAGUS KARYAWAN',
 'ULFAH MASPUPAH',
 'ANSOR GUNARTO',
 'MUHAMMAD ALMUHDAR',
 'MUHAMAD SLAMET MASNA',
 'IDA ATIMI',
 'ARSAD WATIA',
 'HENDRA SUNJAYA',
 'HENDRA DASLAN',
 'H NUR SOLEH',
 'PEDE CELULER',
 'DISTRIATI PAZRIAH',
 'SITI ROMLAH - 1',
 'HARMOKO SE',
 'ARIS MUGIARNO',
 'CIBI BABY SPA',
 'I.G.A.A.M. YUNIARI',
 'MAAD',
 'H KHAIRUL KAROHAN A',
 'FARIANTI LADIA',
 'RUDY PRIYANTO',
 'DANIL ABDUL SUKUR',
 'EMBUNF GERENDONG',
 'PALTI M. PASARIBU',
 'PATONAH 1',
 'SAKA MAHARIA',
 'RUDIANTO/EX B',
 'MEMED',
 'IR.HM.ADELAN ABDULLAH',
 'SOLIHATIN',
 'IMA NOR AINI',
 'DYAH NUR LAILY FATHONAH',
 'ATAN',
 'ENJANG SUKMANA',
 'H.ABDUSSAMAD NO.1',
 'DRA. KUSUM RIYATININGRUM',
 'WELLA NOFA SARI',
 'FAKHRUL KHASNI',
 'NURMAINI 2',
 'SURYA PRANDIKA',
 'IRMA BUDI LESTARI',
 'WIWIN NURYANTIH',
 'ISNUARI',
 'PAULA CANSIA UNTU 1',
 'YUZAB ANDESTA',
 'ANANG DWI WIJANARKO',
 'ASBOLAH/NAGA',
 'AGUS SUSANTO (HOTEL KADIP',
 'SIE KIM HENG. 2',
 'IBU IKA',
 'I PUTU BAYU EKA YANA',
 'NANIK JATMIKO FITRIANI',
 'ARIF VALDI SULFIANSYAH 3',
 'SUTO',
 'SUMERTA I WAYAN',
 'LOLI PIANDA',
 'ASEP FADILAH',
 'YUSUP SLAMET',
 'M.NASRULLOH',
 'ARIES DWANTORO SETYANTO',
 'TRIDES HARIYANTO',
 'MUHAMMAD NUR FATHONI',
 'IRWAN HADIANSYAH',
 'HJ. SITI SOFIAH/ TK ROTI',
 'ANTON PANDOWO',
 'DRS.T.TURNIP',
 'AMELIA BUBUT AYAM',
 'DELLY NOVIANTO N',
 'H.M.YAHYA HS',
 'YUZAB ANDESTA 1',
 'I MADE SASIH',
 'FIKI ZAKIYAH',
 'YUMADI. 2',
 'DINA WAHYU',
 'I MADE PANGGIH',
 'SUSANTY EDY LEO',
 'VIVIN YULIANA',
 'HERDINAL. 6',
 'B A I N A R',
 'GATUT SETYO WAHYUDI',
 'HJ NURSA ADAH',
 'NUR HARYANTO U KDG AYAM',
 'TOSERBA R',
 'DEDE YASIR PUTRA',
 'NILAWATI ROGAYEH, SE',
 'LUMBUBARATDMT',
 'FABIANUS NYOSAPUTRA S.2',
 'LINGGO LAKSITO',
 'EUIS SITI ROCHYAWATI',
 'RIZA ANDRAYANI',
 'DRS.EDWARD IBRAHIM',
 'RIDHO SYAHPUTRA',
 'SANDY TANDI TAPPI',
 'KHOIRUL FAHMI',
 "KHOIRUL ANNAS MA'RUF",
 'H.JAJANG SUKIAHA S.SOS 3',
 'REKA T/KERAJINAN BATU',
 'MOH. ADI',
 'LIM I LAM',
 'ASLAN SETIAWAN C08',
 'KOL R HERFIEN MS',
 'ACHMAD U/PAVLING',
 'H AHMAD PARKAN. 2',
 'IR JOHN RIZAL PURBA',
 "ADE SAFE'I",
 'KK ANEKA',
 'FITRIANI EKA DIANA SARI',
 'ARBIAH',
 'IR WIDYA PURNAMA MM',
 'PURNOMO UDMIKRO/TKSEMBAKO',
 'BACHTIAR BUSRO',
 'DAMIH MARDIANI',
 'ASLAH',
 'BERNADUS MAUBEI WATOKOLAH',
 'SITI RUKAYAH(GDG WALET)',
 'MULYADI 4',
 'H.ZULKARNAINI.S. II',
 'DYOUNGS',
 'MUSA KHOIRIYAH',
 'H.HANAFIAH 2',
 'IIS AZ ZAHRA U USAHA',
 'RESMAN TAMBA',
 'SYUPRIYANTO',
 'LOS SAIK PSR DAERAH',
 'ALNI',
 'DARSIMAH.02',
 'ESAU PARDEDE',
 'AGUS ANGGORO',
 'ALBERT B SIHOMBING',
 'TRISILO ASIH SETYAWAN',
 'MEUBEL ABDUL A',
 'CAHAYA ANUGRAH',
 'SITI DEWI AMINAH',
 'APRIJAL SE',
 'INDRA TAUFIK',
 'SRIONO',
 'ERWINSA',
 'CUA CIN PA',
 'SUSMELI',
 'TUADI',
 'ZAENAL MUTTAKIM',
 'RONNY ABADI',
 'KENOD',
 'TOHA, A.MA',
 'ISNINJAR 02',
 'MARHUMA, MS',
 'RUBBY ADHISURIA',
 'I MADE SUERKA',
 'HINSATOPA SIMATUPANG',
 'MAPUL',
 'SUGIHONO SANTOSO USLI',
 'TRI ANTO NUGROHO (1)',
 'YUYUN YUNENGSI',
 'WINARSIH / BEDAK',
 'SANUDIN B H SABIHIS',
 'ARIFIN MULJADI',
 'AMRAN AHMAD',
 'ULLIN',
 'VIVI ELVIOLA.B',
 "NURUL MU'ATIROH /NAGA",
 'ROHIM SIHOTANG',
 'BIMANTORO PURWANTO',
 'HJ. NURLIA',
 'H ASNAWI AB',
 'SURIPTO 4',
 'RISDA ANISATUN WAQIAH',
 'SUSANA W',
 'JHUAN ERLANDO PUTRA RACHM',
 'LINDYA SAMPELAN',
 'DONNA TANUWIDJAJA',
 'MAS RUSDI',
 'KIKI MEGA',
 'SUTIRAH/SUMIATUN',
 'LUKMANA',
 'VONIRAH',
 'RUSADI/JETPUMP',
 'MAR,ATI',
 'NUR KHUDRIN 1',
 'MITHA WINDIA SARI',
 'MUHAMAD MUHTAROM',
 'TEGUH MAKMUR',
 'DR. ARIF RAHMAN HUSEIN',
 'FANDI HARDIYANTO',
 'FAEYZA JAYA',
 'TITI J. GUMULILI',
 'MGS HI ABD ROHIM',
 'BELINA KOHO',
 'JUPRIYANTO PANDIN',
 'DUWI SUDARTO PUTRA',
 'NAJMIE ALJOEFRIE',
 'RISKI IRMAWATI (WR)',
 'ANJANI TEKHNIK',
 'NINIX INDRIANI',
 'KURNIATIE',
 'EGA PALAPA',
 'YOGEN SUGANDA',
 'DARMI MILE',
 'NANANG SHOLAKHUDIN',
 'SHOLIHUL HADI',
 'SITTI ASMAWATI , SE.AK',
 'H.MUAMAR AL QADRI MPD',
 'JALI BIN ARTIH',
 'EVI FEBRIANTI',
 'CUT MERYA AGUSMITA',
 'APERINUS ZAI',
 'FAJARNO NESARIS ( B)',
 'MANISO.A',
 'ILIARDI SALOMO. 01',
 'YONALDI TANDRA',
 'MOHD NASIR NYAKNIE-3',
 'IIP ERIYANI',
 'LUCY PHOA',
 'ISMANTO SENEN',
 'MIKARDENO. S. P.',
 'TARSIYAN BIN WASLI',
 'ALI MAHFUD 9',
 'DR. UDAYANTI',
 'SUPRAPTI (1)',
 'ARIS MUNANDAR SETIO ADJI',
 'HADI HIKMATULLOH',
 'MARYOLINE OCTAVINA',
 'SATYA MUDA SALIM',
 'MUDDASIR ISHAK',
 'SUNYOTO ADI H',
 'SUMIARNI NI MADE',
 'MARIO KELLY WENNO',
 'SUGIANTO P.',
 'OSKANDAR DAVID PAH 01',
 'W.SADIARKA',
 'JAMALUS MORAN',
 'SAIFUL IMAN',
 'MOHAMMAD MUNIR, S.PD',
 'SELA APRILIA',
 'NI KETUT SUATRI',
 'HAYATON 4',
 'WIRYONO BW',
 'SYAHID AFDAL ADINATA',
 'BENYAMIN SUGANDA',
 'SRI MAHARTATI',
 'ALFARINO ANTONIO',
 'RHEZA EDWARD PESIK',
 'SALIM 8',
 'PURWAHENI',
 'DEDE ARIES HIDAYATULLAH/7',
 'SITI KUNDARYATI',
 'HJ. FATIMAH JUHAIRI',
 'JANUARIZAL',
 'HENRIKA SUWARTI SUGIONO',
 'PRAYITNO HADI KARTA SH',
 'PUNAWI ( D )',
 'NUR YULIADI',
 'NY DARINAH',
 'ALI AKBAR BIN ABDULLAH',
 'DENY HARYANTO',
 'MUHAMMAD APRIL HIDAYAT',
 'FERA AGUSTINA, IR',
 'SUROSO EFENDI NAGA 2',
 'KUSWA BUDIONO',
 'APIP ROHILI',
 'SURYA YANUAR 02',
 'YENIK MARLINA',
 'NI LH SEKARNITI',
 'NARYO BIN ARIN',
 'NI NENGAH JANTEN',
 'KLIWON/PEG',
 'FIRQI ZULFAKAR',
 'BARNOTO EFFENDI',
 'SUS PRIYADI',
 ...]

In [26]:
EXTERNAL_NAMES = []

In [27]:
for name in raw_names:
    clean_name = re.sub(r'\b(DRS|DR|IR|HJ|H|ST|SE|SPD|SH)\b', '', name, flags=re.IGNORECASE).strip()

    parts = clean_name.split()
    if parts:
        EXTERNAL_NAMES.append(parts[0].capitalize())

In [28]:
EXTERNAL_NAMES = list(set(EXTERNAL_NAMES))

In [29]:
def process_names(raw_names):
    cleaned_list = []
    forbidden_words = {'warnet', 'stasiun', 'kpu', 'ikn', 'bidan'}
    
    for name in raw_names:
        if not name or not str(name).strip():
            continue
            
        clean_name = re.sub(r'\b[A-Za-z]\.?\s*', '', str(name))
        
        clean_name = clean_name.strip('.,/ ')
        
        if len(clean_name) > 2 and clean_name.lower() not in forbidden_words:
            cleaned_list.append(clean_name.capitalize())
            
    return cleaned_list

In [30]:
EXTERNAL_NAMES = process_names(EXTERNAL_NAMES)

In [31]:
EXTERNAL_NAMES

['Rry',
 'Arsha',
 'Liardi',
 'Afail',
 'Van',
 'Ovianti',
 'Armita',
 'Anin',
 'Unarwati',
 'Omiyardi',
 'Awidin',
 'Sniyati',
 'Uranto',
 'Oviyatul',
 'Sropik',
 'Omeo',
 'Ebri',
 'Asyanto',
 'Anum',
 'Ngelia',
 'Urul',
 'Alti',
 'Urzajefry',
 'Arhuma',
 'Ulisan',
 'Oggie',
 'Rindo',
 'Ernadus',
 'Anche',
 'Uyit',
 'Iza',
 'Riyanto',
 'Ramita',
 'Haisal',
 'Snuari',
 'Istriati',
 'Onna',
 'Ndhi',
 'Iktor',
 'Ulia',
 'Yan',
 'Avid',
 'Iarma',
 'Udy',
 'Ulkifli',
 'Yahid',
 'Atiyah',
 'Rja',
 'Izal',
 'April',
 'Ahmani',
 'Engasapan',
 'Ery',
 'Urono',
 'Ede',
 'Ayaton',
 'Rh..asir',
 'Ries',
 'Idia',
 'Uliana',
 'Umaul',
 'Aryoline',
 'Itriani',
 'Apung',
 'Njar',
 'Adi',
 'Oyibul',
 'Rfan',
 'Ivin',
 'Fkal',
 'Elly',
 'Bdul',
 'Dek',
 'Lvi',
 'Ris',
 'Ahala.bn.obing',
 'Asdulah',
 'Udirman',
 'Eptian',
 'Ogi',
 'Ariz',
 'Unario',
 'Ohman',
 'Avy',
 'Jong',
 'Arto',
 'Lham',
 'Unita',
 'Ilvana',
 'Ryanto',
 'Aslim',
 'Etya',
 'Oli',
 'Llianis',
 'Uthut',
 'Urzaidi.4',
 'Ris',
 'Riono',
 'Ryvawati',
 'Aryoko',
 'Irta',
 'Iftahahul',
 'Anti',
 'Bsar',
 'Ede',
 'Van',
 'Ysa',
 'Radanarian',
 'Rinda',
 'Lni',
 'Amril',
 'Nti',
 'Ofwatunnisa',
 'Ndi',
 'Aefiyah',
 'Adang',
 'Atolik',
 'Eonard',
 'Ulius',
 'Gus',
 'Huan',
 'Etsy',
 'Slah',
 'Ocky',
 'Unih',
 'Aroya',
 'Aria',
 'Iryono',
 'Arinah',
 'Apto',
 'Emala',
 'Ily',
 'Gunawan',
 'Ardjoni',
 'Erian',
 'Usa',
 'Esdawita',
 'Unitawati',
 'Udis',
 'Rnawati.i',
 'Eronika',
 'Andra',
 'Nggi',
 'Urnip',
 'Ulham',
 'Iswo',
 'Haeridah',
 'Ustapha',
 'Erhati',
 'Eng',
 'Aula',
 'Erwin',
 'Emed',
 'Laine',
 'Eri',
 'Ahrijal',
 'Ipin',
 'Asbehul',
 'Minur',
 'Adiarka',
 'Estro/ohan',
 'Ardy',
 'Mbo',
 'Pdial',
 'Esak',
 'Nip',
 'Iki',
 'Ucy',
 'Armidin',
 'Uhammat',
 'Edak',
 'Esfina',
 'Adel',
 'Nggoro',
 'Mirin',
 'Urkon',
 'Anang',
 'Enab',
 'Ike',
 'Ini',
 'Oslena',
 'Uluk',
 'Umriyah',
 'Aulud',
 'Aud',
 'Osmayuni',
 'Nwar',
 'Upriyanto',
 'Anuarizal',
 'Ugihono',
 'Amli',
 'Rigasi',
 'Urandi',
 'Eptiono',
 'Atut',
 'Ajang',
 'Smail',
 'Awit',
 'Lyasni',
 'Yaeful',
 'Yambahari',
 'Odi',
 'Ani',
 'Ibawa',
 'Isna',
 'Abri',
 'Ubby',
 'Iana',
 'Yahrial',
 'Unung',
 'Usdi',
 'Agil',
 'Izal',
 'Artam',
 'Indya',
 'Lamsyah',
 'Joe',
 'Omadona',
 'Endy',
 'Enny',
 'Aeman',
 'Ngin',
 'Humairi',
 'Rna',
 'Hoirul',
 'Ebora',
 'Ukartinah',
 'Njani',
 'Yub',
 'Rfin',
 'Ubair',
 'Heza',
 'Uparyant0',
 'Uwarno',
 'Eri',
 'Jioe',
 'Enod',
 'Edy',
 'Eti',
 'Eng',
 'Oris',
 'Ugianto',
 'Niek',
 'Pri',
 'Sninjar',
 'Odirul',
 'Intang',
 "Obi'tu",
 'Utarman',
 'Olihatin',
 'Ulwarman',
 'Asana',
 'Enri',
 'Irhan',
 'Akhrul',
 'Ukardi',
 'Apren',
 'Uzein',
 'Yarif',
 'Amhur',
 'Iwin',
 'Oto',
 'Ega',
 'Ahtiar',
 'Ukito',
 'Idi',
 'Ryani',
 'Ulkarnaini',
 'Aluyo',
 'Eka',
 'Jong',
 'Ukli',
 'Arini',
 'Ohn',
 'Achtiar',
 'Och',
 'Gus',
 'Agang',
 'Atiah',
 'Ovianto',
 'Ario',
 'Eru',
 'Inix',
 'Enny',
 'Atnasari',
 'Alvida',
 'Utirah/umiatun',
 'Eubel',
 'Obby',
 'Ing',
 'Isno',
 'Umbubaratdmt',
 'Ustam',
 'Ahilal',
 'Onaldi',
 'Edeh',
 'Mah',
 'Rtini',
 'Embar',
 'Sep',
 'Lvison',
 'Ila',
 'Eti',
 'Idho',
 'Amlah',
 'Anti-l',
 'Amsiah',
 'Ndah',
 'Enilia',
 'Asuki',
 'Rpan',
 'Mat',
 'Andy',
 'Asmi',
 'Eorge',
 'Lyusrita',
 'Perinus',
 'Enri',
 'Ica',
 'Ranoto',
 'Tong',
 'Etrus',
 'Ahidin',
 'Usana',
 'Etty',
 'Urohmah',
 'Esehan',
 'Auw',
 'Ngky',
 'Ibi',
 'Ikri',
 'Adhlan',
 'Erdinal',
 'Dabi',
 'Ainuddin',
 'Ursa',
 'Udi',
 'Opika',
 'Npm',
 'Chmad',
 'Jahidin',
 'Iyoto',
 'Itriya',
 'Ochadi',
 'Unayyah',
 'Rvin',
 'Icky',
 'Nang',
 'Ancing',
 'Enik',
 'Zmien',
 'Unawi',
 'Ulpikar',
 'Mandus',
 'Ismi',
 'Ar,ti',
 'Joe',
 'Urliani',
 'Atya',
 'Utik',
 'Arsiah',
 'Arnoto',
 'Ding',
 'Uliak',
 'Icky',
 'Ino',
 'Mron',
 'Ilawati',
 'Uzab',
 'Rie',
 'Yah',
 'Unyoto',
 'Embah',
 'Uzakir',
 'Alison',
 'Iyar',
 'Amsimas',
 'Ajrun',
 'Iki',
 'Uriyatin',
 'Arang',
 'Urasit',
 'Abianus',
 "Am'ni",
 'Udianto',
 'Min',
 'Idik',
 'Aita',
 'Loan',
 'Oh.ebie',
 'Snawi',
 'Embenihan',
 'Urlis',
 'Usnun',
 'Habib',
 'Ihrini',
 'Gung',
 'Ius',
 'Utjipto',
 'Aeful',
 'Irgo',
 'Armili',
 'Antoso',
 'Arahdiba',
 'Urleli',
 'Ahyudi',
 'Lisa',
 'Ong',
 'Youngs',
 'Ita',
 'Ustina',
 'Utiah',
 'Uwi',
 'Itri',
 'Umaidah',
 'Ani',
 'Armoko',
 'Lwi',
 'Prijal',
 'Eni',
 'Oni',
 'Nna',
 'Rif',
 'Andi',
 'Engadayan',
 'Swan',
 'Ana',
 'Unaidi',
 'Aniso',
 'Udidaya',
 'Ajuardi',
 'Anil',
 'Dhimas',
 'Oih',
 'Engky',
 'Icky',
 'Ustriati',
 'Habib',
 'Eri',
 'Afaruddin',
 'Awam',
 'Endrik',
 'Iji',
 'Atimun',
 'Inny',
 'Urniatie',
 'Halimi',
 'Urdin',
 'Aiz',
 'Ulia',
 'Dah',
 'Uhaeti',
 'Ajmie',
 'Awan',
 'Ahadian',
 'Armi',
 'Ardy',
 'Andhies',
 'Anggar',
 'Isa',
 'Osmanidar',
 'Amroni',
 'Ysn',
 'Hristina',
 'Iem',
 'Atim',
 'Usli',
 'Slan',
 'Anudin',
 'Ilik',
 'Ntan',
 'Ukamto',
 'Iyana',
 'Obiah',
 'Wat',
 'Erly',
 'Rans',
 'Uamar',
 'Ntung',
 'Ndrutama',
 'Ika',
 'Ubeir',
 'Ranyono',
 'Unadi',
 'Aenal',
 'Ayi',
 'Rbiah',
 'Oppie',
 'Ustajab',
 'Ster',
 'Isjal',
 'Kbal',
 'Rvina',
 'Hoirol',
 'Iauw',
 'Itono',
 'Atonah',
 'Melia',
 'Okhamad',
 'Osman',
 'Ila',
 'Omang',
 'Oor',
 'Ipih',
 'Rits',
 'Azuardi',
 'Arlius',
 'Ubahi',
 'Aneci',
 'Ukasah',
 'Lbert',
 'Upiyo.m',
 'Hitra',
 'Ktalia',
 'Dam',
 'Uhammad',
 'Anda',
 'Ansur',
 'Bdullah',
 'Ahaya',
 'Utu',
 'Alperef',
 'Eden',
 'Ukiman',
 'Alta',
 'Zkia',
 'Rafika',
 'Limuddin',
 'Iara',
 'Hoiri',
 'Eleman',
 'Iduwan',
 'Aharuddin',
 'Ompanisasi',
 'Jahroni',
 'Yahrir',
 'Alidin',
 'Udiarta',
 'Edy',
 'Eth',
 'Ilis',
 'Usup',
 'Usanty',
 'Oeparno',
 'Urhayat',
 'Onni',
 'Ahidul',
 'Uaib',
 'Oko',
 'Arios',
 'Iyah',
 'Ifai',
 'Anar',
 'Ahesti',
 'Emli',
 'Aroqi',
 'Adek',
 'Hmad',
 'Anet',
 'Ajang',
 'Elik',
 'Kota',
 'Lbasi',
 'Usnadi',
 'Ntong',
 'Idan',
 'Elah',
 'Asenianto',
 'Ediansyah',
 'Ewantoro',
 'Smal',
 'Pon',
 'Rfood',
 'P.aragih',
 'Endra',
 'Uli',
 'Indah',
 'Efda',
 'Pik',
 'Yin',
 'Fsah',
 'Chamd',
 'Llin',
 'Skandar',
 'Aiman',
 'Edy',
 'Holihul',
 'Rum',
 'Honny',
 'Eny',
 'Oly',
 'Idi',
 'Amih',
 'Urwanta',
 'Ani',
 'Rika',
 'Atrio',
 'Airuz',
 'Ari',
 'Oni',
 'Urmaini',
 'Aka',
 'Afawi',
 'Insar',
 'Ulhadri',
 'Skandar',
 'Rsan',
 'Ndang',
 "Rba'en",
 'Lia',
 'Atingin',
 'Aya',
 'Njasmara',
 'Iti',
 'Ici',
 'Wan',
 'Esnos',
 'Endrianto',
 'Idiet',
 'Uniadi',
 'Alyamah',
 'Rwan',
 'Illy',
 'Lamet',
 'Rmunandar',
 'Lorensius',
 'Ida',
 'Asidin',
 'Amto',
 'Artiyah',
 'Aad',
 'Usain',
 'Ahruddin',
 'Onny',
 'Arak',
 'Hiong',
 'Uripto',
 'Adikin',
 'Yaiful',
 'Rwinsa',
 'Aimun',
 'Alib',
 'Yah',
 'Uhimat',
 'Ong',
 'Oirul',
 'Ataly',
 'Usno',
 'Euleur',
 'Udi',
 'Uty',
 'Mri',
 'Aenudin',
 'Tan',
 'Usuf',
 'Ajiman',
 'Usadi/etpump',
 'Enyamin',
 'Udin',
 'Andri',
 'Atih',
 'Hairil',
 'Lpiyah',
 'Ito',
 'Ahya',
 'Rayitno',
 'Anih',
 'Esy',
 'Unoto',
 'Umuh',
 'Onna',
 'Apiluddin',
 'Irda',
 'Athan',
 'Erry',
 'Amp',
 'Asid',
 'Oha',
 'Ukman',
 'Brahim',
 'Joeng',
 'Ulia',
 'Ella',
 'Inarsih',
 'Icky',
 'Eri',
 'Rta',
 'Asanuddin',
 'Lygia',
 'Iti',
 'Arsi',
 'Aung',
 'Gusstin',
 'Itha',
 'Adari',
 'Arton',
 'Fendi',
 'Oyo',
 'Ohim',
 'Ntonius',
 'Irin',
 'Dwina',
 'Gnes',
 'Rdi',
 'Rides',
 'Ian',
 'Enal',
 'Indin',
 'Umerta',
 'Adar',
 'Erry',
 'Imantoro',
 'Urliana',
 'Uherman',
 'Udi',
 'Iduhu',
 'Aderuddin',
 'Bdussamad',
 'Rafialdi',
 'Eha',
 'Oeki',
 'Race',
 'Adan',
 'Oveldi',
 'Ucipto',
 'Lfarino',
 'Andi',
 'Nfan',
 'Arnet',
 'Urlela',
 'Nsthelabel',
 'Ldoni',
 'Akih',
 'Ismar',
 'Lipian',
 'Njang',
 'Rma',
 'Uhaeni',
 'Aenab',
 'Ntah',
 'Elamat',
 'Ully',
 'Urnomo',
 'Armawan',
 'Isra',
 'Alman',
 'Nton',
 'Nom',
 'Ahrudin',
 'Osyana',
 'Iyama',
 'Einhard',
 'Och',
 'Ebri',
 'Umarni',
 'Iwoto',
 'Atur',
 'Nisatul',
 'Lfah',
 'Amryanto',
 'Urna',
 'Unzir',
 'Arsiyan',
 'Mam',
 'Opendi',
 'Lly',
 'Jang',
 'Edrinaldi',
 'Esi',
 'Aeyza',
 'Ardaliza',
 'Onal',
 'Ewa',
 'Alim',
 'Ohd',
 'Asbullah',
 'Arianie',
 'Ifki',
 'Inggo',
 'Handra',
 'Lisabeth',
 'Uswa',
 'Ohan',
 'Arnas',
 'Ukaeni',
 'Eguh',
 'Ain',
 'M.delan',
 'Apul',
 'Amay',
 'Arsimah.02',
 'Anafiah',
 'Atminah',
 'Usmeli',
 'Usyanto',
 'Ichael',
 'Uril',
 'Iski',
 'Usup',
 'Uanli',
 'Yekh',
 'Arcel',
 'Ina',
 'Juhri',
 'Ajarno',
 'Nggar',
 'Mirah/ariman',
 'Hilip',
 'Uis',
 'Uprapti',
 'Nok',
 'Laudia',
 'Arbara',
 'Asdia',
 'Omi',
 'Ulkarnain',
 'Imping',
 'Lpian',
 'Ing',
 'Idya',
 'Athifatul',
 'Iki',
 'Sau',
 'Endri',
 'Sai',
 'Alid',
 'Ewi',
 'Ardalinda',
 'Amin',
 'Bdillah',
 'Elly',
 'Enaldo',
 'Mbunf',
 'Iwi',
 'Ali',
 'Igit',
 'Hd.awa',
 'Endi',
 'Erry',
 'Ercetakan',
 'Umiarni',
 'Akiman',
 'Onner',
 'Mt_tsel_sel144_aikmel2',
 'Epniwati',
 'Ikolaus',
 'Ivi',
 'Udaryanti',
 'Aryo',
 'Ulfazli',
 'Smanto',
 'Asir',
 'Ojali',
 'Adang',
 'Asdjuri',
 'Liwon/eg',
 'Ong',
 'Enal',
 'Eservoir',
 'Fri',
 'Lyas',
 'Isbah',
 'Usniah',
 'Aidi',
 'Awin',
 'Eneng',
 'Onhaji',
 'Arsim',
 'Gusti',
 'Undar',
 'Aiti',
 'Apriansyah',
 'Arwin',
 'Pendra',
 'Evy',
 'Rwandi.,g',
 'Afis',
 'Ilang',
 'Eetje',
 'Spul',
 'Tasiun',
 'Arianti',
 'Undari',
 'Uadi',
 'Ukmana',
 'Ofyan',
 'Usak',
 'Ahyu',
 'Ico',
 'Ambang',
 'Yamsyuddin',
 'Rik',
 'Isda',
 'Ahyudin',
 'Afi',
 'Ukri',
 'Erlika',
 'Ani',
 'Etra',
 'Onirah',
 'Ede',
 'Git',
 'Edi',
 'Hang',
 'Ilvia',
 'Ino',
 'Opan',
 'Itti',
 'Jatilaksono',
 'Uto',
 'Esman',
 'Nfal',
 'Ddy',
 'Ermawan',
 'Bie',
 'Anik',
 'Insatopa',
 'Udian',
 'Ndra',
 'Umadi',
 'Ika',
 'Arcim',
 'Milatus',
 'Ampeani',
 'Elina',
 'Mrul',
 'Rwidah',
 'Amdani',
 'Liteng',
 'Artanto',
 'Uroso',
 'Ismanita',
 'Ira',
 'Pin',
 'Ohammad',
 'Rwan',
 'Hairul',
 'Irta',
 'Eilina',
 'Rthur',
 'Etty',
 'Arlinah',
 'Imon',
 'Uslan',
 'Ybyo',
 'Nthonius',
 'Jarotdjarotun',
 'Ilmi',
 'Khmad',
 'Atriantos',
 'Elyn',
 'Lun',
 'Arl',
 'Mran',
 'Urhadita',
 'Ona',
 'Ofinus',
 'Ndre',
 'Immi',
 'Ulhakim',
 'Man',
 'Rsad',
 'Afta',
 'Bah',
 'Ewiyanto',
 'Uyun',
 'Gung',
 'Eibiana',
 'Elly',
 'Horiq',
 'Eddy',
 'Urya',
 'Riyanto',
 'Ebrian',
 'Ati',
 'Ulaiman',
 'Umadja',
 'Ris',
 'Tin',
 'Rdian',
 'Iyanta',
 'Asamudin',
 'Ayu',
 'Ato',
 'Usy',
 'Umurbor',
 'Akhtiar',
 'Acky',
 'Zmi',
 'Aminah',
 'Era',
 'Urwaheni',
 'Antin',
 'Ornelia',
 'Gardam',
 'Atma',
 'Erianto',
 'Ogen',
 'Ulyadi',
 'Uput',
 ...]

In [32]:
EXTERNAL_ITEMS = list(set(clean_gofood + clean_prod + clean_steakhouse + clean_alergen + clean_prod2))

In [33]:
EXTERNAL_ITEMS

['ayam krispy pencet',
 'brookoli bawang',
 '',
 'paket combo a',
 'foxtail riding tribe',
 'lostvape centaurus e40',
 'nutra biskuit kari',
 'azarine magic colour',
 'keset kain model',
 'kitkat choco mix',
 'paket boneka 80k',
 'hugger airblade beat',
 'gatsby urban cologne',
 '[special buy 1',
 'combo 2 kurai',
 'poptomi coffee',
 'fiorenza gk laszlo',
 'soklin deterjen bubuk',
 'sell_a_case phone cases',
 'daging kepiting balado',
 '[1 set] tripod',
 'kemeja formal polos',
 'cah taoge ayam',
 'rexus pa50 usb',
 'paha mulus si',
 'chai tau kue',
 'chicken strips with',
 'powerbank 10000mah built',
 'ring gantungan kunci',
 'samgyeopsal import samcan',
 'curry puff pack',
 'tomyam ayam',
 'cumi cumi kecap',
 'omelette mie keju',
 'samcan rejeki 150gr',
 'hedgren scurry sustainably',
 'toothbrush sikat gigi',
 'tempe sedang /',
 'kusen pintu kayu',
 'stick coklat',
 'daging kepiting saus',
 'bibit keji beling',
 'bantalan target jerami',
 'bintang kerupuk vanila',
 'rinnai paket promo',
 'sapporo kiren',
 'lekker holland',
 'ringke fusion case',
 'bueno - mini',
 'paket upgrade lampu',
 'resikda',
 'endog kulit crispy',
 'beef teriyaki',
 'suction cleaners alat',
 'esqa slick drip',
 'japanese matcha large',
 'bola tenis dunlop',
 'amara cutie frutti',
 'daging sapi rendang',
 'celana jeans oxygen',
 'lampu proyektor cahaya',
 'tas ransel laptop',
 'mentai cream udon',
 'mobile portable 5l',
 'xiaomi powerbank 3',
 'pizza molen cokelat',
 'ayam kulit crispy',
 'yuwell',
 'leivy double moisturizing',
 'udang mayo',
 'teh botol',
 'sehat wanlta kompiit',
 'korean rainbow yogurt',
 'zeribowl milk',
 'soft case galaxy',
 'toping sosis',
 'cake pisang barangan',
 'cheese ball original',
 'paket wareg 2',
 'frame kacamata laki',
 'cosmos dry iron/setrika',
 'alami kue tart',
 't shirt lokal',
 'dmm daging giling',
 'jumbo paket 2',
 'santap sereal',
 'durian keju',
 'blewah',
 'corong toa zh',
 'brokoli cah seafood',
 'es milo d',
 'hot berry choco',
 'sensatia lemonhead lip',
 'stopper anting karet',
 'parfum premium vs',
 'frestea 500ml melati',
 'nasi goreng cabai',
 'lampu tidur motif',
 'pao',
 'blend ice thai',
 'maple croffle',
 'tanaman hias marbel',
 'rak dinding serbaguna',
 'milk bath dessert',
 'biodef body wash',
 'reng kayu 2',
 'paket nasi biryani',
 'iced mango latte',
 '[ori]jaysuing lem anti',
 'cabe bawang putih',
 'stop keran /',
 'jus jambu',
 'bika ambon original',
 'jakarta sebelum pagi',
 'casing armour office',
 'acp decobond 3mm',
 'gree circool gcacircool25',
 'anker powerport charger',
 'milkshake banana',
 'studio tropik flawless',
 'hanasui mattedorable lipstick/lipstik',
 'baju koko kurta',
 'y15 yoga body',
 'lemari pakaian wdc',
 'pintu kamar hpl',
 'kahf revered oud',
 'colenak',
 'baked blueberry cheesecake',
 'pc rakitan office',
 '10pcs 180 18pf',
 'prima sereal keju',
 'ifumie goreng telur',
 'dermagift',
 'sandwich krim keju',
 'martabak telur mini',
 'semen jakarta pcc',
 'arei nevis sepatu',
 'hot dolce latte',
 'calbi nhbe 625',
 'gorden jendela/hordeng embos',
 '1 porsi sambal',
 'combo amo fire',
 'choco chiffon /slice',
 'paket armguard &',
 'hainam campur jumbo',
 'pluvia nikita sepatu',
 'zebra cake coklat',
 'mie ayam komplit',
 'yale mortise lock',
 'kacamata baca blueray',
 'nachos kyogi',
 'tissue / tisu',
 'seblak mie tiow',
 'kopi susu tiramisu',
 'ikea nattjasmin sarung',
 'gear set kipas',
 'ikan laut goreng',
 'ice sarsaparilla float',
 'lele geprek',
 'nutra roti tawar',
 'psbb kulit',
 'ice almond latte',
 'salmon bomb',
 'cetak foto print',
 'gurami saos',
 'jaket windbreaker pria',
 'prima yoghurt kari',
 '3pcs clip rambut',
 'kemeja pendek pria',
 'kunci pintu kodai',
 'keramik lantai 30x30/',
 'consina',
 'butterred bundle trio',
 'aksesoris cincin terlaris',
 'milkshake mocca spesial',
 'ugreen cable c',
 'red fried rice',
 'lozta indonesia sandal',
 'meja set 100x60',
 'labu almond f1',
 'tempe + tahu',
 'nasi lele ayam',
 'burger special geprek',
 'love potion',
 'fried rice +',
 'kostum jubah labu',
 'paket sound masjid',
 'hot sanger espresso',
 'kaos kaki winter',
 'mie ayam telur',
 'lemonade stardust 1l',
 'sanger hrd banana',
 'boxer motif premium',
 'yakiniku special beef',
 'mgm 438 kotak',
 'chicken katsu 2pc',
 'nuget ayam goreng',
 'rocket 10',
 'daging aus sliced',
 'black burger jumbo',
 'medris penghasil oxygen',
 'car air purifier',
 'creamy mushroom patty',
 'winod tyra sepatu',
 'digital lock/ smart',
 'kingma kabel charger',
 'good day 3in1',
 'bawang putih [100g]',
 'kaso 100x4x4 jati',
 'gultik tanpa nasi',
 'premium dog food',
 'aven kain celemek',
 'ikan dori salted',
 'sikat gigi untuk',
 'ti-amo toast',
 'chocolate beverage',
 'megam karpet lantai',
 'blw zero baju',
 'ichi ocha',
 'esteh original medium',
 'anting emas klep',
 'sepeda listrik pacific',
 'red velvet cincau',
 'aish outer batik',
 'fruitarian drink',
 'apron plastik celemek',
 'mojito lechy',
 'kakaren kaos kaki',
 'lychee lust',
 'loyang 10 ayam',
 'selera yoghurt vanila',
 'promo !! baju',
 'manset spendek lengan',
 'samsung qa55ls01b qled',
 'mouse murah kualitas',
 'ac tcl 1',
 'soji helm reno',
 'lantai vinyl spc',
 'ap pro masker',
 'kr asam manis',
 'cincin kawin chaniel',
 'mojito peach',
 'peach please',
 'infinix smart 10',
 'jaket semi parka',
 'es yori',
 'panzerotti durian',
 'pioneer se c3t',
 'purbasari velvet lip',
 'official plush smiley',
 '(cuci gudang) falado',
 'jagung susu coklat',
 '[buy 2 get',
 'bakso',
 'makaroni spiral',
 'goela aren latte',
 'chicken steak +',
 'pizza petak',
 'ice blend',
 'jordan oral care',
 'moria bb005 dompet',
 'boneka original line',
 'tori ball',
 'sandal pria japit',
 'oxygen concentrator philips',
 'jasmine green tea',
 'white zebra',
 'freckles bento box',
 'sandisk flashdisk 128gb',
 'kado emas antam',
 'sop ayam kriuk',
 'bakwan kangkung 10',
 'seblak ceria 3',
 'plafon pvc terbaik',
 'boneka beruang putih',
 'kopi bubuk termurah',
 'jeruk medan super',
 'petualang sawarna',
 'sanger nongki',
 'bolde lunch meal',
 'lego 40093 snowman',
 'official store',
 'butterscotch',
 'nasi telur itik',
 'teh jus apel',
 'surau kebaya',
 'handuk mandi polos',
 'sei ayam saus',
 'bintang kopi instan',
 'rok plisket duyung',
 'belden kabel data',
 'corong oli /',
 'grab n go',
 'dux ducis tempered',
 'kaki babi',
 'mama sing celengan',
 'tiramisu cheesecake',
 'mainan anak building',
 'off white fw',
 'fish roll 500gram',
 'hem pendek xxl',
 'sehat yoghurt',
 'lil bro chicken',
 'gorden motif bunga',
 'endless parfume 60ml',
 'alenka blouse baju',
 'martabak pisang keju',
 'black pizza sausage',
 'puding coklat',
 'staycool socks kaos',
 'garansi 3 tahun',
 'busa packing 200cm',
 'okechuku sw unlimited',
 'moiro blackpepper',
 'memory card flash',
 'small ice tiramisu',
 'masker sensi duckbill',
 'cincin berlian eropa',
 'ote-ote',
 'b gulung kelapa',
 'sakumini kids toothpaste',
 'lapis prune',
 'lasika jam tangan',
 'mie kuning ceker',
 'mie jumbo kobong',
 'boneka teddy bear',
 'alami yoghurt vanila',
 'anlene gold 5x',
 'aqualuxe lem anti',
 'lampu gantung hias',
 'kaca cermin 120x35cm',
 'kepiting soka goreng',
 'emina star lash',
 'imboost suplemen daya',
 'pizza jamur medium',
 'sodium alginate food',
 'toples bumbu',
 'otak2 udang free',
 'crispy chicken steak',
 'lg 75nano80asa',
 'darkchoco original',
 'n1b. kitsune soba',
 'mefinal 500 mg',
 'iced cappucino',
 'bihunku goreng paket',
 'nasi belut telor',
 'informa 90x160 cm',
 'tartar chicken rice',
 'mango whole cake',
 'oppo a3x 6gb/128gb',
 'ikan nila goreng',
 'kebaya bali viral',
 'mortar utama mu',
 'working gloves 5b',
 'corenation soft yoga',
 'nasi mandhi hampers',
 'indomie kangkung belacan',
 'roti tawar istimewa',
 'clara outer batik',
 'evocore lemari pakaian',
 'sepeda listrik exotic',
 'es cao hitam',
 'novel terjemah obral',
 'snack viral /',
 'cosmos magic com/rice',
 'mc vanilla',
 'tawar lembut friends',
 'cincin couple hitam',
 'es/hotgood day freeze',
 'sasa tepung ayam',
 'original mutiara by',
 'e',
 'masker duckbill 4d',
 'onestep hiv test',
 'boneka mainan bear',
 'luna hair dryer/pengering',
 'nasi timbel ayam',
 'sandal heels hak',
 'es nutri sari,es',
 'gantungan kunci no',
 'taro latte dingin',
 'syafiraaa',
 'bundling delinghi mesin',
 'timetosport 2 in',
 'boneless paha kulit',
 'ice mango tea',
 'egg pudding',
 'green apple',
 'choco oreo ice',
 'denpoo vacuum cleaner',
 'bacon babi premium',
 'kenmaster lem super',
 'tebus murah mukbang',
 'fg punch',
 'es boba avocado',
 'record nagita sneakers',
 'kasur termurah seprei',
 'cocoa cloud macchiato',
 'iga super 1kg',
 'lapis surabaya uk22cm',
 'platini celana panjang',
 'kambing',
 'mie gobyoss beef',
 'bakmie sedap siantar',
 'ottoke jajangmyeon',
 'boba green tea',
 'es durian milo',
 'beli 1 gratis',
 'nutra kerupuk vanila',
 'mie sakura goreng',
 'kispray dus bluis',
 'cumi',
 'kukubima susu',
 'bintang saus keju',
 'meringue',
 'santap yoghurt kari',
 'simplus blender juicer',
 'charger laptop/notebook universal',
 'mie paket 1',
 '910 nineten haze',
 'acer aspire lite',
 'nasi bakar meko',
 'natural cream cheese',
 'plato tirai jendela',
 'amplifier fc a8240',
 'karburator karbu super',
 'pinset besi serbaguna',
 'corndog moza-tempura ikan',
 'cottonbee basic',
 'karpet talang tebal',
 'lenyes ca51 mini',
 'buntut bakar madu',
 'sapo tahu vegetarian',
 '(free pentul)paris jadul',
 'shrimp tofu',
 'gorden gordeng gordyn',
 'puma topi anak',
 '5 porsi nasi',
 'wagyu top blade',
 'skelly gantungan kunci',
 'ciput tali simple',
 'korean garlic',
 'sambal pedas meatyball',
 'roti pisang keju',
 'cosrx salicylic acid',
 'naget ayam so',
 'sparkling peach lemonade',
 'the palace dj',
 'kerupuk jangek',
 'raket maxbolt black',
 'regaji husus belah',
 'bundle 2pcs',
 'balsem otot |',
 'sweetpresso',
 'merah putih handuk',
 'stp brake fluid',
 'otak - otak',
 'unica karpet plastik',
 'roma 4',
 'buku tulis mandarin',
 'foom pod x',
 'vacuum cleaner bed',
 'cameleo large',
 'kacamata fotokromik anti',
 'peptisol vanila 189',
 'burger spesial king',
 'blus atasan wanita',
 'melted cheese set',
 'kohike mathca au',
 'kakap thai dressing',
 'rasa biskuit',
 'fuyunghai kepiting',
 'keloreena original 100%',
 'bakwan campur',
 'chikuwa',
 'promo tabung oksigen',
 'vins aust special',
 'nutra sosis cokelat',
 'rinnai',
 'cheesy pizza',
 'original beef bowl',
 'regulator las oksigen',
 'chicken wings party',
 'nasi telor gulai',
 'frozen soursop (iqf)',
 'sarung guling microtex',
 'teh susu coklat',
 'sop buntut asam',
 'samosa beef',
 'white pizza',
 'milk shake',
 'bebek bakar tanpa',
 'mountainhiker kompor gas',
 'ini teh susu',
 'jersey adidas y',
 'royal life stainless',
 'danish',
 'jaket bomber parasut',
 'dfc personal',
 'cuci gudang /',
 'fenix are',
 'combo rf x',
 'benang jahit 500',
 'wig premium rambut',
 'relay hella ori',
 'bisa cod c5072',
 'mie kuah instans',
 'liangwe lentiven lampu',
 'tic tac',
 'qarieen abaya //',
 'donat oreo',
 'seblak indomie kuah',
 'garlic fried rice',
 'baked strawberry cheesecake',
 'sushi salmon torio',
 'ikan gurame asem',
 'somay kubis',
 'miyako wd190ph dispenser',
 'mykonos luminos extrait',
 'indomie seafood merah',
 'azko soleil grande',
 'anker soundcore k20i',
 'paddle shift innova',
 'lampu proyektor bintang',
 'moicik blackpepper',
 'combo ayam bakar',
 'pink summer',
 'promo hoodie pria',
 'tropicana slim diabtx',
 'nerolight smart emergency',
 'paket kirian 3',
 'dl beauty acne',
 'kabel power komputer',
 'mainan squishy nailong',
 'kedondong',
 'puri rak dinding',
 'lampu filamen edison',
 'fresh white milk',
 'choco milkshake',
 'buku rindu',
 'tartar sauce',
 'mighty kacamata hitam',
 'anker zolo b2699',
 'sosis keju',
 'fantasy custom kaca',
 'es kopi tiramisu',
 'super telor ayam',
 'sumiyaki ika sansho',
 'tokyo1 virus out',
 'liontin kalung emas',
 'abaya qareena full',
 'lampu kamar tidur',
 'mainan edukasi anak',
 'gurami tauco /',
 'mentarang',
 'mie cjdw jombo',
 'jaket olah raga',
 'buah beku daging',
 'lavender long bishop',
 'sausage fries combo',
 'waldo east (original)',
 'cincin tiaria jewelry',
 'zenbu mozaru /',
 'softies 3d surgical',
 'sushi kani tamago',
 'vibesbags totepack vilan',
 'dimsum 49 flash',
 'hot wheels promo',
 'paket 6',
 'kremlin topi ripped',
 'infinix xpad20 lte',
 'kotak plastik bening',
 'hot almond latte',
 'outer lowo bolak',
 'sarung wadimor jawa',
 'fettucine parmigiana',
 'topping squid',
 'rasa biskuit cokelat',
 'tteoboki sosis',
 'dakui + ocha',
 'siokee per ekor',
 'kirin hair dryer',
 'bandana polos polister',
 'sweat miniature pu',
 'gula aren impor',
 'braderparts baterai battery',
 'durian coffee',
 'kuro samurai sushi',
 'alami nugget ayam',
 'jr sapporo',
 'jus strawberry',
 'egg',
 'kostum raja imlek',
 'cellkit alat pembuka',
 'backpack bag swimming',
 'podium minimalis, mimbar',
 'regulator oksigen o2',
 'mango freshmilk',
 'vicks vaporub 50',
 'large',
 'topokki large',
 'wardah lip cream',
 'hangang potato corn',
 'feeding tube ring',
 'indomie rebus seafood',
 'bosch gbm320 professional',
 'dirty matcha dalgona',
 'sage chair kursi',
 'zact pasta gigi',
 'nasi soulmate',
 'kornet crispy',
 'mineral botol',
 'es cao susu',
 'gosave masker respirator',
 'choco chesee mini',
 'dadar telur',
 'voted padel quarter',
 'fan belt tali',
 'ara minyak esensial',
 'theravol oil natural',
 'bbq & cheese',
 'cah tauge teri',
 'dodol betawi asli',
 'tetsin mochi mochio',
 'pancake durian pandan',
 'gantungan kunci label',
 'plossa press &',
 'salt n pepper',
 'lampu gantung /',
 'hp flashdisk metal',
 'zoyi gm550 digital',
 'pop ice lychee',
 'matcha hokkaido',
 'beyou by bucini',
 'coffee chocolate',
 'alltrek water bottle',
 'mango silky puding',
 'chocolate muisjes bombolone',
 'pentol petir',
 'bintang biskuit ayam',
 'kaca tahan panas',
 'hot kopi avocado',
 'polymer clay jual',
 'bufet minimalis jati',
 'undefeated totebag original',
 'chesee tea',
 'setrikaan / gosokan',
 'hairdryer wigo taifun',
 'suka ikan gurami',
 'fantech mouse wireless',
 'bihunku ayam bawang',
 'tansuju+mesis',
 'roti bocah isi',
 'paket anti rayap',
 'cappucino c',
 'batagor bandung',
 'pepsodent pencegah gigi',
 'udang rambutan 3pcs',
 'spaghetti quemami',
 'pahebat beef burger',
 'maybelline the blushed',
 'alami sereal',
 'teriyaki madness',
 'boneka hoki tahun',
 'eelic lampu meja',
 'balsem aktiv cap',
 'wispie girl boss',
 'lychee tea 1l',
 'unagi kabayaki japan',
 'asam manis',
 'burger daging crispy',
 'lavio safety boots',
 'ayam jamur',
 'boneka lotso original',
 'bogul kelepon kecil',
 'santap selai vanila',
 'stik gorden jendela',
 'rasa keripik keju',
 'murrey case 1x1',
 'boneka beruang pink',
 'otiv socks collection',
 'lalapan ikan lele',
 'wardah perfect bright',
 'tahu go 10pcs',
 'cumi tepung',
 'baked cheese cake',
 'banana foster pancakes',
 'bolu gulung alpukat',
 'chikuwa long',
 'kabel lan 15m',
 'tambah mozzarela',
 'kabel chain carrier',
 'bihun goreng 512',
 'belut goreng tepung',
 'prima cup',
 'pahe 5',
 'hot lychee tea',
 'pancong greentea s',
 'nasi goreng kecap',
 'pudding mango',
 'lego city police',
 'anker nano charger',
 'makmur selai ayam',
 'promo combo bibi',
 'karbonat babi /',
 'ice coffee',
 'tumis capcay',
 'scarlett whitening skin',
 'sosis bakar teriyaki',
 'mineral water',
 'halal 100% original',
 'kacamata baca besi',
 'sarang maduku',
 'black beef',
 'new deerma cm800',
 'ha',
 'banyak 2',
 'promo yt 708/352/240',
 'r',
 'lime tea',
 'rayya pashmina viscose',
 'sweet sunrise',
 'olahan cumi',
 '40 color eyeshadow',
 '[kbc beautetox] hello',
 'kasur springbed inthebox',
 'waffle tiramisu',
 'giv body wash',
 'smart tv 32',
 'hello kitty -',
 'iced sweet tea',
 'madu manuka mgo',
 'cake marmer',
 'ac aqua japan',
 'mie graga original',
 'cod!!! isi 100pcs',
 'edamame original',
 'tino tino kalung',
 'milkis strawberry',
 'sup bakso tahu',
 'kiniko chawanmushi',
 'sepatu outdoor merrell',
 'pepes kakap',
 'baby spinach salad',
 'seblak kepala ayam',
 'petualang sembalun mid',
 'air mineral 330',
 'osaka tea',
 'karpet lantai mobil',
 'ice thai milk',
 'combo mabar fc',
 'botol minum plastik',
 'vanilla cookies',
 'mango usagi',
 'chicken teriyaki gunkan',
 'seblak dumpling cheese',
 'rexus arka ii',
 'selada bulat organik',
 'mobil 2000w peak',
 'pisang keju petak',
 'spaghetti beef blackpepper',
 'boneka barbie mattel',
 'frasser matrass beladiri',
 '3pcs croffles',
 'pork lapchiong 500gr',
 'meja abk meja',
 'peci miki hat',
 'la fancy foods',
 'choco crunchy creme',
 'karburator carburator xeon',
 'noxious setelan baselayer',
 'gelas kaca akari',
 'sup sapi',
 'mt.edma twister 56in',
 'nuudo daily moisturizing',
 'vit-c monster',
 'mochacino hot',
 'maspion ex',
 'ikan goreng filet',
 'minyak goreng 1',
 'double beef cheese',
 'utp ftp cat',
 '[live] cod miyako',
 'ayam geprek wrap',
 'sonifer hair dryer',
 'bolu gulung kacang',
 'teh pahit hot',
 'kacamata fashion wanita',
 'diskon handsock jempol',
 'yoona crm591 cermin',
 'kwitiaw nyemek daging',
 'bakso petruk',
 '(cod) karburator keihin',
 'nats living: kalung',
 'acre crispy duck',
 'motor tvs ronin',
 'lidah lada garam',
 'bonsai sianci',
 'dunlopillo guling white',
 'black coffee 1',
 'hicoop',
 'crystallure supreme advanced',
 'melon juice',
 'ms glow acne',
 'roti klepon',
 'outer longkardi batik',
 'ikan dory 1kg',
 'anker powerdrive iii',
 'gorden plisket blackout',
 'korek api zippo',
 'jane tea',
 'mie kuning kuah',
 'bonsai sancang cakep',
 'martabak telur loyang',
 'claris foodsaver 2733',
 'pao isi ayam',
 'cake kurma',
 'pouch wiwu warriors',
 'nasi mandhi',
 'lemon pepper fries',
 'shargeek 170 pd',
 'kwitiaw kuah telur',
 'terry palmer luxury',
 'novel lavender remaja',
 'king ka',
 'joil gunting kuku',
 'magic mat (beli',
 '[additional] alva board',
 'urap',
 'indo kerupuk cokelat',
 'chocolate mint',
 'lg 65qned80tsa',
 'brownis bolu',
 'standing mirror ukuran',
 'tas ransel anak',
 'ice lychee tea',
 'siomay & batagor',
 'ayam saos inggris',
 'hana emas tepung',
 'alami saus',
 'keju jepang',
 'kaos graggreg',
 'liquid why banana',
 'mie sop medan',
 'wedhang kbon',
 'sandal wanita sandal',
 'combo ayam geprek',
 'rasa sereal keju',
 'sempak pria /',
 'gula merah aren',
 'isocal rasa vanila',
 'bubuk minuman premium',
 'coffee bun',
 'melon keju',
 'tepung terigu gerbang',
 'sarung guling katun',
 'buy 1 get',
 'kopiah peci hitam',
 'es susu milo',
 'es sugu',
 'calamary udon',
 'komplit pakai ayam',
 'record shinjuku sepatu',
 'aukey qi2 magsafe',
 'beef carbonara udon',
 'pashmina viscose bamboo',
 'hemat combo 3',
 'indo biskuit',
 'tanaman bonsai pushu',
 'gochugaru masita for',
 'kertas hvs 75',
 'dada ayam fillet',
 'kintakun home bt21',
 'cokolateh soulmate',
 'extra patty mozarella',
 'paket sejoli c',
 'fish ball soup',
 'teh poci leci',
 'hot caramel latte',
 'ayam goreng lada',
 'roti kukus jamur',
 'super gaming meja',
 'indomie',
 'jus wortel',
 'roti gula',
 'paikut super sop',
 'irish latte',
 'spare pork ribs',
 'bogul pandan keju',
 'jepit rambut tanaman',
 'mie komplit mozza',
 'kopi baileys purin',
 'coklat milkshake',
 'matcha milk',
 'soes buah',
 'uncle goober bites',
 'meja rias kaca',
 'azzure earrings moissanite',
 'bakso aci original',
 'food storage lunch',
 'mie cjdw cemek',
 'evangeline parfum sakura',
 'rexus s5 aviator',
 'brownies potong mika',
 'helm bogo retro',
 'pecel lele no',
 'daktongjib bokeum',
 'novel : pulang',
 'rexus ergonomic chair',
 '[official bmth] ribcage',
 'henna eagle black/brown',
 'risoles beef',
 'nasi kulit bara',
 'kukee 50 cm',
 'nasi campur +',
 'hanasui lip cream',
 'kacamata radiasi baca',
 'kabel patchcord sc',
 'truffle saikoro mentai',
 'teavana ice tea',
 'rocky milk vanilla',
 'makmur mayones',
 'pajero die cast',
 'sayur segar bandung',
 'ice coklat atjeh',
 'bacem puyuh',
 'ultimate ramen',
 'trombozzo',
 'pork belly buns',
 'karpet tikar spon',
 'nyk nemesis daemon82',
 'murah ! original',
 'tripod somita st',

In [34]:
print(f"Loaded {len(EXTERNAL_NAMES)} clean names and {len(EXTERNAL_ITEMS)} items!")

Loaded 1105 clean names and 44821 items!

In [35]:
def generate_random_price():
    slang = ["cepek", "goban", "gocap", "seceng", "cenggo", "goceng", "pekgo"]
    if random.random() < 0.2:
        return random.choice(slang)

    formats = [
        lambda: f"{random.randint(10, 500)}k",
        lambda: f"{random.randint(10, 500)} ribu",
        lambda: f"{random.randint(10, 500)}rb",
        lambda: f"{random.randint(1, 9)}.{random.randint(1,9)}jt",
        lambda: f"{random.randint(10, 999)}.000"
    ]
    return random.choice(formats)()

In [36]:
def build_massive_dataset(templates_file, output_file, multiplier=100):
    with open(templates_file, 'r', encoding='utf-8') as f:
        templates = json.load(f)
        
    augmented_data = []
    
    for template in templates:
        for _ in range(multiplier):
            new_text = template["raw_text"]
            replacements = {}
            
            for ent in template["entities"]:
                placeholder = ent["value"]
                ent_type = ent["entity"]
                
                if placeholder not in replacements:
                    if "PERSON" in ent_type: 
                        replacements[placeholder] = random.choice(EXTERNAL_NAMES)
                    elif "ITEM" in ent_type:
                        replacements[placeholder] = random.choice(EXTERNAL_ITEMS)
                    elif "PRICE" in ent_type:
                        replacements[placeholder] = generate_random_price()
                    else:
                        replacements[placeholder] = placeholder
            
            for placeholder, actual_value in replacements.items():
                new_text = new_text.replace(placeholder, str(actual_value))
                
            final_entities = []
            
            for ent in template["entities"]:
                placeholder = ent["value"]
                ent_type = ent["entity"]
                actual_value = str(replacements[placeholder])
                
                for match in re.finditer(re.escape(actual_value), new_text):
                    span_start = match.start()
                    span_end = match.end()
                    
                    is_duplicate = any(
                        e['start'] == span_start and e['end'] == span_end 
                        for e in final_entities
                    )
                    
                    if not is_duplicate:
                        final_entities.append({
                            "entity": ent_type,
                            "value": actual_value,
                            "start": span_start,
                            "end": span_end
                        })
                        
            augmented_data.append({
                "raw_text": new_text,
                "entities": final_entities
            })
            
    random.shuffle(augmented_data)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(augmented_data, f, indent=2, ensure_ascii=False)
        
    print(f"Created {len(augmented_data)} rows with exact character coordinates!")

In [37]:
build_massive_dataset("talangin_synthetic_templates.json", "training_data.json", multiplier=10)

Created 24900 rows with exact character coordinates!

In [41]:
df_train = pd.read_json('training_data.json')
df_train.head()

,raw_text,entities
0,Plis bgt Lpiyah sama Yaiful buruan tf soalnya ...,"[{'entity': 'PERSON', 'value': 'Lpiyah', 'star..."
1,"Punten Kak Ucy sama Kak Tan, maaf bgt ya kalo ...","[{'entity': 'PERSON', 'value': 'Ucy', 'start':..."
2,Kosong bgt rasanya kek dompet gw skr gara2 ats...,"[{'entity': 'ITEM', 'value': 'ats gergaji mura..."
3,Adh pusing bgt baru bngun. Itu jam tangan smar...,"[{'entity': 'ITEM', 'value': 'jam tangan smart..."
4,Sumpah ya Ega lg liat mutasi rekening kok nama...,"[{'entity': 'PERSON', 'value': 'Ega', 'start':..."

In [42]:
from collections import Counter
import ast

In [43]:
if isinstance(df_train['entities'].iloc[0], str):
    df_train['entities'] = df_train['entities'].apply(ast.literal_eval)

In [ ]:
def check_dataset_quality(df):
    print("=== DATASET OVERVIEW ===")
    print(f"Total Rows: {len(df)}")
    print(f"Duplicate Texts: {df['raw_text'].duplicated().sum()}\n")
    
    all_entities = []
    for ents in df['entities']:
        for ent in ents:
            all_entities.append(ent.get('entity'))
            
    print("=== ENTITY DISTRIBUTION ===")
    entity_counts = Counter(all_entities)
    for ent_type, count in entity_counts.items():
        print(f"- {ent_type}: {count} occurrences")

check_dataset_quality(df_train)