In [27]:
import pandas as pd
import re
import json
import random

In [3]:
food_dir='dataset/gofood_dataset.csv'
prod_dir = 'dataset/tokopedia_product_reviews_2025.csv'
names_dir = 'dataset/Indonesian_Name_Dataset.csv'

In [4]:
df_food = pd.read_csv(food_dir)
df_food.head()

,merchant_name,merchant_area,category,display,product,price,discount_price,isDiscount,description
0,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Almara Kopi (kopi Susu Gula Aren),20000.0,NaN,0,Sajian Kopi Susu Gula Aren Yang Berbeda Dari K...
1,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice Almara Kopi (kopi Susu Gula Aren),22000.0,NaN,0,Sajian Kopi Susu Gula Aren Yang Berbeda Dari K...
2,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Millsis,20000.0,NaN,0,Sajian Susu Coklat Milo Dengan Racikan Khas 3 ...
3,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice Millsis,20000.0,NaN,0,Sajian Susu Coklat Milo Dengan Racikan Khas 3 ...
4,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Millbro,22000.0,NaN,0,Sajian Susu Coklat Milo Plus Espresso Dengan R...

In [5]:
df_prod = pd.read_csv(prod_dir)
df_prod.head()

,review_text,review_date,review_id,product_name,product_category,product_variant,product_price,product_url,product_id,rating,sold_count,shop_id,sentiment_label
0,baru sekali ini terima brg dr belanja online d...,2024-12-22,1134256160,Telur Ayam Kampung Asli - Telur Mengandung Ome...,Makanan & Minuman,Box Polos,87000,https://www.tokopedia.com/indofarmproduct/telu...,4601033481,5,1000000,8672687,positive
1,cocok bgt aku sama telur nya. nga Amis menurut...,2025-02-25,1242584634,Telur Ayam Kampung Asli - Telur Mengandung Ome...,Makanan & Minuman,Box Polos,87000,https://www.tokopedia.com/indofarmproduct/telu...,4601033481,5,1000000,8672687,positive
2,Telornya sudah sampai di rumah dengan kemasan ...,2025-07-15,1573444677,Telur Ayam Kampung Asli - Telur Mengandung Ome...,Makanan & Minuman,Box Polos,87000,https://www.tokopedia.com/indofarmproduct/telu...,4601033481,5,1000000,8672687,positive
3,Telor sudah diterima dengan baik dan tidak ada...,2025-07-20,1581728541,Telur Ayam Kampung Asli - Telur Mengandung Ome...,Makanan & Minuman,Box Polos,87000,https://www.tokopedia.com/indofarmproduct/telu...,4601033481,5,1000000,8672687,positive
4,"Alhamdulillah penjual amanah,Telor nya terbaik...",2023-04-24,881041355,Telur Ayam Kampung Asli - Telur Mengandung Ome...,Makanan & Minuman,Box Full Design,87000,https://www.tokopedia.com/indofarmproduct/telu...,4601033481,5,1000000,8672687,positive

In [6]:
df_names = pd.read_csv(names_dir)
df_names.head()

,Unnamed: 0,NAMA,Count,Kategori,Jumlah Suku Kata,jumlah kata,Jumlah Huruf Vokal,Jumlah Huruf Konsonan,Jumlah Huruf
0,0,ANJAR SUROTO,1,Pribadi,5,2,5,6,11
1,1,REINHARD RUDIYANTO SIHITE,1,Pribadi,9,3,10,13,23
2,2,ABD RAHIM NANI,1,Pribadi,5,3,5,7,12
3,3,DRS MUSTAPHA AFIFF,1,Pribadi,5,3,5,11,16
4,4,FAIZ FIRDAUS,1,Pribadi,3,2,5,6,11

In [7]:
raw_names = df_names['NAMA']
raw_names.head()

0                 ANJAR SUROTO
1    REINHARD RUDIYANTO SIHITE
2               ABD RAHIM NANI
3           DRS MUSTAPHA AFIFF
4                 FAIZ FIRDAUS
Name: NAMA, dtype: str

In [8]:
raw_names.tolist()

['ANJAR SUROTO',
 'REINHARD RUDIYANTO SIHITE',
 'ABD RAHIM NANI',
 'DRS MUSTAPHA AFIFF',
 'FAIZ FIRDAUS',
 'RIKI YULISMAN',
 'JUNARIO HP SRG. A',
 'M.ROBBY',
 'MIRHAN',
 'J.PARDEDE IV',
 'SUKARTINAH',
 'ELI SONALIA',
 'MOCH SODIKIN',
 'I KETUT WARDIANA',
 'TRINDO JUNAEDI',
 'ARI FATIMAH',
 'I DEWA GEDE WISASTA',
 'HUSAIN JAYA',
 'AHMAD SYAEFULLOH',
 'MUHAMAD KHOLIL',
 'ROCHADI C',
 'HARTON SE',
 'DANI FIQIH 06',
 'KAMRIL',
 'EKO NOVAN SAPUTRO(CUCIAN)',
 'SAMSUDIN. A',
 'SUKLI',
 'NURLELI SAGITA',
 'CHANDRA WINARSIH',
 'NI WAYAN SUDARIATI',
 'M.ZAIDI',
 'RIWOTO',
 'MIYAR / NIYAR',
 'AL HOERIAH',
 'DRS SUBAHI IDRIS MM',
 'HENDRA JAYA 02',
 'LIE ANDY KUSMANTO',
 'PETRUS APRIANTO 01',
 'HASANUDDIN S',
 'HUZEIN NOOR',
 'NURBIYANTONI',
 'DIDIET RADITYO',
 'SITI SUWARTIK',
 'ANDRE YULIUS TJAHYA S',
 'ADE MULYANI',
 'SALMAN PARSI',
 'ARI MINDAYANI',
 'LA HANUGA',
 'H. NASRUDDIN',
 'SITI HANDRIANI',
 'IIN ABDUL SALEH',
 'DAVY LENSOEN TJOMAN',
 'SETYA NINGRUM',
 'INFAN ANNUR NAGA',
 'WIBAWA SAPUTRA',
 'ZAINUDDIN HUSIN',
 'NICO SECIO',
 'INTAN MUTHIA',
 'AMIN THOHARI',
 'ELLIANIS 3',
 'KEVIN JOSUA SIRAIT',
 'YUSTINA SURATINI',
 'NI WAYAN PUSPINI',
 'HARDY WIRAWAN RUTON',
 'DAVID HENDRI LIEM',
 'NI KADEK PUTRI INTARI',
 'TEDY SUBIYARSONO U/APOTIK',
 'H M SUBANDI',
 'PAWIT ALFADI',
 'SUROYONO',
 'WAHYUDI A',
 'J KUSNADI',
 'SUTJIPTO 2',
 'AMRI GUSMAN',
 'MOHD PUJI ALFAED 10',
 'DESAK MADE ASRI YUNI',
 'SAIFUL BAHRI/NAGA',
 'INDRA NUR ASRAFFI',
 'UNU HIDAYAT',
 'DEDE JUANDA',
 'ERLINA,SH',
 'LAWIDIN',
 'MARIE ABDULLAH',
 'S U M A',
 'YOPPIE BUDIONO',
 'SATIYAH 2',
 'KHALIMI',
 'GITO YEKTINI',
 'TENRI VADA EDA',
 'WAHYUDIN BIN H UCIN',
 'EKO PRIYO',
 'BAYU REDA ALDIO PURNOMO',
 'A H U I',
 'MARTANTO SULISTIO',
 'NURDIN ADAM',
 'CUT NURAIDA',
 'JUMSIH',
 'TUTIK ALFIYAH',
 'HARI RISDIYANTO',
 'SARIYEM/BLOK E',
 'NOVIYATUL QIFTISAROH',
 'MUHAMMAD NAUFAL A.A',
 'WIDYA WULANDARI',
 'HERY GUNAWAN (2)',
 'DIYAH SETYANINGRUM',
 'TRI ISMAN ROHADI',
 'M SAHWA',
 'SONNI SUSANTO',
 'NUNUNG NURHALIMAH',
 'H KASMI',
 'I GEDE ARJANA',
 'IIN SOLINAR',
 'ANNA PRIHARTATI',
 'RAMLI YS',
 'HNS GINTING',
 'RAHADIAN RACHMAN',
 'YETI HANDAYANI',
 'IDA FITRIA NINGSIH',
 'YUDIANTO B. ANDRIAWAN',
 'ROSLENA',
 "HJ DUHAETI BT MA'RUP /TOK",
 'NURHAYAT',
 'THONG LENA',
 'HJ.NUROHMAH',
 'DIDIK MUFRIANTO/A',
 'RENI NURAENI (KEBIDANAN)',
 'HERMAN SETIA BUDI. B',
 'HJ. SITI JULAEHA 3',
 'YUSUF WARDOYO',
 'TJONG DJOEN KHOEI',
 'ISWAN LASIKI',
 'INDAH FIRDASARI',
 'MOHAMAD MUHOLIB',
 'YAKIMAN',
 'CHRIS CHANDRA (B)',
 'SEPTIONO INDRASARI SAPUTR',
 'LAIMAN MARGONO',
 'SUHERMAN U/USAHA UDANG',
 'ASMIYANI',
 'JENAL ARIFIN (REST AREA)',
 'H. M WAWAN PRIYANTO',
 'PUPUT RIANA',
 'TJOE KHE BENG',
 'LILY GUNAWAN',
 'PAMSIMAS PANJI TIRTA',
 'CHANDRA SIBARANI II',
 'SUSY ANDAYANI',
 'AGUNAWAN HADI SUSANTO',
 'MUHAMMAD NUR 04',
 'ARDI SUBADRA',
 'HERRY V',
 'M. DANANG ERIAN KOI',
 'LONG BENG LONG',
 'RATIM (AYAM POTONG)',
 'HENDRIK JAYA. S',
 'MAHMANI',
 'RY SUYOTO',
 'NEVY RAHMI NURJANA',
 'H.PAHRUDDIN',
 'NURLIS M.NUR',
 'DESTRO/JOHAN NURKOLIS',
 'AHMAD BAGIR',
 'HJ CICI MUNTASIROH',
 'ARJA',
 'SAHALA.M.LBN.TOBING',
 'ABSAR',
 'EVAN SUTIONO',
 'KUSNIAH',
 'M RIDWANULLOH',
 'IRA SINTAWATI',
 'GRAFIALDI FAKS RIZZA',
 'H. MUYOTO',
 'ISMAIL MARZUQI',
 'IR H AMBO APPE',
 'IVAN MARCO',
 'WAHYU ITA KRISTINA',
 'AHMAD NUROCHMAN',
 'SURASIT',
 'LUKMAN YACUB',
 'I PUTU DARMIKA',
 'H. DAMERI A',
 'DADAN ALI SADIKIN',
 'YOGI YUSWANDI',
 'SUTRA AKMALISA',
 'A.AGUNG SRI SARTIKA SSN',
 'MAR JOHAN',
 'MAMAY SUMINAR',
 'RENALDO TAMBUNAN',
 'ITIN JUBAEDAH RINATA',
 'SELAH AL JUHRI',
 'SAMSUDI LUMBAN BATU',
 'ACHMAD MUCHTAROM',
 'SILVANA LENGGOGENI',
 'RUHIMAT',
 'JONI CAHYOKO 4',
 'ANISATUL WAHYUNI',
 'YANTI AFRIANI',
 'ROPIKA AULIA',
 'ELLY KARTIKA SARI',
 'LIRA DIAN NOFITA 4',
 'GEDE DANA',
 'DESI IRMAYANI',
 'VERONIKA ATIK ANDARWATI',
 'SUNOTO NAGA',
 'HENGKY SIAKIMAN ALI',
 'JAJANG SUPARMAN 2',
 'NUR FUAD HASAN',
 'NY IDAH MUNGSIDAH',
 'HENDRA DINATA/T.BUKU',
 'SUAIB GENI',
 'BUDI BRAMANTYO',
 'JONNER SIBUEA',
 'R. SYAMSUDIRMAN 3',
 'BUDIDAYA ABD KODIR',
 'IRWAN WAHYU ARYANTO',
 'ZULFAZLI',
 'CHANDRA ISKANDAR',
 'NI KETUT MIRAH DWIADI',
 'H. SUTIKMO',
 'ARIE NATANAEL 2',
 'ANGGI TRIYONO/ PECEL LELE',
 'MOCH. ROCHIN ( ABU MOTOR',
 'MIMIN SUKARMIN 2',
 'MICKY LEKATOMPESSY',
 'PENGINAPAN HIDAYAH',
 'ARFIN NUR HENDITYA',
 'TOPAN FRANDITIO',
 'ASAI 1',
 'HERI KUSWARA',
 'AMAT YASIN',
 'ENOK SUMARNI',
 'M. INSYAH',
 'SUKAENI',
 'AGUNG RIANDY',
 'WIYOTO',
 'LISNA DEAHANA',
 'YUSUF ALGAFUR 13',
 'DONNA PURBA',
 'EKA DIAN YULIANTI',
 'IDA BGS MADE SUGIARTA',
 'EPON SUMARTINI',
 'FATMA YULIATI 1',
 'ALBASI PARAHYANGAN',
 'LULUK ANDINI',
 'KATRIN WIDIYANTI',
 'KRIS BUDI HARTANTI',
 'DULWARMAN',
 'DARMAWAN YAHYA SURYA',
 'DINI APRILIYANTINI',
 'ERWAN SAMSIYANTO',
 'FADHLAN SALAMI PUTRA',
 'DWI RUBIYO',
 'HERWIN 10',
 'CING',
 'SUMAUL FIYANI',
 'KUSNUN SARIF',
 'LYSA MAYA SARI (3 )',
 'SRI RETNOWATI L,S.KOM',
 'JESNOS SANDOS',
 'NORIS PRATAMA',
 'H ZUBAIR AL MUDJAHID SH 5',
 'DMT_TSEL_SEL144_AIKMEL2',
 'JAJANG JAELANI',
 'ANJASMARA (A)',
 'LILIK DARYANTO',
 'SALVIDA',
 'YATI SUSANTI',
 'ZAENUDIN CHALMA',
 'IRWAN MBUINGA',
 'NURLELA TAHIR,SP',
 'LASANA',
 'ANI YULIANI',
 'ANGGAR WISNANDARI',
 'AHMAD MUZHOFFAL.SE.MAF.4',
 'CATUR ANDI SUTRISNO',
 'PEK TAW KIE',
 'KEMBAR BROILER',
 'IRIGASI SAWAH ANTON',
 'TIKA MERI VIONA',
 'SIMON WANGDRA',
 'ELYGIA',
 'SITI WARYATI',
 'ADI PUTRA SENTAS PRASETYA',
 'HEULEUR GABAH',
 'NATALY SH',
 'RUHAENI',
 'MELLY YANA SAPUTRI',
 'PRADANARIAN YUFLIK H.',
 'JOKO ISTIYONO',
 'SARDY TANTIONO',
 'HAPRIANSYAH NOOR',
 'TAN TJOEN JOE',
 'IRIGASI SAWAH MUKAIR',
 'ALPIAN NOR M',
 'YANCHE',
 'NURZAJEFRY. SH',
 'HJ SITI AISAH NST',
 'H.NURZAIDI.4',
 'WANDI SUHENDI 3',
 'SYAMSYUDDIN H SYAKUNI',
 'RATNASARI II',
 'NY IDRIS',
 'VENILIA THERESIA',
 'INGIN JAYA',
 'IWAN PITOYO',
 'KADANG AYA RUKIMIN',
 'MUHAMMAD ZUL AFKAR',
 'IWAN REGITO SIREGAR',
 'CHUMAIRI C',
 'DR.H SAAD S NST.SPOG',
 'SARANG WALET SAFRI',
 'M.R FAKHRURROZI',
 'IMAM SANOESI AB',
 'NI KADEK RAI WIRYANINGSIH',
 'ARYANTO DALIH',
 'H ADI JUHADI B',
 'MUZAKIR TUMU',
 'HERMAWAN SETIYONO',
 'ABDULLAH 5',
 'MOH NURCHOLIK',
 'ELVI ZULGANDI',
 'KATIMUN EKO SUSANTO',
 'ANSTHELABEL FASHION',
 'KHABIB YUDI',
 'SYAHRIR DG LILI',
 'ERIK FERDIANSYAH M',
 'I NENGAH DODIT SETIAWAN',
 'ABDUL KHOLIG',
 'ADE OBIANTI 1',
 'MARDALINDA',
 'DRS AMANDUS NAHAS',
 'KUSNADI D',
 'SUYONO NAGA 03',
 'ARIYANTO GOZALY',
 'AA NGR SUENDA',
 'ASMAN LB MARBUN',
 'MUHAMMAD IRSYAD NAJI',
 'SUKIMAN BIN MARSIDIN',
 'IYAN HERYANTO BENGKE',
 'ALWI SETIAWAN A2-8',
 'KUSYANTO HALIM',
 'SURODJO',
 'DILA MEIDAWATI',
 'YANET PRIMA YANI',
 'YASID KHAROMI',
 'AGUS HERI WIDODO B',
 'NRFOOD',
 'ISKANDAR PARIADI',
 'AULIAK',
 'MUHAMAD GHOFARUL IKHSAN',
 'ROSMANIDAR,A MD',
 'RAMP',
 'LO KIUK ME .',
 'DJAROTDJAROTUN',
 "ARBA'IEN",
 'MARDJONI TATSHIR',
 'KAEFIYAH',
 'YOHAN PAMOSANGKA',
 'I NYOMAN GERIAWAN',
 'NUR DIANA AL VIDA',
 'ERNA YUSNITA',
 'NI WAYAN KOMEKAYANTHI',
 'LIS FERADEWI',
 'ZUBEIR ABDAT',
 'A MUKHSIN',
 'ANGGORO LA ANGKA',
 'SAWIN II',
 'OEY DJOEI ING',
 'MOH IHSAN/PERCETAKAN',
 'NI WAYAN SURYATI',
 'NONY YOLANDA/JET PAM',
 'CLAUDIA CITRADEWI',
 'KHABIB MUSTOFA / NAGA',
 'TOYIBUL BANI (A)',
 'KALIMASADA',
 'SUMARNI 01',
 'KANTIN KUA SEPATAN',
 'I KETUT SUDARMA YASA',
 'SITI AISIYAH BT MUNDAKIR',
 'KHOIRI NAGA KOL TGLDLIMO',
 'DAVID TRISNO ST A',
 'FRITS FERI FELLE',
 'IKBAL SAIFUL BAHRI',
 'JOHANURI.E',
 'NGARDAM',
 "YYS DARUL MA'ARIF AL INSA",
 'SELAMAT UDIN',
 'AGUS SUHANDI',
 'FATHAN ACHSAN',
 'J I O',
 'DIDA FARM',
 'JLITENG SUSILO',
 'EKO CHRIS MARTONO',
 'ZACKY SYAHPUTRA',
 'AYU SUNDARI AZIZAH',
 'M.AZMIEN',
 'OEI BING TWAN',
 'H.M MUDIYASIN',
 'ENTI SAPTI 3',
 'ANIP',
 'MUBARIZI ARIFIN 5',
 'ADABI',
 'MOKHAMAD ROSYIDI',
 'MULHAM RAHMAN',
 'H MUSTAJAB AM',
 'EKO DIANTORO 7',
 'ARI JINU PURWANTO4',
 'KHOSIM WIBOWO',
 'WARNAS PUTRA SUNDA',
 'JUNAIDI SETIAWAN',
 'SAEFUL AKHYAR',
 'APIN HERNAWAN',
 'ACHMAD ROFIQI MASHUDIYANT',
 'DONI CARLOS',
 'ALIMUDDIN NASUTION',
 'H JENAB',
 'JIMMI TRAPILO',
 'SAUD MUHAMMAD AL SAHRI',
 'FALTA YUPITA SARI',
 'KRT CHRISNA ATMADJI',
 'NY YUNIDAR',
 'RUSLI AG',
 'NI NENGAH GATRI',
 'LAJUARDI',
 'MARINI 1',
 'LAZUARDI MUHARAM SETIAWAN',
 'JUNIH BIN SOAN',
 'EVA ULLY MARISKA',
 'PUTU EKA KRISNA',
 'ADITYA SRI ADRIAN',
 'DIAN DARMANTO',
 'SAHILAL ARIMI',
 'TRI BUDI CAHAYA',
 'RIFKI PERMANA 2',
 'WALYAMAH',
 'ALI KHOIRUL KHUBIBAH',
 'LESEHAN RIZKI PUTRA',
 'ZAMHUR ZAMZAMI',
 "ROBI'ATU SHOLIHAH 2",
 'SANGGAR TANI',
 'SADAR RIYANTO',
 'WONG PAN TJIAUW',
 'M. SADIKUN',
 'VICKY SANJAYA',
 'YENNY RUSTAM',
 'MURLIANA A - TAJJALI',
 'MUNZIR SAPUTRA',
 'M SOLEH MA',
 'SATRIO AJI NUGROHO',
 'NITA REHANI',
 'ROSYANA (U/MEUBEUL KUSEN)',
 'RAMPEANI RACHMAN',
 'NAIMUN',
 'AGIT ASBIYANTO',
 'SEPNIWATI',
 'HENGKY TJONG',
 'YUNITAWATI',
 'AHMAD THAHA',
 'MENG KHIANG',
 'SIDUHU ZEGA',
 'DALPEREF 2',
 'I KADEK RICKY SUJANA',
 'DWI PUTRI ARSIH K SH 1',
 'RATINGIN',
 'MARIANIE 3',
 'FIPIN ANDRIAS',
 'SIWI ASTUTI',
 'TJOENG LENG TJUI',
 'I GUSTI KETUT MUSTIKA',
 'IRSAN PARLAUNGAN',
 'ACHMAD MAEMUN',
 'ROCKY JEFF MAICHEL SAUPAL',
 'ERIKA NURFATMAWATI',
 'SIYAMA',
 'HERLIKA ( 1 )',
 'I NYOMAN ARIADI',
 'H S ADANG',
 'MADARI',
 'SANIN H.SANIP SOLO',
 'AKHMAD ALBAR',
 'DEDDY ROYADI BAC',
 'BADERUDDIN, S. SOS., MM',
 'SULAIMAN ABAS',
 'AGUSSTIN OEMAR I',
 'ASEP SUWANDI',
 'AHMAD PATAAN',
 'SYEKH NUR AWALUDIN',
 'MUHAMMAD JAWAD. (A)',
 'HAFIS ZUCHRODI',
 'PAIMAN SAPTO RAHARJO C',
 'YUDIS PERMANA',
 'BISMI HAYATI',
 'EFENDI SUSANTO',
 'PAM KKM KEDAK MAKMUR',
 'PATOLIK',
 'WAHYU ARIWIBOWO',
 'AMRUL MUKMININ/SABLON',
 'DEWIYANTO',
 'MUNDARI HASAN',
 'KODIRUL ANAM',
 'M. Z. ABIDIN/MZSTIKER',
 'AHMAD ITSNADI',
 'MOHAMAD ADI MULYONO',
 'ANGGI NURJAYANTI',
 'I KADEK KRISNA',
 'YANA SOPYANA',
 'ACHMAD KOSASSIH',
 'ROKHMAH U/PENJAHIT',
 'MOH.FEBIE PRIMA',
 'RIZAL FAHMI',
 'DRS. AHMAD TURMUDZI',
 'AMRI JAMALUDIN',
 'DRS. N. WAMBRAUW',
 'TONI MALAU',
 'ABU HAMID MASKUR RIDWAN',
 'SURONO BUET SERVASIUS 2',
 'DEDRINALDI',
 'BINTANG SUPRIYANTO',
 'SYARIF HIDAYAT IBNU JAUZI',
 'CICI IKA SRI RAHAYU',
 'SAHRIJAL',
 'MARIOS PURWADI',
 'PURWANTA INDRABAKTI',
 'ADE HARDETO',
 'DENAL',
 'TJOE HAI YEN',
 'MARCEL LAY',
 'DWI NUR HAYATI',
 'JAJANG MUHTADIN',
 'ERVIN SABAR SIANTURI',
 'BUDI EKO SETIAWAN',
 'SEPTIAN HADIONO',
 'YUNIADI EKA PRATAMA 1',
 'FETRI YENI',
 'AMIRIN',
 'I KT MANIK A PRIANTARA Y',
 'REFRIZAL',
 'NI MADE KONTASIH B',
 'PENGASAPAN IKAN SUMIATI',
 'CARTAM WIRTADIJAYA',
 'RESERVOIR MOTORIZED VALVE',
 'UTA BIN PIONG',
 'JONI SOLFRUS NENO',
 'H.R HARDJA DIDJAJA 2',
 'PONIJAN KASIYONO',
 'PAMSIMAS SARIMULYO',
 'MUHAMMAT ATHARI / BEDAK',
 'TNK KA KHAMIMAH',
 'NI KETUT WISMAYANTI',
 'DWI NINGSIH',
 'JOEKI ANNA',
 'AKHMAD.E',
 'GANDHIES DYAH PITALOKA /',
 'M ILHAM FACHRUDIN',
 'SLAMET WURYADI',
 'ILHAM S LUBIS',
 'JAUW WALUDIN IWAN',
 'MISNO RUDI',
 'AGUS KURNIAWAN, ST',
 'MUDIARTA,I NYOMAN',
 'ESTER MATANA',
 'IMAM TAUFIK.ST',
 'ROMADONA',
 'BETSY ERIA SULASTRI',
 'SANTOSO JOHAN ( A )',
 'EDI KUNTADI',
 'CANDRA WIJAYA',
 'ALDONI HASAN',
 'APRIYONAL',
 'MUHAMMAD IFTIKAAR PASHA',
 'PNPM MANDIRI SULISWANTO',
 'RAMA TAUFIK RAMADHAN',
 'DASLIM TAMBUNAN',
 'AGR SMSWH MUHAMMAD WIDODO',
 'KHO SIE KING',
 'HJ. DIANA DARMAWANTI',
 'SERI AGUSTINA MELINDA -1',
 'ARIF RUSTIAWAN NAGA',
 'DWI RANGGA SEPTIANA FAJAR',
 'H ARIF HIDAYAT',
 'H.T KARIMUDDIN',
 'JONI OFRYA',
 'ANDRUTAMA ALS ANDREW H',
 'HERI DIAN PERMANA',
 'FERA SEPTI RAHAYU 1',
 'ENDANG JATMIYATI',
 'RENDI U/KONVENSI',
 'PRANOTO LATIF',
 'I KETUT WARTA',
 'PEMBENIHAN PANGAN',
 'ANDHI HERWANTO.S.SOS',
 'ELIA AFRIANI,SE',
 'FEBRI SUBIYANTO',
 'DEBORA DEISY',
 'TIRTA BALAWARA',
 'H.AGUS SUPARMIN',
 'T SAFWAN A',
 'ELLY SUGIANTO',
 'ADI KURDI',
 'ANGELIA TANTRA',
 'SAFTA HADI',
 'APRIRIANTI',
 'MARIA MARITA KEWA',
 'DENNY SETYAWAN',
 'IBRAHIM ST MUDO',
 'FARIZ ANGGA OKTAVIAN, SH',
 'IMAM SOEROSO',
 'AN. AIDA KARTIKA SANTI',
 'FLORENSIUS ROSENO',
 'NURZADIAN',
 'WIDI HARSONO B',
 'SIAUW WIE KONG',
 'PETRUS MUSTAMU',
 'NENENG (B)',
 'MISBAH IBRAHIM',
 'SUKASAH',
 'DL SITORUS (KANTIN A',
 'YOGGIE GM',
 'RUDIAN',
 'CUT WARDATI',
 'SOFYAN S SKMMPM',
 'KOMANG SUDIANTA',
 'I WAYAN VIVI OVITA',
 'AGR SMR SAWAH YUSUF HARIS',
 'LAI BUI MIN(A)',
 'KHAIRUL ANWAR',
 'RUMADJA LUSUH',
 'DYBYO HARTONO',
 'DEDI SUNARNO',
 'ANFAL AULIYA',
 'AHMAD SAHUDI',
 'NAYI NI WAYAN',
 'T.M. DAUD AR',
 'HERU RYANTARA',
 'NI PUTU SUMETRI',
 'ONG TJHING HONG',
 'ROHMAN BASUKI',
 'PUTU GEDE WIARTHA',
 'ANOM SUJITO',
 'DWI ALDI SUKMA',
 'AGUNG WIERYANTO THEDY',
 'DEWI MURTIANI',
 'GILANG RAHADIAN M.A',
 'ANGKY PATTY',
 'DIKI PRANATA',
 'ELY DESWITA ANIS',
 'M A D I O N O',
 'JAITI',
 'YULIA ANDRIANI',
 'IRWAN ESEKTRA',
 'WAWAN AYAM',
 'RAFI DIFA ALMAS 1',
 'TRI MAYA ARINI',
 'NANI AGUSTINI',
 'HONNA',
 'NETTY NURHAYATI SIAHAAN',
 'NI MADE PUSPITAYANTI',
 'RONNY LIM',
 'THORIQ AHMAD FAUZAN',
 'YANI A44',
 'GAUNG ADAKA',
 'ERIK ISAKANDAR',
 'RUSLAN BN-9',
 'SITI SHARAH',
 'QARLINAH',
 'MUHAMMAD GIBRAN PALUPI (H',
 'NOPENDI YUPITER',
 'DIDIK SETIAWAN NAGA',
 'H SONHAJI',
 'DARMITA',
 'TUTIK LESTARI AND. KEB',
 'SLAMET AGUS SURYANI',
 'M.FAHRUDIN NOOR',
 'ELYUSRITA',
 'SANECI',
 'ACHAMD',
 'M ZULYADAINI',
 'HJ.YENI.M.SE 2',
 'IYAH, A',
 'ADI JHON',
 'TAN GIE IEN',
 'ERNAWATI.II',
 'DARTO WAHAB',
 'OTONG SYAMSUDIN',
 'JUMAIDAH',
 'ANI YATI MENARA TELOR',
 'I WAYAN LIDUG',
 'ANDI ILHAM',
 'ASMAL JUNUN',
 'SUKRI KACCA',
 'NURLELAWATI',
 'SYAEFUL ANHAR',
 'JANAR',
 'I SAFIA',
 'LUKITO SANTOSO',
 'AAM BADRUTTAMAM',
 'A HERI PURWANTO',
 'SUDIN SIBURIAN',
 'SUDIRMAN H - 2',
 'BOBBY ESA PUTRA C',
 'ENDANG DAMANHURI',
 'SITI ZUMAROTUL CHOIROH',
 'WARNET AGUS RUSMAN',
 'POMPANISASI ANSAR BASIR',
 'NENENG KUSMIATI',
 'KPU KAB. ALOR',
 'PARAHDIBA.SH',
 'AGUS RIYONO NAGA',
 'NUR IMAN,S.KOM',
 'BIDAN ERNA SUSILAWATI',
 'SUMRIYAH. I.',
 'LAW TIANG HWAT',
 'I NENGAH PARNA',
 'SUN SUMANTO',
 'H PIPIH LUTFI SPBU',
 'LAS JWS',
 'JUNAYYAH',
 'AZKIA KARET',
 'RIZMAR NAZIR',
 'JOKO WASITO.A',
 'HA DJAN NI',
 'JAMRONI / NAGA',
 'MHD.BAWA',
 'SATRIANTOS',
 'ERWAN KURNIA',
 'TASBEHUL HOER',
 'SOEPARNO,DRS',
 'MERI ELIZARNI',
 'NUR RABAIYAH',
 'RIKA YUHANA 1',
 'MASDIA II',
 'ASROPIK',
 'DRS IDA BAGUS KARYAWAN',
 'ULFAH MASPUPAH',
 'ANSOR GUNARTO',
 'MUHAMMAD ALMUHDAR',
 'MUHAMAD SLAMET MASNA',
 'IDA ATIMI',
 'ARSAD WATIA',
 'HENDRA SUNJAYA',
 'HENDRA DASLAN',
 'H NUR SOLEH',
 'PEDE CELULER',
 'DISTRIATI PAZRIAH',
 'SITI ROMLAH - 1',
 'HARMOKO SE',
 'ARIS MUGIARNO',
 'CIBI BABY SPA',
 'I.G.A.A.M. YUNIARI',
 'MAAD',
 'H KHAIRUL KAROHAN A',
 'FARIANTI LADIA',
 'RUDY PRIYANTO',
 'DANIL ABDUL SUKUR',
 'EMBUNF GERENDONG',
 'PALTI M. PASARIBU',
 'PATONAH 1',
 'SAKA MAHARIA',
 'RUDIANTO/EX B',
 'MEMED',
 'IR.HM.ADELAN ABDULLAH',
 'SOLIHATIN',
 'IMA NOR AINI',
 'DYAH NUR LAILY FATHONAH',
 'ATAN',
 'ENJANG SUKMANA',
 'H.ABDUSSAMAD NO.1',
 'DRA. KUSUM RIYATININGRUM',
 'WELLA NOFA SARI',
 'FAKHRUL KHASNI',
 'NURMAINI 2',
 'SURYA PRANDIKA',
 'IRMA BUDI LESTARI',
 'WIWIN NURYANTIH',
 'ISNUARI',
 'PAULA CANSIA UNTU 1',
 'YUZAB ANDESTA',
 'ANANG DWI WIJANARKO',
 'ASBOLAH/NAGA',
 'AGUS SUSANTO (HOTEL KADIP',
 'SIE KIM HENG. 2',
 'IBU IKA',
 'I PUTU BAYU EKA YANA',
 'NANIK JATMIKO FITRIANI',
 'ARIF VALDI SULFIANSYAH 3',
 'SUTO',
 'SUMERTA I WAYAN',
 'LOLI PIANDA',
 'ASEP FADILAH',
 'YUSUP SLAMET',
 'M.NASRULLOH',
 'ARIES DWANTORO SETYANTO',
 'TRIDES HARIYANTO',
 'MUHAMMAD NUR FATHONI',
 'IRWAN HADIANSYAH',
 'HJ. SITI SOFIAH/ TK ROTI',
 'ANTON PANDOWO',
 'DRS.T.TURNIP',
 'AMELIA BUBUT AYAM',
 'DELLY NOVIANTO N',
 'H.M.YAHYA HS',
 'YUZAB ANDESTA 1',
 'I MADE SASIH',
 'FIKI ZAKIYAH',
 'YUMADI. 2',
 'DINA WAHYU',
 'I MADE PANGGIH',
 'SUSANTY EDY LEO',
 'VIVIN YULIANA',
 'HERDINAL. 6',
 'B A I N A R',
 'GATUT SETYO WAHYUDI',
 'HJ NURSA ADAH',
 'NUR HARYANTO U KDG AYAM',
 'TOSERBA R',
 'DEDE YASIR PUTRA',
 'NILAWATI ROGAYEH, SE',
 'LUMBUBARATDMT',
 'FABIANUS NYOSAPUTRA S.2',
 'LINGGO LAKSITO',
 'EUIS SITI ROCHYAWATI',
 'RIZA ANDRAYANI',
 'DRS.EDWARD IBRAHIM',
 'RIDHO SYAHPUTRA',
 'SANDY TANDI TAPPI',
 'KHOIRUL FAHMI',
 "KHOIRUL ANNAS MA'RUF",
 'H.JAJANG SUKIAHA S.SOS 3',
 'REKA T/KERAJINAN BATU',
 'MOH. ADI',
 'LIM I LAM',
 'ASLAN SETIAWAN C08',
 'KOL R HERFIEN MS',
 'ACHMAD U/PAVLING',
 'H AHMAD PARKAN. 2',
 'IR JOHN RIZAL PURBA',
 "ADE SAFE'I",
 'KK ANEKA',
 'FITRIANI EKA DIANA SARI',
 'ARBIAH',
 'IR WIDYA PURNAMA MM',
 'PURNOMO UDMIKRO/TKSEMBAKO',
 'BACHTIAR BUSRO',
 'DAMIH MARDIANI',
 'ASLAH',
 'BERNADUS MAUBEI WATOKOLAH',
 'SITI RUKAYAH(GDG WALET)',
 'MULYADI 4',
 'H.ZULKARNAINI.S. II',
 'DYOUNGS',
 'MUSA KHOIRIYAH',
 'H.HANAFIAH 2',
 'IIS AZ ZAHRA U USAHA',
 'RESMAN TAMBA',
 'SYUPRIYANTO',
 'LOS SAIK PSR DAERAH',
 'ALNI',
 'DARSIMAH.02',
 'ESAU PARDEDE',
 'AGUS ANGGORO',
 'ALBERT B SIHOMBING',
 'TRISILO ASIH SETYAWAN',
 'MEUBEL ABDUL A',
 'CAHAYA ANUGRAH',
 'SITI DEWI AMINAH',
 'APRIJAL SE',
 'INDRA TAUFIK',
 'SRIONO',
 'ERWINSA',
 'CUA CIN PA',
 'SUSMELI',
 'TUADI',
 'ZAENAL MUTTAKIM',
 'RONNY ABADI',
 'KENOD',
 'TOHA, A.MA',
 'ISNINJAR 02',
 'MARHUMA, MS',
 'RUBBY ADHISURIA',
 'I MADE SUERKA',
 'HINSATOPA SIMATUPANG',
 'MAPUL',
 'SUGIHONO SANTOSO USLI',
 'TRI ANTO NUGROHO (1)',
 'YUYUN YUNENGSI',
 'WINARSIH / BEDAK',
 'SANUDIN B H SABIHIS',
 'ARIFIN MULJADI',
 'AMRAN AHMAD',
 'ULLIN',
 'VIVI ELVIOLA.B',
 "NURUL MU'ATIROH /NAGA",
 'ROHIM SIHOTANG',
 'BIMANTORO PURWANTO',
 'HJ. NURLIA',
 'H ASNAWI AB',
 'SURIPTO 4',
 'RISDA ANISATUN WAQIAH',
 'SUSANA W',
 'JHUAN ERLANDO PUTRA RACHM',
 'LINDYA SAMPELAN',
 'DONNA TANUWIDJAJA',
 'MAS RUSDI',
 'KIKI MEGA',
 'SUTIRAH/SUMIATUN',
 'LUKMANA',
 'VONIRAH',
 'RUSADI/JETPUMP',
 'MAR,ATI',
 'NUR KHUDRIN 1',
 'MITHA WINDIA SARI',
 'MUHAMAD MUHTAROM',
 'TEGUH MAKMUR',
 'DR. ARIF RAHMAN HUSEIN',
 'FANDI HARDIYANTO',
 'FAEYZA JAYA',
 'TITI J. GUMULILI',
 'MGS HI ABD ROHIM',
 'BELINA KOHO',
 'JUPRIYANTO PANDIN',
 'DUWI SUDARTO PUTRA',
 'NAJMIE ALJOEFRIE',
 'RISKI IRMAWATI (WR)',
 'ANJANI TEKHNIK',
 'NINIX INDRIANI',
 'KURNIATIE',
 'EGA PALAPA',
 'YOGEN SUGANDA',
 'DARMI MILE',
 'NANANG SHOLAKHUDIN',
 'SHOLIHUL HADI',
 'SITTI ASMAWATI , SE.AK',
 'H.MUAMAR AL QADRI MPD',
 'JALI BIN ARTIH',
 'EVI FEBRIANTI',
 'CUT MERYA AGUSMITA',
 'APERINUS ZAI',
 'FAJARNO NESARIS ( B)',
 'MANISO.A',
 'ILIARDI SALOMO. 01',
 'YONALDI TANDRA',
 'MOHD NASIR NYAKNIE-3',
 'IIP ERIYANI',
 'LUCY PHOA',
 'ISMANTO SENEN',
 'MIKARDENO. S. P.',
 'TARSIYAN BIN WASLI',
 'ALI MAHFUD 9',
 'DR. UDAYANTI',
 'SUPRAPTI (1)',
 'ARIS MUNANDAR SETIO ADJI',
 'HADI HIKMATULLOH',
 'MARYOLINE OCTAVINA',
 'SATYA MUDA SALIM',
 'MUDDASIR ISHAK',
 'SUNYOTO ADI H',
 'SUMIARNI NI MADE',
 'MARIO KELLY WENNO',
 'SUGIANTO P.',
 'OSKANDAR DAVID PAH 01',
 'W.SADIARKA',
 'JAMALUS MORAN',
 'SAIFUL IMAN',
 'MOHAMMAD MUNIR, S.PD',
 'SELA APRILIA',
 'NI KETUT SUATRI',
 'HAYATON 4',
 'WIRYONO BW',
 'SYAHID AFDAL ADINATA',
 'BENYAMIN SUGANDA',
 'SRI MAHARTATI',
 'ALFARINO ANTONIO',
 'RHEZA EDWARD PESIK',
 'SALIM 8',
 'PURWAHENI',
 'DEDE ARIES HIDAYATULLAH/7',
 'SITI KUNDARYATI',
 'HJ. FATIMAH JUHAIRI',
 'JANUARIZAL',
 'HENRIKA SUWARTI SUGIONO',
 'PRAYITNO HADI KARTA SH',
 'PUNAWI ( D )',
 'NUR YULIADI',
 'NY DARINAH',
 'ALI AKBAR BIN ABDULLAH',
 'DENY HARYANTO',
 'MUHAMMAD APRIL HIDAYAT',
 'FERA AGUSTINA, IR',
 'SUROSO EFENDI NAGA 2',
 'KUSWA BUDIONO',
 'APIP ROHILI',
 'SURYA YANUAR 02',
 'YENIK MARLINA',
 'NI LH SEKARNITI',
 'NARYO BIN ARIN',
 'NI NENGAH JANTEN',
 'KLIWON/PEG',
 'FIRQI ZULFAKAR',
 'BARNOTO EFFENDI',
 'SUS PRIYADI',
 ...]

In [9]:
EXTERNAL_NAMES = []

In [10]:
for name in raw_names:
    clean_name = re.sub(r'\b(DRS|DR|IR|HJ|H|ST|SE|SPD|SH)\b', '', name, flags=re.IGNORECASE).strip()
    
    parts = clean_name.split()
    if parts:
        EXTERNAL_NAMES.append(parts[0].capitalize())

In [11]:
EXTERNAL_NAMES = list(set(EXTERNAL_NAMES))

In [12]:
raw_food = df_food['product'].dropna().tolist()
raw_food

['Hot Almara Kopi (kopi Susu Gula Aren)',
 'Ice Almara Kopi (kopi Susu Gula Aren)',
 'Hot Millsis',
 'Ice Millsis',
 'Hot Millbro',
 'Ice Millbro',
 'Hot 330 Helateh',
 'Ice 330 Helateh',
 'Hot Ilusi Kopi',
 'Ice Ilusi Kopi',
 'Kopi Jelly',
 'Hot Americano',
 'Ice Americano',
 'Hot Latte',
 'Ice Latte',
 'Hot Cappucino',
 'Ice Cappucino',
 'Hot Mocacino',
 'Ice Mocacino',
 'Hot Caramel Latte',
 'Ice Frappucino',
 'Ice Caramel Latte',
 'Hot Hazelnut Latte',
 'Ice Hazelnut Latte',
 'Hot Vanilla Latte',
 'Ice Vanilla Latte',
 'Vietnam Drip',
 'Kopi Tarik',
 'Kopi Matcha',
 'Kopi Charcoal',
 'Hot Matcha',
 'Ice Matcha',
 'Hot Charcoal',
 'Ice Charcoal',
 'Hot Coklat',
 'Ice Coklat',
 'Hot Lemon Tea',
 'Ice Lemon Tea',
 'Ice Yakult Squash',
 'Kopi Beer',
 'Teh Jelly',
 'Lemon Squash',
 'Ocean Blue',
 'Chocomint',
 'Lychee Squash',
 'Chocoreo',
 'Pisang Lumer Coklat',
 'Roti Bakar',
 'Kentang Goreng',
 'Paket Ngemil 1',
 'Paket Ngemil 2',
 'Paket Ngemil 3',
 'Paket Mix Bento',
 'Paket Bento Shrimp Roll',
 'Paket Bento Ebi Furai',
 'Paket Bento Ekkado',
 'Paket Chicken Teriyaki',
 'Paket Chicken Blackpaper',
 'Paket Beff Teriyaki',
 'Paket Beff Blackpaper',
 'Paket Mie Ayam',
 'Paket Mie Ayam Bakso',
 'Paket Mie Yamin',
 'Paket Mie Yamin Bakso',
 'Hemat Berdua',
 'Hemat 1',
 'Hemat Combo 3',
 'Hemat Combo 2',
 'Hemat Combo 1',
 'Hemat Super 5',
 'Chicken Steak Pops',
 'Sirloin Steak Beef Pops',
 'Tenderloin Steak Beef Pop',
 'Chicken Crispy',
 'Tenderloin Crispy',
 'Sirloin Steak Crispy',
 'Chicken Double',
 'Sirloin Double',
 'Tenderloin Double',
 'Beef Steak',
 'Blackpepper',
 'Chicken Mushroom',
 'Chicken Pepper',
 'Sirloin Import 175 Gram',
 'Rib Eye Import 175 Gram',
 'Chicken Steak Geprek',
 'Sirloin Steak Geprek',
 'Tenderloin Steak Geprek',
 'Steak Cumi',
 'Steak Tuna Pepper',
 'Steak Tuna Mushroom',
 'Steak Dori Crispy',
 'Nasi',
 'Kuah Steak',
 'Chicken Drumstick',
 'Spaghetty',
 'Kentang Lokal',
 'Frenchfries',
 'Lemon Tea',
 'Es Tea Manis',
 'Lemon Squash',
 'Es Jeruk',
 'Teh Tawar',
 'Capucino Float',
 'Avocado Float',
 'Orange Float',
 'Milkshake Vanila',
 'Milkshake Strawberry',
 'Milkshake Coklat',
 'Milkshake Vanila Spesial',
 'Milkshake Coklat Spesial',
 'Milkshake Strawberry Spesial',
 'Orange',
 'Es Capucino',
 'Milkshake Mocca',
 'Milkshake Mocca Spesial',
 'Lemon Fresh',
 'Chicken Drumstick',
 'Tas ABUBA ( Max 5 Box )',
 'Lychee Popping Boba',
 'Peach Popping Boba',
 'Choco Volcano',
 'Oreo Fruit Blast',
 'Bread Pudding Classic',
 'Guava Juice',
 'Honeydew Juice',
 'Mango Juice',
 'Sourmint',
 'Soursop Juice',
 'Strawberry Juice',
 'Watermelon Juice',
 'Orange Juice',
 'Avocado Juice',
 'Oreo Milkshake',
 'Strawbeery Milkshake',
 'Vanilla Milkshake',
 'Chocolate Milkshake',
 'Ice Age Melt Down',
 'Lychee Tea',
 'Mojito Classic',
 'Peach Tea',
 'The Genjer',
 'The Passion',
 'Air Mineral',
 'Coca Cola',
 'Hot Chocolate',
 'Hot Lemonade',
 'Hot Tea',
 'Hot Tea Sweet',
 'Hot Lemontea',
 'Ice Chocolate',
 'Ice Lemonade',
 'Ice Tea',
 'Ice Tea Sweet',
 'Sprite',
 'Ice Lemontea',
 'Rib Eye Wagyu 4-5',
 'Rib Eye Wagyu 6-7',
 'Tenderloin Wagyu',
 'Sirloin Wagyu 4-5',
 'Sirloin Wagyu 6-7',
 'Tenderloin Local',
 'Tenderloin Nz',
 'Tenderloin Us',
 'Sirloin Nz',
 'Sirloin Us',
 'Sirloin Lokal',
 'Rib Eye Nz',
 'Rib Eye Us',
 'Lamb Chop Nz',
 'Battered Dory Fish Regular',
 'Battered Dory Spicy',
 'Salmon Steak',
 'Fish Bite Regular',
 'Fish Bite Spicy',
 'T-Bone Local',
 'T-Bone Nz',
 'Boneless Fried Chicken Regular',
 'Boneless Fried Chicken Spicy',
 'Grilled Chicken Steak',
 'Grilled Chicken Wings',
 'Chicken Pop Corn Regular',
 'Chicken Pop Corn Spicy',
 'Chicken Wings Crush Garlic',
 'Chicken Wings Crush Hot',
 'Chicken Pop Corn With Butter Rice',
 'Spaghetti Bolognese Kids Meal',
 'Grilled Meatball Vegetable & Potato',
 'Beef Patty Steak',
 'Grilled Meatball',
 'Mix Beef Rice',
 'Abuba Signature Salad',
 'Creamy Fun Fries',
 'Spicy Fun Fries',
 'Veggie Fruit Salad',
 'French Fries Original',
 'Veggie Fruit Salad With Sesame Dressing',
 'Beef Lasagna',
 'Fettuccine Carbonara',
 'Spaghetti Bolognese',
 'Sweet Corn',
 'Mix vegetables',
 'Potato Wedges',
 'Mashed Potato',
 'Mushroom Sauce',
 'Tartar Sauce',
 'Blackpepper Sauce',
 'Barbecue Sauce',
 'Lychee Popping Boba',
 'Peach Popping Boba',
 'Crunchy Vegan Fried Chicken Reg',
 'Crunchy Vegan Fried Chicken Spicy',
 'Vegan Beef Mix Rice',
 'Vegan Beef Steak',
 'Vegan Chi-Pop',
 'Vegan Chic Mix Rice',
 'Vegan Chicken Steak',
 'bakwan Sayur',
 'tempe Crispi',
 'tahu Jeletot',
 'tahu Pong',
 'risole',
 'Cireng',
 'piscok Lumer',
 'Gorengan Ubi',
 'Pisang Goreng',
 'Tape Goreng',
 'Tempe Basah',
 'Singkong Goreng',
 'Combro Ranjau',
 'Pisang Molen',
 'Loncom',
 'Lonsay',
 'Es Buah Segar',
 'Es Pukat',
 'Es Lemon Tea',
 'Es Nutri Sari,Es Cincau',
 'Es Nutri Sari,Jeruk Nipis',
 'Es Nutri Sari ,Sweet Mango',
 'Es Nutri Sari,Sweet Orange',
 'Es Nutri Sari,Sweet Guava',
 'Es Nutri Sari,Sirsak',
 'Es Nutri Sari,Jeruk Peras',
 'Es Nutri Sari,Anggur',
 'Es Nutri Sari,Leci',
 'Es Nutri Sari,Lemon Tea',
 'Es Nutri Sari,Blewah',
 'Nutri Sari,Es Rujak',
 'Es Capucino',
 'Bakso Ceker Mercon',
 'ceker Mercon',
 'Bakso Mercon',
 'Dimsum',
 'Tiam MIE',
 'TiamMie',
 'Nasi Goreng Sapi',
 'Kwetiaw Sapi',
 'Telur  CEPLOK',
 'Kwetiaw Kengci',
 'Ayam Full',
 'Nasi',
 'Ayam Dada',
 'Ayam Paha',
 'Kepala Ayam',
 'Ceker Ayam',
 'Ati Ampela Ayam',
 'Usus Ayam',
 'Ati Ampela Bebek',
 'Paha Bebek',
 'Kepala Bebek',
 'Dada Bebek',
 'Tempe',
 'Tahu',
 'Pete',
 'Peyek',
 'Kulit Ayam',
 'Sosis Kecil Bakar/ Goreng',
 'Sosis Bakar/Goreng Jumbo',
 'Sosis Bakar/Goreng Sedang Keju',
 'Sosis Bakar/goreng Sedang Lada Hitam',
 'Sosis Bakar/goreng Sedang Original',
 'lobster Bakar/goreng',
 'Cikuwa Bakar/goreng',
 'Dampling Cheese Bakar/goreng',
 'Bakso Bakar/Goreng',
 'bola Udang Bakar/Goreng',
 'CrabStik bakar',
 'Skelep Bakar/Goreng',
 'Baso Ikan bakar/goreng',
 'Bakso Salmon Bakar/Goreng',
 'Otak-otak Singapur Bakar/goreng',
 'Otak-otak Bakar/goreng',
 'udang bakar/Goreng',
 'Maklor ( Makaroni Telur)',
 'Cireng',
 'Tokoyaki  isi 5',
 'Telur Gulung Original',
 'Cilor Tusuk',
 'Telor Gulung Isi',
 'Sempol Isi 5',
 'Kaki Naga Isi 5',
 'Naget Cham  Isi 5',
 'Kentang Goreng',
 'Cilor (Aci Telor)',
 'Mielor (Mie Telur)',
 'Omlet (Mie + Telur)',
 'Martabak Telur Loyang',
 'Martabak Telur Terigu Loyang',
 'Martabak Telur Puyuh',
 'Lumpia Telor Ayam',
 'Lumpia Telor Bebek',
 'Otak-otak Kriuk',
 'Bakso Kriuk',
 'Makaroni Pedas',
 'kripik Kaca',
 'Makaroni Spiral',
 'es pop ice',
 'Es Teh Manis',
 'Es Milo',
 'Es Drink Beng-beng',
 'Aqua',
 'Es Good Day Cappucino',
 'Es Good Day Freeze',
 'Es Good Day Mocacino',
 'Dancow Panas/Dingin',
 'Indomi Kuah + Telur',
 'Indomie goreng + Telur',
 'Indomie Kuah + Bakso',
 'Indomie Soto Telur + Bakso Sosis',
 'Super Bihun Kuah Telur + Bakso',
 'Indomi Goreng Mix Ceker Mercon',
 'Indomie Goreng Mix Ceker+Bakso Mercon',
 'Indomie Soto  Telur + Ceker Mercon',
 'Otak-otak Mercon',
 'Bakso Mercon',
 'Ceker Mercon',
 'Ceker Mix Bakso Mercon',
 '275 Gr Tenderloin Beef With Truffle Sauce',
 'Chicken Croffle Truffle',
 'Single Serve Croffle with Ovomaltine',
 'Cinnamon Rolls Ovomaltine',
 'Ovomaltine Raspberry Tart',
 'Black Coffee 1 L',
 'Black Coffee 500 mL',
 'Kopi Nusantara 1 L',
 'Kopi Nusantara 500 mL',
 'Caffe Latte 1 L',
 'Caffe Latte 500 mL',
 'Almond Croissant',
 'Bacon & cheese croissant',
 'Butter croissant',
 'Choco lava croissant',
 'Nutella Pain au Chocolat',
 'Peanut butter & jelly croissant',
 'Salted egg yolk croissant',
 'Triple Cheese Croissant',
 'Truffle Mushroom croissant',
 'Garlic Cheese Bread',
 'Bacon & cheese quiche',
 'Spinach mushroom quiche',
 'Beef Pie',
 'Chicken Mushroom Pie',
 'Pain Au Raisin',
 'Pain Au Praline',
 'Vanilla Bomboloni',
 'Chocolate Brownies Bomboloni',
 'Biscoff Lotus Bomboloni',
 'Lemon Meringue Bomboloni',
 'Nutella Bomboloni',
 'Salted Caramel Bomboloni',
 'Peanut Butter & Jelly Bomboloni',
 'Strawberry Cheesecake Bomboloni',
 'Plain Croffle',
 'Cinnamon Sugar Croffle',
 'Maple Croffle',
 'Nutella Croffle',
 'Salted Caramel Croffle',
 'Biscoff Lotus Croffle',
 'Assorted Croffle Box of 8 pcs',
 'Peanut Butter & Jelly Croffle',
 'Kaya Toast Croffle',
 'Hot Espresso',
 'Hot Long Black / Americano',
 'Hot Macchiato / Piccolo',
 'Hot Cappucino / Flat White',
 'Hot Caffe Latte',
 'Hot Mocha',
 'Hot Magic',
 'Add Soy Milk',
 'Add Almond Milk',
 'Add Oat Milk',
 'Iced Americano',
 'Iced Caffe Latte',
 'Iced Caffe Latte with Vanilla Ice Cream',
 'Iced Mocha',
 'Iced Mocha with Chocolate Ice Cream',
 'Iced Matha Espresso Latte',
 'Classic Affogato',
 'Es Kopi Nusantara',
 'Kopi Nusantara Granita',
 'Loose Leaf Tea (English Breakfast, Earl Grey, Blackcurrant & Hibiscus, Lemongrass & Ginger, Chamomile, Peppermint)',
 'Matcha Latte',
 'Lychee / Peach / Strawberry Iced Tea',
 'Lemon Iced Tea',
 'Signature Chocolate',
 'Pure Orange Juice',
 'Pure Apple Juice',
 'Orange + Apple Juice',
 'Fresh Brewed Ice Tea',
 'Avocado Float',
 'Avocado Affogato',
 'Avocado with Kopi Nusantara Granita',
 'Loose Leaf Tea (Jasmine, French Vanilla, Rosebud)',
 'Triple Berry Smoothies',
 'Banana & Co Smoothies',
 'Mango Tango Smoothies',
 'Nashville Hot Chiken Wings',
 'House Fries',
 'Beef Brisket Ball',
 'Oriental Roasted Duck Bao',
 'Fried Calamari',
 'Spaghetti (Cacio e Pepe)',
 'Tagliatelle Oxtail Ragu',
 'Spagethetti Carbonara',
 'Clam Linguine',
 'Add Lobster Tail (For Mac And Cheese)',
 'Mac And Cheese',
 'Cavatelli',
 'Black Truffle Tagliarini',
 'Lasagna Verde',
 'Osso Buco Agnolotti',
 'Crab Spaghetti',
 'Charred Corn Ribs , Maple Chilli Sauce',
 'House , Parmesan',
 'Truffle Mashed Potato',
 'Asparagus , Hollandaise',
 'Creamed Or Wilted Spinach',
 'Steamed Sea Bass',
 'Balinese Fried Duck',
 'Chargrilled Cabe Ijo Short Ribs',
 'BBQ Char Siu Short Rib',
 'Nasi Goreng Gila',
 'Chargrilled Jumbo King Prawn',
 'Black Truffle Wagyu Beef Bowl',
 'Mushroom Soup',
 'Burrata',
 'Bakers Caesar',
 'New England Clam Chowder',
 'Cajun Rub Hot Smoked Salmon',
 'Buttermilk Fried Chicken Croffle',
 'Avocado Toast',
 'Bakers Breakfast',
 'Crab Omelette',
 'Scramble Egg & Foie Gras',
 'Baked Eggs',
 'Eeg Benedict',
 'Garlic Cheese',
 'Valrhona Chocolate Tart',
 'Verlhona Flourless Cake Tart',
 'Brie Caramel',
 'Pistachio Fragipane',
 'Pear Tart',
 'Peach Tart',
 'Lemon Tart',
 'Caramel Pecan',
 'Apple Tart',
 'Milk Chocolate  Hazelnut Fondant',
 'Croissant Eeg Tart',
 'Varlhona Dark Chocolate Fondant',
 'Dark Chocolate Fondant',
 'Crispy Skin Salmon',
 'Steak and Frites',
 'Half Roasted Chicken',
 'Nashville Fried Lobster & Chips',
 'Lobster Thermidor',
 'Black Angus Striploin 300gr',
 'Black Angus Ribeye 300gr',
 'Bourbon Beef & Bone Marrow Pie',
 'Black Angus Tenderloin 275gr',
 "Baker's Burger",
 'Lobster Roll',
 'Egg Sandwich',
 'Cheeseburger',
 'French Dip Roast Beef Sandwich',
 'Reuben Sandwich',
 'Elderflower Grape',
 'Berry Blast',
 'Jasmine Citrus Mojito',
 'Chamomile Strawberry Spritzer',
 'Lemongrass & Guava Sparkler',
 'Coffee Crumb Cinnamon Roll',
 'Lotus Biscoff Cinnamon Roll',
 'Choco Nutella Cinnamon Roll',
 'Peanut Nougat Cinnamon Roll',
 'Walnut Caramel Cinnamon Roll',
 'Bakmi Istimewa (3 Toppings)',
 'Bakmi Special (Bebek Peking + Ayam Kampung)',
 'Bakmi Bebek Peking',
 'Bakmi Campur (Ayam Kampung + Ayam Cincang)',
 'Bakmi Ayam Kampung',
 'Bakmi Ayam Cincang',
 'Bakmi Ayam Kampung Super Topping',
 'Bakmi Bebek Peking Super Topping',
 'Bakso Sapi 1 Porsi (10 Pcs)',
 'Bakso Sapi 1/2 Porsi (5 Pcs)',
 'Bakso Sapi (2 Pcs)',
 'Bakso Goreng',
 'Pangsit Rebus 1 Porsi (10 Pcs)',
 'Pangsit Rebus 1/2 Porsi (5 Pcs)',
 'Pangsit Rebus (2 Pcs)',
 'Bebek Peking 1 Ekor',
 'Bebek Peking 1/2 Ekor',
 'Bebek Peking 1/4 Ekor',
 'Ayam Kampung 1 Ekor',
 'Ayam Kampung 1/2 Ekor',
 'Ayam Kampung 1/4 Ekor',
 'Air Mineral 600 Ml',
 'Teh Pucuk',
 'Bakmi Rebus Kalimantan',
 'Bakmi Goreng Kalimantan',
 'Bakmi Kuah Kalimantan',
 'Bakmi Goreng Kari',
 'Bakmi Siram Kalimantan',
 'Kwetiaw Rebus Kalimantan',
 'Kwetiaw Goreng Kalimantan',
 'Kwetiaw Goreng Kari',
 'Kwetiaw Siram Kalimantan',
 'Bihun Rebus Kalimantan',
 'Bihun Goreng Kalimantan',
 'Nasi Goreng Kalimantan',
 'Nasi Goreng Kusut',
 'Nasi Goreng Singapore',
 'Nasi Goreng Kari',
 'Nasi Siram Kalimantan',
 'Nasi Telor Kalimantan',
 'Nasi Muntahu Lopui',
 'Locupan Jam',
 'Locupan Tek-Tek',
 'Pangsit Kuah Isi 5',
 'Pangsit Kuah Isi 10',
 'Pangsit Tek - Tek Isi 5',
 'Pangsit Tek - Tek Isi 10',
 'Susu Kacang 500ML',
 'Ayam Kampung Goreng Kremes',
 'Ayam Kampung Goreng Kremes + Nasi',
 'Bakso Mie Campur',
 'Bakso Soun/Bihun/Mie Kuning',
 'Bakso Spesial',
 'Bakso Kuah',
 'Bakso Urat Besar',
 'Bakso Telur',
 'Bakso Setengah Porsi',
 'Nasi Putih',
 'Mie Ayam Bakso',
 'Mie Ayam Bakso Pangsit',
 'Mie Ayam Bakso Pangsit + Urat Besar',
 'Mie Ayam Bakso Urat Besar',
 'Mie Ayam Pangsit',
 'Mie Ayam Pangsit + Urat Besar',
 'Mie Ayam',
 'Mie Ayam Bakso Telur',
 'Mie Ayam Pangsit + Bakso Telur',
 'Sop Daging Sapi',
 'Siomay',
 'Siomay Goreng',
 'Krupuk',
 'Kelapa Bulat ala Thailand',
 'Soda Susu',
 'Es Alpukat',
 'Es Kelapa Jeruk',
 'Es Alpukat Kelapa',
 'Es Campur',
 'Es Kelapa',
 'Es Jeruk',
 'Es Teh Manis',
 'Es Teh Tawar',
 'Teh Manis Panas',
 'Teh Tawar',
 'Jeruk Panas',
 'Lemon Tea',
 'Juas Buah Naga',
 'Jus Alpukat',
 'Jus Sirsak',
 'Jus Melon',
 'Jus Strawberry',
 'Jus Tomat',
 'Jus Jambu',
 'Air Mineral',
 'Coca Cola',
 'Sprite',
 'Fanta',
 'Fruite Tea',
 'Teh Botol',
 'Jus Mangga',
 'Prima Gelas',
 'Pulpy Orange',
 'Fresh Tea',
 'Happiness Bento Set 1',
 'Happiness Bento Set 2',
 'Oishii Set 1',
 'Oishii Set 2',
 'Chicken Katsu Curry Bento',
 'Chicken Karaage Nanban Bento',
 'Beef Hamburg Curry Rice',
 'Chicken Karaage Mentai Bento',
 'Cheesy Beef Cutlet Curry',
 'Fish Katsu Mentai Bento',
 'Double Hamburg Curry Rice',
 'Cheesy Hamburg Curry Rice',
 'Es Matcha Mindfulness',
 'Es Mango Yakult Jelly',
 'Es Lychee Yakult Jelly',
 'Cinnamon Roll',
 'Choco Lava Cake',
 'Dark Chocolate',
 'Tiramisu Cheesecake',
 'Chicken Karaage Curry Bento',
 'Chicken Katsu Nanban Bento',
 'Beef Teriyaki Bento',
 'Chicken Teriyaki Bento',
 'Chicken Katsu Mentai Bento',
 'Extra Cheesy Beef Cutlet Curry',
 'Cheesy Chicken Cutlet Curry',
 'Extra Cheesy Chicken Cutlet Curry',
 'Fish Katsu Nanban Bento',
 'Fish Katsu Curry Bento',
 'Hemat Set',
 'Ekkado Set',
 'Cheesy Chicken Set',
 'Chicken Katsu Set',
 'Chicken Popcorn Bento 1',
 'Chicken Popcorn Bento 2',
 'Coffee Brownie',
 'Almond Brownie',
 'Coconut Pandan',
 'Red Velvet',
 'Original Cheesecake',
 'Blueberry Cheesecake',
 'Raspberry Cheesecake',
 'Extra Sambal Sachet',
 'Extra Mayonnaise Sachet..',
 'Es Kopi Cheer Me Up',
 'Es Cokelat Cozy',
 'Es Teh Joyful',
 '1Ltr Es Kopi Cheer Me Up',
 'Mineral Water 330 Ml',
 'Es Sukur - Susu Kurma',
 'Es Cendol Ceria',
 'Coca-Cola',
 'Bakso Bakar',
 'Bakso Salmon Bakar',
 'Crabstick Bakar',
 'Dumpling Bakar',
 'Fishroll Bakar',
 'Ikan Kue Pedas Bakar',
 'Rolade Bakar',
 'Scallope Bakar',
 'Sosis Bakar',
 'Sosis Bakar Jumbo',
 'Tofu Seafood Bakar',
 'Chikuwa Bakar',
 'Otak - Otak Bakar',
 'Mie Oyeng',
 'Sosis + Kyentang Oyeng',
 'Kyentang Oyeng',
 'Sotang (Sosis Kentang) Oyeng',
 'Otak-otak Oyeng',
 'Bebek Goreng',
 'Bebek Belur Cabe Ijo',
 'Bebek Bakar Bumbu Rica',
 'Bebek Bakar Kacang',
 'Ayam Kota Goreng',
 'Ayam Kota Belur Cabe Ijo',
 'Ayam Kota Bakar Kacang',
 'Ayam Kota Bakar Rica',
 'Ayam Kampung Belur Cabe Ijo',
 'Ayam Kampung Goreng',
 'Ayam Kampung Bakar Kacang',
 'Ayam Kampung Bakar Rica',
 'Udang Goreng Tepung',
 'Cumi Goreng Tepung',
 'Cumi Tumis Cabe Ijo',
 'Udang Tumis Cabe Ijo',
 'Cumi Asin Tumis Cabe Ijo',
 'Nila Belur (Cabe Ijo)',
 'Nila Goreng.',
 'Nila Bakar Kacang',
 'Nila Bakar Rica',
 'Sayur Asem',
 'Cah Kangkung Polos',
 'Cah Kangkung Teri',
 'Cah Kangkung Seafood',
 'Terong Goreng Tepung',
 'Tumis Jamur Tiram',
 'Plencing Kangkung',
 'Telur Penyet',
 'Telur Dadar',
 'Sosis Goreng (2potong)',
 'Tahu Goreng (5potong)',
 'Tempe Goreng (5potong)',
 'Telur Bakar',
 'Sosis Bakar (2potong)',
 'Nasi A',
 'Nasi B',
 'Nasi Putih',
 'Sambal Korek',
 'Sambal Ijo',
 'Sambal Mangga',
 'Sambal Teri',
 'Sambal Terasi',
 'Sambal Terong',
 'Es Jeruk',
 'Jeruk Murni',
 'Es Lidah Buaya',
 'Es Timun',
 'Es Jeruk Nipis',
 'Es Lemon Tea',
 'Es Milo',
 'Mineral Botol',
 'Es Teh Manis',
 'Es Teh Tawar',
 'Es Alpukat Susu',
 'Jus Alpukat',
 'Teh Botol',
 'Es Kosong',
 'Es Mangga Boedjang',
 'Jus Mangga',
 'Bebek Goreng',
 'Bebek Belur Cabe Ijo',
 'Bebek Bakar Bumbu Rica',
 'Bebek Bakar Kacang',
 'Ayam Kota Goreng',
 'Ayam Kota Belur Cabe Ijo',
 'Ayam Kota Bakar Kacang',
 'Ayam Kota Bakar Rica',
 'Ayam Kampung Belur Cabe Ijo',
 'Ayam Kampung Goreng',
 'Ayam Kampung Bakar Kacang',
 'Ayam Kampung Bakar Rica',
 'Udang Goreng Tepung',
 'Cumi Goreng Tepung',
 'Cumi Tumis Cabe Ijo',
 'Udang Tumis Cabe Ijo',
 'Cumi Asin Tumis Cabe Ijo',
 'Nila Belur (Cabe Ijo)',
 'Nila Goreng.',
 'Nila Bakar Kacang',
 'Nila Bakar Rica',
 'Sayur Asem',
 'Cah Kangkung Polos',
 'Cah Kangkung Teri',
 'Cah Kangkung Seafood',
 'Terong Goreng Tepung',
 'Tumis Jamur Tiram',
 'Plencing Kangkung',
 'Telur Penyet',
 'Telur Dadar',
 'Sosis Goreng (2potong)',
 'Tahu Goreng (5potong)',
 'Tempe Goreng (5potong)',
 'Telur Bakar',
 'Sosis Bakar (2potong)',
 'Nasi A',
 'Nasi B',
 'Nasi Putih',
 'Sambal Korek',
 'Sambal Ijo',
 'Sambal Mangga',
 'Sambal Teri',
 'Sambal Terasi',
 'Sambal Terong',
 'Es Jeruk',
 'Jeruk Murni',
 'Es Lidah Buaya',
 'Es Timun',
 'Es Jeruk Nipis',
 'Es Lemon Tea',
 'Es Milo',
 'Mineral Botol',
 'Es Teh Manis',
 'Es Teh Tawar',
 'Es Alpukat Susu',
 'Jus Alpukat',
 'Teh Botol',
 'Es Kosong',
 'Es Mangga Boedjang',
 'Jus Mangga',
 'Original Topokki',
 'MozzarellaTopokki',
 'Kimmari Topokki',
 'Ganjeong Topokki',
 'Rapokki',
 'Roze Topokki',
 'Kimchi Kimbab',
 'Odeng',
 'Original Package',
 'Mozzarella Package',
 'Roze Package',
 'Sharing Package',
 'Kimchi Stir Friced Rice',
 'Bulgogi Rice',
 'A Bowl Of Rice',
 'Bulgogi Japchae',
 'Jeyuk Bokkeum',
 'Mineral Water',
 'Coke',
 'Sprite',
 'Chilsung Cider',
 'Milkis Banana',
 'Milkis Melon',
 'Milkis Milk',
 'Milkis Strawberry',
 'Lapis Original',
 'Cokelat Keju',
 'Bolu Susu Oreo',
 'Bolu Susu Red Velvet',
 'Cokelat',
 'Pandan Keju',
 'Full Talas',
 'Lapis Blackforest',
 'Brownis Glossy',
 'Black Forest Ukuran 11',
 'Black Forest Ukuran 15',
 'Red Valvet Ukuran 17',
 'Red Velvet 15',
 'Double Coklat Uk.15',
 'Lilin Magic',
 'Lilin Angka',
 'Black Forest Ukuran 17',
 'Black Forest Ukuran 19',
 'Red Velvet 11',
 'Tiramissu Uk.11',
 'Tiramissu Uk.15',
 'Tiramissu Uk.17',
 'Double Coklat Uk.11',
 'Double Coklat Uk.17',
 'Mocca Uk.11',
 'Mocca Uk.15',
 'Klepon 15',
 'Klepon 17',
 'Cake Cokelat',
 'Cake Tape',
 'Bogor Banana',
 'Kotak Cokelat',
 'Kotak Pandan',
 'Muffin Mini',
 'Donat Mini',
 'Bika Ambon',
 'Cake Pisang',
 'Cake Marmer',
 'Pisang Bolen Cokelat',
 'Cheese Stik',
 'Strudle Brownis',
 'Pisang Bolen Keju',
 'Banana Cheese Roll',
 'Swiss Roll Red Velvet',
 'Swiss Roll Cokelate Oreo',
 'Swiss Roll Keju',
 'Cream Keju',
 'Keju Susu',
 'Double Cheese',
 'Polo Cokelat Chip',
 'Strawberry Mountain',
 'Bluebarry Mountain',
 'Roti Kismis',
 'Long Cokelat',
 'Sarikaya',
 'Roti Unyil',
 'Roti Kacang Hijau',
 'Coklat Kacang',
 'Kacang Merah',
 'Kelapa Gula Malaka',
 'Long Cheese Cream',
 'Strawberry Cream',
 'Mocca',
 'Bluebarry Cheese Roll',
 'Sosis Cheese',
 'Smoke Beef',
 'Roti Pizza',
 'Coklat Roll',
 'Roti Coklat',
 'Roti Mickey',
 'Cream Coklat',
 'Kura Kura',
 'Cokelat Keju',
 'Roti Pisang',
 'Roti Bun',
 'Coklat Meksiko',
 'Coffe Caramel',
 'Abon Roll',
 'Abon Sapi',
 'Sobek Cokelat Combine',
 'Melxic Keju',
 'Melxic Coklat',
 'Sobek Sweet Cheese',
 'Sobek Smokeebeef',
 'Tawar Susu',
 'Tawar Cokelat',
 'Tawar Keju',
 'Lapis Black Forest',
 'Bogor Banana',
 'Swiss Roll Coklat Oreo',
 'Swiss Roll Keju',
 'Bolu Susu Oreo',
 'Bolu Susu Red Velvet',
 'Bika Ambon',
 'Brownies Glossy',
 'Cake Coklat',
 'Cake Marmer',
 'Cake Pisang',
 'Cake Tape',
 'Kotak Pandan',
 'Kotak Coklat',
 'Muffin Mini',
 'Swiss Roll Red Velvet',
 'Black Forest 18',

In [13]:
clean_gofood = []

In [14]:
for item in raw_food:
    item = re.sub(r'\(.*?\)', '', item).strip()
    
    short_item = " ".join(item.split()[:3]).lower()
    clean_gofood.append(short_item)

In [15]:
clean_gofood

['hot almara kopi',
 'ice almara kopi',
 'hot millsis',
 'ice millsis',
 'hot millbro',
 'ice millbro',
 'hot 330 helateh',
 'ice 330 helateh',
 'hot ilusi kopi',
 'ice ilusi kopi',
 'kopi jelly',
 'hot americano',
 'ice americano',
 'hot latte',
 'ice latte',
 'hot cappucino',
 'ice cappucino',
 'hot mocacino',
 'ice mocacino',
 'hot caramel latte',
 'ice frappucino',
 'ice caramel latte',
 'hot hazelnut latte',
 'ice hazelnut latte',
 'hot vanilla latte',
 'ice vanilla latte',
 'vietnam drip',
 'kopi tarik',
 'kopi matcha',
 'kopi charcoal',
 'hot matcha',
 'ice matcha',
 'hot charcoal',
 'ice charcoal',
 'hot coklat',
 'ice coklat',
 'hot lemon tea',
 'ice lemon tea',
 'ice yakult squash',
 'kopi beer',
 'teh jelly',
 'lemon squash',
 'ocean blue',
 'chocomint',
 'lychee squash',
 'chocoreo',
 'pisang lumer coklat',
 'roti bakar',
 'kentang goreng',
 'paket ngemil 1',
 'paket ngemil 2',
 'paket ngemil 3',
 'paket mix bento',
 'paket bento shrimp',
 'paket bento ebi',
 'paket bento ekkado',
 'paket chicken teriyaki',
 'paket chicken blackpaper',
 'paket beff teriyaki',
 'paket beff blackpaper',
 'paket mie ayam',
 'paket mie ayam',
 'paket mie yamin',
 'paket mie yamin',
 'hemat berdua',
 'hemat 1',
 'hemat combo 3',
 'hemat combo 2',
 'hemat combo 1',
 'hemat super 5',
 'chicken steak pops',
 'sirloin steak beef',
 'tenderloin steak beef',
 'chicken crispy',
 'tenderloin crispy',
 'sirloin steak crispy',
 'chicken double',
 'sirloin double',
 'tenderloin double',
 'beef steak',
 'blackpepper',
 'chicken mushroom',
 'chicken pepper',
 'sirloin import 175',
 'rib eye import',
 'chicken steak geprek',
 'sirloin steak geprek',
 'tenderloin steak geprek',
 'steak cumi',
 'steak tuna pepper',
 'steak tuna mushroom',
 'steak dori crispy',
 'nasi',
 'kuah steak',
 'chicken drumstick',
 'spaghetty',
 'kentang lokal',
 'frenchfries',
 'lemon tea',
 'es tea manis',
 'lemon squash',
 'es jeruk',
 'teh tawar',
 'capucino float',
 'avocado float',
 'orange float',
 'milkshake vanila',
 'milkshake strawberry',
 'milkshake coklat',
 'milkshake vanila spesial',
 'milkshake coklat spesial',
 'milkshake strawberry spesial',
 'orange',
 'es capucino',
 'milkshake mocca',
 'milkshake mocca spesial',
 'lemon fresh',
 'chicken drumstick',
 'tas abuba',
 'lychee popping boba',
 'peach popping boba',
 'choco volcano',
 'oreo fruit blast',
 'bread pudding classic',
 'guava juice',
 'honeydew juice',
 'mango juice',
 'sourmint',
 'soursop juice',
 'strawberry juice',
 'watermelon juice',
 'orange juice',
 'avocado juice',
 'oreo milkshake',
 'strawbeery milkshake',
 'vanilla milkshake',
 'chocolate milkshake',
 'ice age melt',
 'lychee tea',
 'mojito classic',
 'peach tea',
 'the genjer',
 'the passion',
 'air mineral',
 'coca cola',
 'hot chocolate',
 'hot lemonade',
 'hot tea',
 'hot tea sweet',
 'hot lemontea',
 'ice chocolate',
 'ice lemonade',
 'ice tea',
 'ice tea sweet',
 'sprite',
 'ice lemontea',
 'rib eye wagyu',
 'rib eye wagyu',
 'tenderloin wagyu',
 'sirloin wagyu 4-5',
 'sirloin wagyu 6-7',
 'tenderloin local',
 'tenderloin nz',
 'tenderloin us',
 'sirloin nz',
 'sirloin us',
 'sirloin lokal',
 'rib eye nz',
 'rib eye us',
 'lamb chop nz',
 'battered dory fish',
 'battered dory spicy',
 'salmon steak',
 'fish bite regular',
 'fish bite spicy',
 't-bone local',
 't-bone nz',
 'boneless fried chicken',
 'boneless fried chicken',
 'grilled chicken steak',
 'grilled chicken wings',
 'chicken pop corn',
 'chicken pop corn',
 'chicken wings crush',
 'chicken wings crush',
 'chicken pop corn',
 'spaghetti bolognese kids',
 'grilled meatball vegetable',
 'beef patty steak',
 'grilled meatball',
 'mix beef rice',
 'abuba signature salad',
 'creamy fun fries',
 'spicy fun fries',
 'veggie fruit salad',
 'french fries original',
 'veggie fruit salad',
 'beef lasagna',
 'fettuccine carbonara',
 'spaghetti bolognese',
 'sweet corn',
 'mix vegetables',
 'potato wedges',
 'mashed potato',
 'mushroom sauce',
 'tartar sauce',
 'blackpepper sauce',
 'barbecue sauce',
 'lychee popping boba',
 'peach popping boba',
 'crunchy vegan fried',
 'crunchy vegan fried',
 'vegan beef mix',
 'vegan beef steak',
 'vegan chi-pop',
 'vegan chic mix',
 'vegan chicken steak',
 'bakwan sayur',
 'tempe crispi',
 'tahu jeletot',
 'tahu pong',
 'risole',
 'cireng',
 'piscok lumer',
 'gorengan ubi',
 'pisang goreng',
 'tape goreng',
 'tempe basah',
 'singkong goreng',
 'combro ranjau',
 'pisang molen',
 'loncom',
 'lonsay',
 'es buah segar',
 'es pukat',
 'es lemon tea',
 'es nutri sari,es',
 'es nutri sari,jeruk',
 'es nutri sari',
 'es nutri sari,sweet',
 'es nutri sari,sweet',
 'es nutri sari,sirsak',
 'es nutri sari,jeruk',
 'es nutri sari,anggur',
 'es nutri sari,leci',
 'es nutri sari,lemon',
 'es nutri sari,blewah',
 'nutri sari,es rujak',
 'es capucino',
 'bakso ceker mercon',
 'ceker mercon',
 'bakso mercon',
 'dimsum',
 'tiam mie',
 'tiammie',
 'nasi goreng sapi',
 'kwetiaw sapi',
 'telur ceplok',
 'kwetiaw kengci',
 'ayam full',
 'nasi',
 'ayam dada',
 'ayam paha',
 'kepala ayam',
 'ceker ayam',
 'ati ampela ayam',
 'usus ayam',
 'ati ampela bebek',
 'paha bebek',
 'kepala bebek',
 'dada bebek',
 'tempe',
 'tahu',
 'pete',
 'peyek',
 'kulit ayam',
 'sosis kecil bakar/',
 'sosis bakar/goreng jumbo',
 'sosis bakar/goreng sedang',
 'sosis bakar/goreng sedang',
 'sosis bakar/goreng sedang',
 'lobster bakar/goreng',
 'cikuwa bakar/goreng',
 'dampling cheese bakar/goreng',
 'bakso bakar/goreng',
 'bola udang bakar/goreng',
 'crabstik bakar',
 'skelep bakar/goreng',
 'baso ikan bakar/goreng',
 'bakso salmon bakar/goreng',
 'otak-otak singapur bakar/goreng',
 'otak-otak bakar/goreng',
 'udang bakar/goreng',
 'maklor',
 'cireng',
 'tokoyaki isi 5',
 'telur gulung original',
 'cilor tusuk',
 'telor gulung isi',
 'sempol isi 5',
 'kaki naga isi',
 'naget cham isi',
 'kentang goreng',
 'cilor',
 'mielor',
 'omlet',
 'martabak telur loyang',
 'martabak telur terigu',
 'martabak telur puyuh',
 'lumpia telor ayam',
 'lumpia telor bebek',
 'otak-otak kriuk',
 'bakso kriuk',
 'makaroni pedas',
 'kripik kaca',
 'makaroni spiral',
 'es pop ice',
 'es teh manis',
 'es milo',
 'es drink beng-beng',
 'aqua',
 'es good day',
 'es good day',
 'es good day',
 'dancow panas/dingin',
 'indomi kuah +',
 'indomie goreng +',
 'indomie kuah +',
 'indomie soto telur',
 'super bihun kuah',
 'indomi goreng mix',
 'indomie goreng mix',
 'indomie soto telur',
 'otak-otak mercon',
 'bakso mercon',
 'ceker mercon',
 'ceker mix bakso',
 '275 gr tenderloin',
 'chicken croffle truffle',
 'single serve croffle',
 'cinnamon rolls ovomaltine',
 'ovomaltine raspberry tart',
 'black coffee 1',
 'black coffee 500',
 'kopi nusantara 1',
 'kopi nusantara 500',
 'caffe latte 1',
 'caffe latte 500',
 'almond croissant',
 'bacon & cheese',
 'butter croissant',
 'choco lava croissant',
 'nutella pain au',
 'peanut butter &',
 'salted egg yolk',
 'triple cheese croissant',
 'truffle mushroom croissant',
 'garlic cheese bread',
 'bacon & cheese',
 'spinach mushroom quiche',
 'beef pie',
 'chicken mushroom pie',
 'pain au raisin',
 'pain au praline',
 'vanilla bomboloni',
 'chocolate brownies bomboloni',
 'biscoff lotus bomboloni',
 'lemon meringue bomboloni',
 'nutella bomboloni',
 'salted caramel bomboloni',
 'peanut butter &',
 'strawberry cheesecake bomboloni',
 'plain croffle',
 'cinnamon sugar croffle',
 'maple croffle',
 'nutella croffle',
 'salted caramel croffle',
 'biscoff lotus croffle',
 'assorted croffle box',
 'peanut butter &',
 'kaya toast croffle',
 'hot espresso',
 'hot long black',
 'hot macchiato /',
 'hot cappucino /',
 'hot caffe latte',
 'hot mocha',
 'hot magic',
 'add soy milk',
 'add almond milk',
 'add oat milk',
 'iced americano',
 'iced caffe latte',
 'iced caffe latte',
 'iced mocha',
 'iced mocha with',
 'iced matha espresso',
 'classic affogato',
 'es kopi nusantara',
 'kopi nusantara granita',
 'loose leaf tea',
 'matcha latte',
 'lychee / peach',
 'lemon iced tea',
 'signature chocolate',
 'pure orange juice',
 'pure apple juice',
 'orange + apple',
 'fresh brewed ice',
 'avocado float',
 'avocado affogato',
 'avocado with kopi',
 'loose leaf tea',
 'triple berry smoothies',
 'banana & co',
 'mango tango smoothies',
 'nashville hot chiken',
 'house fries',
 'beef brisket ball',
 'oriental roasted duck',
 'fried calamari',
 'spaghetti',
 'tagliatelle oxtail ragu',
 'spagethetti carbonara',
 'clam linguine',
 'add lobster tail',
 'mac and cheese',
 'cavatelli',
 'black truffle tagliarini',
 'lasagna verde',
 'osso buco agnolotti',
 'crab spaghetti',
 'charred corn ribs',
 'house , parmesan',
 'truffle mashed potato',
 'asparagus , hollandaise',
 'creamed or wilted',
 'steamed sea bass',
 'balinese fried duck',
 'chargrilled cabe ijo',
 'bbq char siu',
 'nasi goreng gila',
 'chargrilled jumbo king',
 'black truffle wagyu',
 'mushroom soup',
 'burrata',
 'bakers caesar',
 'new england clam',
 'cajun rub hot',
 'buttermilk fried chicken',
 'avocado toast',
 'bakers breakfast',
 'crab omelette',
 'scramble egg &',
 'baked eggs',
 'eeg benedict',
 'garlic cheese',
 'valrhona chocolate tart',
 'verlhona flourless cake',
 'brie caramel',
 'pistachio fragipane',
 'pear tart',
 'peach tart',
 'lemon tart',
 'caramel pecan',
 'apple tart',
 'milk chocolate hazelnut',
 'croissant eeg tart',
 'varlhona dark chocolate',
 'dark chocolate fondant',
 'crispy skin salmon',
 'steak and frites',
 'half roasted chicken',
 'nashville fried lobster',
 'lobster thermidor',
 'black angus striploin',
 'black angus ribeye',
 'bourbon beef &',
 'black angus tenderloin',
 "baker's burger",
 'lobster roll',
 'egg sandwich',
 'cheeseburger',
 'french dip roast',
 'reuben sandwich',
 'elderflower grape',
 'berry blast',
 'jasmine citrus mojito',
 'chamomile strawberry spritzer',
 'lemongrass & guava',
 'coffee crumb cinnamon',
 'lotus biscoff cinnamon',
 'choco nutella cinnamon',
 'peanut nougat cinnamon',
 'walnut caramel cinnamon',
 'bakmi istimewa',
 'bakmi special',
 'bakmi bebek peking',
 'bakmi campur',
 'bakmi ayam kampung',
 'bakmi ayam cincang',
 'bakmi ayam kampung',
 'bakmi bebek peking',
 'bakso sapi 1',
 'bakso sapi 1/2',
 'bakso sapi',
 'bakso goreng',
 'pangsit rebus 1',
 'pangsit rebus 1/2',
 'pangsit rebus',
 'bebek peking 1',
 'bebek peking 1/2',
 'bebek peking 1/4',
 'ayam kampung 1',
 'ayam kampung 1/2',
 'ayam kampung 1/4',
 'air mineral 600',
 'teh pucuk',
 'bakmi rebus kalimantan',
 'bakmi goreng kalimantan',
 'bakmi kuah kalimantan',
 'bakmi goreng kari',
 'bakmi siram kalimantan',
 'kwetiaw rebus kalimantan',
 'kwetiaw goreng kalimantan',
 'kwetiaw goreng kari',
 'kwetiaw siram kalimantan',
 'bihun rebus kalimantan',
 'bihun goreng kalimantan',
 'nasi goreng kalimantan',
 'nasi goreng kusut',
 'nasi goreng singapore',
 'nasi goreng kari',
 'nasi siram kalimantan',
 'nasi telor kalimantan',
 'nasi muntahu lopui',
 'locupan jam',
 'locupan tek-tek',
 'pangsit kuah isi',
 'pangsit kuah isi',
 'pangsit tek -',
 'pangsit tek -',
 'susu kacang 500ml',
 'ayam kampung goreng',
 'ayam kampung goreng',
 'bakso mie campur',
 'bakso soun/bihun/mie kuning',
 'bakso spesial',
 'bakso kuah',
 'bakso urat besar',
 'bakso telur',
 'bakso setengah porsi',
 'nasi putih',
 'mie ayam bakso',
 'mie ayam bakso',
 'mie ayam bakso',
 'mie ayam bakso',
 'mie ayam pangsit',
 'mie ayam pangsit',
 'mie ayam',
 'mie ayam bakso',
 'mie ayam pangsit',
 'sop daging sapi',
 'siomay',
 'siomay goreng',
 'krupuk',
 'kelapa bulat ala',
 'soda susu',
 'es alpukat',
 'es kelapa jeruk',
 'es alpukat kelapa',
 'es campur',
 'es kelapa',
 'es jeruk',
 'es teh manis',
 'es teh tawar',
 'teh manis panas',
 'teh tawar',
 'jeruk panas',
 'lemon tea',
 'juas buah naga',
 'jus alpukat',
 'jus sirsak',
 'jus melon',
 'jus strawberry',
 'jus tomat',
 'jus jambu',
 'air mineral',
 'coca cola',
 'sprite',
 'fanta',
 'fruite tea',
 'teh botol',
 'jus mangga',
 'prima gelas',
 'pulpy orange',
 'fresh tea',
 'happiness bento set',
 'happiness bento set',
 'oishii set 1',
 'oishii set 2',
 'chicken katsu curry',
 'chicken karaage nanban',
 'beef hamburg curry',
 'chicken karaage mentai',
 'cheesy beef cutlet',
 'fish katsu mentai',
 'double hamburg curry',
 'cheesy hamburg curry',
 'es matcha mindfulness',
 'es mango yakult',
 'es lychee yakult',
 'cinnamon roll',
 'choco lava cake',
 'dark chocolate',
 'tiramisu cheesecake',
 'chicken karaage curry',
 'chicken katsu nanban',
 'beef teriyaki bento',
 'chicken teriyaki bento',
 'chicken katsu mentai',
 'extra cheesy beef',
 'cheesy chicken cutlet',
 'extra cheesy chicken',
 'fish katsu nanban',
 'fish katsu curry',
 'hemat set',
 'ekkado set',
 'cheesy chicken set',
 'chicken katsu set',
 'chicken popcorn bento',
 'chicken popcorn bento',
 'coffee brownie',
 'almond brownie',
 'coconut pandan',
 'red velvet',
 'original cheesecake',
 'blueberry cheesecake',
 'raspberry cheesecake',
 'extra sambal sachet',
 'extra mayonnaise sachet..',
 'es kopi cheer',
 'es cokelat cozy',
 'es teh joyful',
 '1ltr es kopi',
 'mineral water 330',
 'es sukur -',
 'es cendol ceria',
 'coca-cola',
 'bakso bakar',
 'bakso salmon bakar',
 'crabstick bakar',
 'dumpling bakar',
 'fishroll bakar',
 'ikan kue pedas',
 'rolade bakar',
 'scallope bakar',
 'sosis bakar',
 'sosis bakar jumbo',
 'tofu seafood bakar',
 'chikuwa bakar',
 'otak - otak',
 'mie oyeng',
 'sosis + kyentang',
 'kyentang oyeng',
 'sotang oyeng',
 'otak-otak oyeng',
 'bebek goreng',
 'bebek belur cabe',
 'bebek bakar bumbu',
 'bebek bakar kacang',
 'ayam kota goreng',
 'ayam kota belur',
 'ayam kota bakar',
 'ayam kota bakar',
 'ayam kampung belur',
 'ayam kampung goreng',
 'ayam kampung bakar',
 'ayam kampung bakar',
 'udang goreng tepung',
 'cumi goreng tepung',
 'cumi tumis cabe',
 'udang tumis cabe',
 'cumi asin tumis',
 'nila belur',
 'nila goreng.',
 'nila bakar kacang',
 'nila bakar rica',
 'sayur asem',
 'cah kangkung polos',
 'cah kangkung teri',
 'cah kangkung seafood',
 'terong goreng tepung',
 'tumis jamur tiram',
 'plencing kangkung',
 'telur penyet',
 'telur dadar',
 'sosis goreng',
 'tahu goreng',
 'tempe goreng',
 'telur bakar',
 'sosis bakar',
 'nasi a',
 'nasi b',
 'nasi putih',
 'sambal korek',
 'sambal ijo',
 'sambal mangga',
 'sambal teri',
 'sambal terasi',
 'sambal terong',
 'es jeruk',
 'jeruk murni',
 'es lidah buaya',
 'es timun',
 'es jeruk nipis',
 'es lemon tea',
 'es milo',
 'mineral botol',
 'es teh manis',
 'es teh tawar',
 'es alpukat susu',
 'jus alpukat',
 'teh botol',
 'es kosong',
 'es mangga boedjang',
 'jus mangga',
 'bebek goreng',
 'bebek belur cabe',
 'bebek bakar bumbu',
 'bebek bakar kacang',
 'ayam kota goreng',
 'ayam kota belur',
 'ayam kota bakar',
 'ayam kota bakar',
 'ayam kampung belur',
 'ayam kampung goreng',
 'ayam kampung bakar',
 'ayam kampung bakar',
 'udang goreng tepung',
 'cumi goreng tepung',
 'cumi tumis cabe',
 'udang tumis cabe',
 'cumi asin tumis',
 'nila belur',
 'nila goreng.',
 'nila bakar kacang',
 'nila bakar rica',
 'sayur asem',
 'cah kangkung polos',
 'cah kangkung teri',
 'cah kangkung seafood',
 'terong goreng tepung',
 'tumis jamur tiram',
 'plencing kangkung',
 'telur penyet',
 'telur dadar',
 'sosis goreng',
 'tahu goreng',
 'tempe goreng',
 'telur bakar',
 'sosis bakar',
 'nasi a',
 'nasi b',
 'nasi putih',
 'sambal korek',
 'sambal ijo',
 'sambal mangga',
 'sambal teri',
 'sambal terasi',
 'sambal terong',
 'es jeruk',
 'jeruk murni',
 'es lidah buaya',
 'es timun',
 'es jeruk nipis',
 'es lemon tea',
 'es milo',
 'mineral botol',
 'es teh manis',
 'es teh tawar',
 'es alpukat susu',
 'jus alpukat',
 'teh botol',
 'es kosong',
 'es mangga boedjang',
 'jus mangga',
 'original topokki',
 'mozzarellatopokki',
 'kimmari topokki',
 'ganjeong topokki',
 'rapokki',
 'roze topokki',
 'kimchi kimbab',
 'odeng',
 'original package',
 'mozzarella package',
 'roze package',
 'sharing package',
 'kimchi stir friced',
 'bulgogi rice',
 'a bowl of',
 'bulgogi japchae',
 'jeyuk bokkeum',
 'mineral water',
 'coke',
 'sprite',
 'chilsung cider',
 'milkis banana',
 'milkis melon',
 'milkis milk',
 'milkis strawberry',
 'lapis original',
 'cokelat keju',
 'bolu susu oreo',
 'bolu susu red',
 'cokelat',
 'pandan keju',
 'full talas',
 'lapis blackforest',
 'brownis glossy',
 'black forest ukuran',
 'black forest ukuran',
 'red valvet ukuran',
 'red velvet 15',
 'double coklat uk.15',
 'lilin magic',
 'lilin angka',
 'black forest ukuran',
 'black forest ukuran',
 'red velvet 11',
 'tiramissu uk.11',
 'tiramissu uk.15',
 'tiramissu uk.17',
 'double coklat uk.11',
 'double coklat uk.17',
 'mocca uk.11',
 'mocca uk.15',
 'klepon 15',
 'klepon 17',
 'cake cokelat',
 'cake tape',
 'bogor banana',
 'kotak cokelat',
 'kotak pandan',
 'muffin mini',
 'donat mini',
 'bika ambon',
 'cake pisang',
 'cake marmer',
 'pisang bolen cokelat',
 'cheese stik',
 'strudle brownis',
 'pisang bolen keju',
 'banana cheese roll',
 'swiss roll red',
 'swiss roll cokelate',
 'swiss roll keju',
 'cream keju',
 'keju susu',
 'double cheese',
 'polo cokelat chip',
 'strawberry mountain',
 'bluebarry mountain',
 'roti kismis',
 'long cokelat',
 'sarikaya',
 'roti unyil',
 'roti kacang hijau',
 'coklat kacang',
 'kacang merah',
 'kelapa gula malaka',
 'long cheese cream',
 'strawberry cream',
 'mocca',
 'bluebarry cheese roll',
 'sosis cheese',
 'smoke beef',
 'roti pizza',
 'coklat roll',
 'roti coklat',
 'roti mickey',
 'cream coklat',
 'kura kura',
 'cokelat keju',
 'roti pisang',
 'roti bun',
 'coklat meksiko',
 'coffe caramel',
 'abon roll',
 'abon sapi',
 'sobek cokelat combine',
 'melxic keju',
 'melxic coklat',
 'sobek sweet cheese',
 'sobek smokeebeef',
 'tawar susu',
 'tawar cokelat',
 'tawar keju',
 'lapis black forest',
 'bogor banana',
 'swiss roll coklat',
 'swiss roll keju',
 'bolu susu oreo',
 'bolu susu red',
 'bika ambon',
 'brownies glossy',
 'cake coklat',
 'cake marmer',
 'cake pisang',
 'cake tape',
 'kotak pandan',
 'kotak coklat',
 'muffin mini',
 'swiss roll red',
 'black forest 18',
 'double chocolate 16',
 'double chocolate 18',
 'red velvet 12',
 'tiramisu 12',
 'tiramisu 16',
 'black forest 12',
 'black forest 16',
 'bf 20',
 'cupcake',
 'double chocolate 12',
 'mocca 12',
 'mocca 16',
 'rainbow cake',
 'red velvet 16',
 'red velvet 18',
 'tiramisu 18',
 'donat mini',
 'donat kentang',
 'cokelat',
 'cokelat keju',
 'full talas',
 'original keju',
 'pandan keju',
 'lilin magic',
 'lilin angka',
 'cheese stick',
 'pisang bolen cokelat',
 'strudel brownies',
 'almond pastry',
 'banana cheese roll',
 'pisang bolen keju',
 'roti abon roll',
 'roti abon sapi',
 'roti pizza',
 'roti smoked beef',
 'roti sosis keju',
 'roti blueberry mountain',
 'roti cokelat',
 'roti cokelat roll',
 'roti cream coklat',
 'roti cream keju',
 'roti double cheese',
 'roti kacang hijau',
 'roti kelapa gula',
 'roti kismis',
 'roti long cheese',
 'roti long cokelat',
 'roti mickey',
 'roti polo chip',
 'roti sarikaya',
 'roti strawberry cheese',
 'roti blueberry cheese',
 'roti chocobun',
 'roti coffe caramel',
 'roti cokelat kacang',
 'roti cokelat keju',
 'roti cokelat mexico',
 'roti kacang merah',
 'roti keju susu',
 'roti kura-kura',
 'roti mocca',
 'roti pisang cokelat',
 'roti strawberry mountain',
 'roti unyil',
 'roti vanilla',
 'roti melxic cokelat',
 'roti melxic keju',
 'roti sobek smoked',
 'roti sobek sweet',
 'roti sobek chocolate',
 'roti tawar cokelat',
 'roti tawar keju',
 'roti tawar susu',
 'brobagi 1 -',
 'brobagi 2 -',
 'brobagi 3 -',
 'the brothers',
 'the cheesy chicken',
 'the chicken burger',
 'best of chicken',
 'the o.g. chicken',
 'asian chicken burger',
 'she caught ol',
 'chicago beef burger',
 ...]

In [16]:
raw_prod = df_prod['product_name'].dropna().tolist()
clean_prod = []

In [17]:
clean_prod

[]

In [18]:
for item in raw_prod:
    item = str(item).split('-')[0].strip()
    
    short_item = " ".join(item.split()[:3]).lower()
    clean_prod.append(short_item)

EXTERNAL_ITEMS = list(set(clean_gofood + clean_prod))

In [19]:
EXTERNAL_ITEMS

['coockies and cream',
 'mlcc 220 22pf',
 'lapis',
 'sony kd85x80l',
 'intel 2 telur',
 'ice mocchacino',
 'roti bunting mac',
 'ontbijtkoek loaf',
 'mexican boy',
 'selai srikaya tk',
 'astacala ice',
 'white medium',
 'tipker coklat pisang',
 'es rumput laut',
 'seblak puyu',
 'siomay bandung',
 'xundd case magnetic',
 'french fries +',
 'selai hazelnut crispy',
 'garlic cheese',
 'rujak serut',
 'biscoff cake',
 'mie kuah spesial',
 'passion fruit tea',
 'chicken cheeseburger',
 'roti bakar silverqueen',
 'traktirdiver-mu',
 'coffee jelly',
 'aren latte',
 'cinnamon ginger lemonade',
 'fried prawn youtiao',
 'ikan sambal dabu-dabu',
 'sambal rica-rica',
 'nutrisari sweet mango',
 'mamasuka saus sambal',
 'coklat muffin',
 'cap cai polos',
 'all variant',
 'kopi ngunjuk panas',
 'donat siram strawberry',
 'istimewa campur keju',
 'isi vanila',
 'cheese burger +',
 'brownies choco peanut',
 'tiga rasa',
 'garlic beef du',
 'kepiting mix udang',
 'seafood pasta',
 'mie udang kering',
 'chicken wings salty',
 'melted cheese',
 'zesty chicken tikka',
 'peanut butter balls',
 'crospy 10 pcs',
 'bihun gr 369',
 'popcorn chicken',
 'original topokki',
 'choco madness',
 'j. caramel popcorn',
 'mlcc 471 470pf',
 'ikan gurami tauco',
 'bento special 3',
 'mongkey burger',
 'money counter alat',
 'banana coffe',
 'pistachio balls -',
 'hawaii tea',
 'paket 6',
 'hioshi /500gram/paku beton/putih/galvanis/baja/tembok/',
 'kerupuk seblak',
 'nasi ayam lava',
 'roti kurma',
 'paket bento f',
 'truffle chicken mentai',
 'coffee lemonade',
 'tabbouleh',
 'biocalci 72 non',
 'screening jantung advance',
 'kani tobiko roll',
 'pangsit',
 'beff masrom',
 'jus alpulat susu',
 'bakwan ayam 10pcs',
 'dimsum goreng lumpia',
 'chocolover',
 'dimsum siewmay udang',
 'mango',
 'lg gcfb47ffqab',
 'pari sambal',
 'ceker recheese refftwo',
 'dodol vanila pelastik',
 'strawberry cheese bubble',
 'joyko mesin laminating',
 'ice latte melonkolis',
 'pisang goreng biasa',
 'onion garlic cracker',
 'cheesy fries large',
 'strawberry sweet',
 'kacang tojin original',
 'samcan rejeki 150gr',
 'seblak mie baso',
 'yaki edamame',
 'sayur taucho',
 'kickgo deker anak',
 'salam gift box',
 'chicken katsu set',
 'oppa bite',
 'es susu dancaw',
 'taro cookies cream',
 'bts',
 'salad ayam cincang',
 'selada romain',
 'toast dip in',
 'thai tea green',
 'avocado salted caramel',
 'air purifier sharp',
 'korean rainbow yogurt',
 'kerapu steam kecap',
 'sup kaldu',
 'sando biscuit butter',
 'ice cream vanilla',
 'blend ice tiramisu',
 'cake agar agar',
 'hot cheese milk',
 'ac lg h09tn4',
 'bbq beef rasher',
 'end plate untuk',
 'glass sudah oca',
 'bensu drink mangga',
 'roti cane coklat',
 'chiffon cake chocolate',
 'sundelbolong',
 'combo nonton komplit',
 '2 kombinasi small',
 'voted padel quarter',
 'lapis surabaya bulat',
 'asam kaktus',
 'cheeseburger xl',
 'katetong keju',
 'bakso mercon kecil',
 'iced gula aren',
 'tteoboki original',
 'choco hazelnut pearl',
 'passion fruit',
 'martabak coklat',
 'hot & spicy',
 'roti bakar kampung',
 'baso aci. baso',
 'indomie double tek-tek+telor',
 'thai tea chocho',
 'valrhona chocolate tart',
 'kiwi tea',
 'bakso ikan goreng',
 'es ceria',
 'sushi cheesy lover',
 'birthday greetings topper',
 'iced cheezo premium',
 'mukbang grat 8',
 'iced virgin mojito',
 'roti manis kosong',
 'topping prawn',
 'bakso',
 'tcs',
 'dips: creamy ranch/',
 'cake meses premium',
 'awal tahun 5',
 'paket triple collagen',
 'chicken nugget yasaka',
 'mi-shake strawberry',
 'gurami panggang bumbu',
 'rocket 1',
 'nasi wader penyet',
 'mie original level',
 'teh hijau tarik',
 'chicken blackpepper ball',
 'melon lime',
 'toumiao bawang putih',
 'raspberry sorbet',
 'es sirup susu',
 'ottoke kupiko',
 'spicy chicken burger',
 'mie gragas kobong',
 'lilin angka 4',
 'istimewa jagung manis',
 'beef teriyaki rice',
 'food chopper mitochiba',
 'roti kacang merah',
 'hokkien mie bihun',
 'fried egg',
 'ikan mujaer',
 'freestea 500ml apple',
 'kopi gosong',
 'gendon egg',
 'pangsit rebus 1',
 'keluarga 12',
 'sayur gulai',
 'cup cake chocolate',
 'bakso ayam',
 'tripple salty croffle',
 'dolce coffee',
 'spotec running zsoka',
 'es kosong',
 'klappertaart original',
 'healty spicy mobu',
 'sosis',
 'milkshake milo',
 'ice lemona americano',
 'baso aci dunpling',
 'roti kukus butter',
 'choco caramel m',
 'milk shake mango',
 'cireng crispy',
 'iga penyet',
 'asam manis ayam',
 'pastry keju',
 'lapis kukus klepon',
 'burger daging sapi+',
 'lontong cap gomeh',
 'cumi kukus dan',
 'dynamite roll',
 'lecy squash',
 'lava jumbo kua',
 'red velvet milk',
 'mozzarellatopokki',
 'legrand steker ac',
 'max tea teh',
 'lemon earl grey',
 'ma ling',
 'bicopi chocolate greentea',
 'markisa 1ltr',
 'c11. kappa maki',
 'panzerotti smoked beef',
 'loyang besar ayam',
 'robot rt25 powerbank',
 'set kaya butter',
 'resin lolipop warna',
 'penting happy green',
 'roti cane',
 'sop buntut',
 'ikea sunnersta pengait',
 'pia madu regular',
 'lucky sunday chocolate',
 'coconut almond',
 'taro milk bubble',
 'es krim double',
 'remot control 1',
 'kopi jahe',
 'a mission to',
 'expresso double',
 'nila sambal ijo+lalapan',
 'nongki rame',
 'toples container 1000ml',
 'gado-gado padang',
 'extra topping mozzarella',
 'kambing',
 'barbeque',
 'lementea',
 'deal 4',
 'ondansetron hcl dihydrate',
 'coffee float',
 'robika special strong',
 'selai peanut butter',
 'choco cheese',
 'cocopandan squash',
 'cireng isi ayam',
 'roti tawar gandum',
 'tubruk',
 'kue pancong keju',
 'ice caffee latte',
 'hasston semprotan air',
 'bihun goreng/kuah spesial',
 'crispy beef',
 'pancong nanas +',
 'seliter kezegeran 1',
 'bakmie goreng/kuah udang',
 'mie goreng hijau',
 'red velvet',
 'sedaap cup mie',
 'es nyoklat',
 'ayam paha bawah',
 'mie hun kuah',
 'vexor luminary lampu',
 'hot matcha',
 'chicken wings korean',
 'mst pahat bubut',
 'sasa tepung pisang',
 'krave signature sandwich',
 'daging paha babi',
 'hot stmj',
 'biscoff lotus bomboloni',
 'madeleine box 5pcs',
 'beef barbeque',
 'topping tiramisu',
 'bluder paulus',
 'snack pack 2',
 'choco pop',
 'ebisu sushi',
 'mie tiaw sea',
 'chicken ham',
 'gateau chocolate bar',
 'happyfit long resistance',
 'paket 5 bowls',
 'yakult kiwi',
 'roasted hazelnut cookies',
 'nasi ayam kentucy',
 'badak susu',
 'kaya toast croffle',
 'bicycle chain lube',
 'add almond milk',
 'paket chicken teriyaki',
 'smoked chicken ball',
 'tahu susu pandan',
 'new choco cashew',
 'asinan mangga mengkal',
 'udang tauco +',
 'ice avocado coffee',
 'vizz baterai advan',
 'kopi baileys',
 'bakso rusuk +',
 'via / whole',
 'choco milkshake',
 'kentang gr',
 'juice durian',
 'aqua botol 1500ml',
 'chocoquick',
 'keciput',
 '1 liter java',
 'penyetan tahu tempe',
 'kyoto vanilla latte',
 'awal tahun 3',
 'babat hitam',
 'hemat twingz rice',
 'dori telor asin',
 'sate sinchan',
 'betagen',
 'ice greentea latte',
 'soba mie ayam',
 'sausage roll',
 'paket mix 6',
 'mocha frappuccino',
 'sfidn fits hijau',
 'freshtea',
 'danish',
 'bakmi goreng/kuah sosis',
 'tawar gandum kecil',
 'nasi bebek goreng',
 'ifumie goreng biasa',
 'katsubushi 50gr',
 'chicken burger crispy',
 'risol ayam saos',
 'roti bunting 1',
 'avocado chocola-tea free',
 'angkak kapsul (red',
 'whole pesto',
 'filling chill box',
 'sosoft deterjen cair',
 'mie ayam wings',
 'brownies banana bread',
 'j. salty popcorn',
 'semangat mangkokkuxkanzler',
 'freesub',
 'bbq chicken',
 'kebab double beef',
 'cheese donut',
 'smoked beef ham',
 'ikan wader tanpa',
 'chicken milanese melt',
 'kwetiaw goreng daging',
 '153 polyester film',
 'jeruk panas',
 'cotton candy',
 'sup',
 'cafe latte caramel',
 'xiaomi redmi 15c',
 'le minerale 600ml',
 'lumpsang dengan glaze',
 'municipal wings',
 'ayam ras penyet',
 'swiss roll loaf',
 'nasi goreng mawut',
 '1xtakoyaki crab, 1xtakoyaki',
 'manisan manalagi 250',
 'kopi cincau cold',
 'siomay daging 3pcs',
 'gold digger',
 'kani fried sushi',
 'gula merah',
 'gembung',
 'luwak tubruk',
 'butter chicken rice',
 'ketan item kelapa',
 'fluffy iced red',
 'dalgona nutrisari',
 'chocolatos',
 'cadburry large!',
 'genmaicha ice',
 'bolu lapis coffe',
 'molen pisang plus',
 'roti kulit',
 'prata with sugar',
 'thai spicy manggo',
 'milo o hot',
 'capcai m',
 'smoothie popping strawberry',
 'banana serasel',
 'bubble gum mojito',
 'sweet cheese croisant',
 'tokyo banana',
 'ramen tori paitan',
 'software program kasir',
 'sup kembang tahu',
 'masker sensi kn95',
 'pork belly samcan',
 'es matcha latte',
 'bakso tumis doweeeeer',
 '10pcs 68nf 683',
 'durian keju',
 'sambal goreng udang',
 'guribee layers twinpack',
 'udang goreng mentega',
 'mie kroyok teman',
 'susu kedelai',
 'hot ovaltine',
 'crispy chicken paha',
 'vanilla custard crispy',
 'toping ceker',
 'extra daging kebab',
 'lem pvc isarplas',
 'bothok tawon',
 'bolu tape',
 'kebab teju',
 'zensoderm cream isi',
 'hand warmer penghangat',
 'spero deionized water',
 'tipis kering delfi',
 'bakso bakar 3',
 'vanilla corn flakes',
 'es caramel coklat',
 'choco roll',
 'choco walnut cookies',
 'kacang madu 200',
 'yakult mix lemon',
 'new kaos /',
 'sambal per porsi',
 'baso aci fish',
 'chicken mushroom',
 'kue pancong chocomaltine',
 'aqua ac 0.5',
 'ice mocacino',
 'cheese bites',
 'bcw wins phoenix',
 'double jus naga',
 'es lemon',
 'cappucino hazulnut panas',
 'kwatiaw jamur',
 'brocoli tumis seafood',
 'strawberry mojito 16oz',
 'oppa kribo',
 'cutleries set',
 'bundle beef creamy',
 'ice tea original',
 'vanilla cold',
 'brastomolo',
 'ayam bakar +',
 'banana milk',
 'cake combinasi besar',
 'beef roll',
 'roti maryam green',
 'masker evo plusmed',
 'bolu gulung mocca',
 'paket lubis 2',
 'hot lemontea',
 'nasi manyung telor',
 'mix kripik basreng',
 'iced sanger arabica',
 'ice coffe latte',
 'lg led 86up8000',
 'jegar jelly chrysanthemum',
 'deluxe cheese large',
 'toshiba vhh85mn',
 'original 3 pcs',
 'ayam geprek keju',
 'strawberry sweet cake',
 'ayam cha jamur',
 'smooked beef isi',
 'nasi goreng beef',
 'nasi goreng honje',
 'chamomile strawberry spritzer',
 'old fashion lemonade',
 'ac toshiba ras09j2kg',
 'telur negeri 10',
 'oval coklat',
 '3 pcs dadar',
 'ice kopi vietnam',
 'white truffle praline',
 '2 cup mentai',
 'pop ice vanilla',
 'nasi chicken salted',
 'minicake blueberry',
 'milo machiato',
 'bakso aci kuah',
 'hazelnut signature chocolate',
 'bakso lava .poyo',
 'gree gwc05moo5s ac',
 'chiken teriyaki',
 'umpan pancing kinoy',
 'matcha latte mambo',
 'teh jus apel',
 'chocolate layer bread',
 'susu latte',
 'jus melon jumbo',
 'orange tea',
 'hot dog komplit',
 "it'zrikaya",
 'muffin chocolate',
 'bakso ikan',
 'iced vanilla fruity',
 'sarung tangan biliar',
 'thaitea',
 'spaghetti chicken parmigiana',
 'herbal egg',
 'oreo cookies',
 'sirsak blueocean mix',
 'nasi ayam kampung',
 'fruits streusel pie',
 'nasi nila tauco',
 'dakui + ocha',
 'paket hemat 2',
 'corndog mozarella capucino',
 'roma 2',
 'salmon mentai roll',
 'rock n roll',
 'coffe boba brown',
 'sausage ramen',
 'cake topper',
 'c5. tako sushi',
 'regal coffee',
 'tepung terigu kunci',
 'chiken katsu bento',
 'iced chocolatenut',
 'animal style fries',
 'hamtaro cheese',
 'fruit strusel pie',
 'lychee yakukt',
 'coffee klepon coconut',
 'gramoxone 276 sl',
 'risol ayam original',
 'roti burger ayam',
 'chocolate cincau cold',
 'caramel praline macchiato',
 'classic cheddar',
 'butter chicken ala',
 'kail pancing milano',
 'paket hemat 1',
 'scrambled eggs',
 'teh hijau',
 'toping meses',
 'event desk /',
 'milo susu telur',
 'nasi gurih matasapi',
 'honey americano',
 'etoricoxib novell 60',
 'akurat test kehamilan',
 'iga konro bakar',
 'ojeg malam',
 'bundle joy 1',
 'sate cecek bakar',
 'ocean mystic',
 'omelette mie mozarella',
 'semen gresik 50kg',
 'peanut butter &',
 'cokelat keju',
 'nasi campur ayam',
 'buffalo chicken wings',
 'green tes frappe',
 'pandan kaya rm',
 'dawet durian hitam',
 '1 liter es',
 'venom ballistix 5',
 'cetak voucher custom',
 'milk shake coffee',
 'salmon tempura floss',
 'fire flying chicken',
 'small',
 'manjog ra-tteo 3',
 'mie pecel',
 'roti tawar mini',
 'baby crab says',
 'decathlon oxelo set',
 'tahu + tempe',
 'special truffle large',
 'milo tarik',
 'mocha mi-shake',
 'cumi asin tumis',
 'strawberry refresher',
 'pisang goreng nutela',
 'matcha ginger',
 'biscoff white chocolate',
 'vanilla gelato',
 'samsung rt20farwdsa',
 'strasse bike shampoo',
 'nutella skippy',
 'fruits white zebra',
 'meatball spicy',
 'hot bubble coffee',
 'industrial surface mounting',
 '1x tako sosis',
 'yakult 1 pcs',
 'crepes tiramisu coklat',
 'chiffon pandan slice',
 'roti ksr',
 'shawarma sedang komplit',
 'paket 3 sedep',
 'salmon mentaiko rice',
 'topping coklat 1',
 'nasi sayur wong',
 'pu marquisa fresh',
 'agilio olio tuna',
 'teh pahit',
 'coffee c iced',
 'kopi bungkus',
 'kopi susu vanilla',
 'caramel milkshake',
 'firecast | tas',
 'pilotter pro gloves',
 'es tea manis',
 'roti mahkota/ring',
 'spicy tuna with',
 'flimty mangga mango',
 'pentol 24pcs',
 'strawberry pocky dessert',
 'zuna gloves x',
 'kr asam manis',
 'hot vanilla',
 'nasi goreng baso',
 'nasi ayam kulit',
 'daging babi kapsim',
 'poached egg',
 'storobery smothis',
 'roti long cheese',
 'rame-rame biryani iga',
 'beef sausage bbq',
 'pegangan kawat kabel',
 'v60',
 'yeoja',
 'manggo pearl',
 'timurasa bubuk cokelat',
 'es coklat buco',
 'soup buah',
 'paket small',
 'tuna puff',
 'ayam karamel gurih',
 'juice alpokat',
 'americano panas',
 'cokelat',
 'coocaa smart tv',
 'bakso kecil',
 'kabel pematik remote',
 'nutella skippy cheese',
 'caramel cream latte',
 'cake chiffon cokelat',
 'paket rani 1',
 'abon sapi',
 'beer jawa',
 'bundaberg passion fruit',
 'chicken cheese roll',
 'keicak',
 'family box for',
 'sourdough',
 'nasi goreng full',
 'seblak baper',
 'mango chocolate cake',
 'crispy nori',
 'paket nasi tahu',
 'srikaya butter set',
 'tamie cap cay',
 'changhong ac 1/2',
 'nutrisari panas /',
 'ikan cucut fillet',
 'bicopi chocolate chesse',
 'ongkos pasang senar',
 'milky melon',
 'moicik karage blackpepper',
 'teh susu oreo',
 'bluder gold cheese',
 'bihun balap biasa',
 'teh susu dingin',
 'biasa ayam',
 'paha bebek',
 'mango oat factory',
 'baguette 30cm',
 'farbivent cairan inhalasi',
 'cataflam 50mg 1',
 'vacuum bag 3d',
 'pocai telor 2',
 '500gr udang lovely+gratis',
 'fresh pomello',
 'seblak bandung netizen+pilus',
 'mie kuning siram',
 'dextone gasket silicon',
 'cheese choco toast',
 'nila',
 'beef bowl',
 'leci yakult',
 'pisang sunpride cengkeh',
 'sweetberry ice',
 'udang ramebox',
 'krispy barbar ala',
 'sambal hijau',
 'ceker super doweeeeeeer',
 'lilin angka 9',
 'mie ayam bakso/telur',
 'smoked ham beef',
 'cheese loaf',
 'add mango chunk',
 'cappucino caramel dingin',
 'tawar',
 'lumpia salmon gragas',
 'sepatu voli junior',
 'robot rt32 30000mah',
 'mie aceh goreng',
 'orenji',
 'kalibre dry bag',
 'mie aceh cemek',
 'pancake',
 'ayam rendang/ potong',
 'su - ma',
 'hydrocortisone kalbe farma',
 'topping siomay gurilem',
 'le minerale',
 'roll brulee',
 'danish beef potato',
 'plankon ramen',
 'choco and cheese',
 'taro oreo',
 'tiramissu uk.11',
 "decathlon oxelo men's",
 'ikan sambal/ potong',
 'frisian flag omela',
 'cha sawi putih',
 'beras merah sosoh',
 'nutealla',
 'herlean herwell kapsul',
 'compression fitting nepel',
 'katsu hot recheese',
 'cup bra segitiga',
 'strawberry mix lemon',
 'choco leci',
 'soda cola',
 'rosang',
 'mata gerinda amplas',
 'veggie anselmo',
 'electrolux ews98262wa',
 'pinkyy',
 'curry chicken',
 'hot signature chocolate',
 'creme brulee',
 'combo fire flying',
 'roti gulung nanas',
 '1 kopi baileys',
 'paket bomboloni',
 'rappokki',
 'happyfit aeri lightweight',
 'ngibab 4',
 'puding cup',
 'popcorn caramel medium',
 'baso frozen varian',
 'sei ayam longboard',
 'imboost force fct',
 'roti bunting sobakso',
 'couple bundle',
 'cah toge +',
 'baso cumi',
 'beef black papper',
 'legrand mallia sense',
 'bodymaster samsak tinju',
 'kopi gula aren',
 'jumbo truffle gyudon',
 'nasi jasio',
 'paket 1 sedep',
 'paket pizza small',
 'oval keju',
 'sambal goreng tempe',
 'dada geprek +',
 'kani cheese sushi',
 'paket i',
 'paket ber 2',
 'cheese sauce',
 'alltrek alas duduk',
 'new! the original',
 'korean hallasan lava',
 'sosis bakar merah',
 'donic table top',
 'cheese croffle',
 'pisang goreng chocolate',
 'special cookies n',
 'koyo cabe 1',
 'hainan chicken rice',
 'blue squash',
 'paket geprek 2',
 'bay fresh air',
 'roti sisir coklat',
 'sweet kit 2',
 'momo',
 'pancong milo l',
 'blubery',
 'special meji mentai',
 'nasi campur',
 'fettucine parmigiana',
 'yummy 1',
 'paket m3',
 'bantalan target jerami',
 'sambal teri ijo',
 'yakitori',
 'noodle 1',
 'vanilla white rabbit',
 'kuini',
 'ikan tuna cube',
 'ovaltine cheese',
 'double coklat',
 'cumi cabe garam',
 'mager weekend',
 'sucau/suboba',
 'kj telor asin',
 'sisri',
 'chocolate matcha',
 'roze topokki',
 'dimsum bakar',
 'mentai cheese',
 'lampu taman led/',
 'ice mint choco',
 'astamaya ice',
 'loyang besar kambing',
 'cheezu ebi roll',
 'kerui alarm rumah',
 'samurai burger set',
 'smart save popcorn',
 'bolu gulung kacang',
 'pisang goreng coklat',
 'cajun rub hot',
 'ecoflow new river',
 'baku bk',
 'beef yakiniku rice',
 'chiki ball ayam',
 'squash',
 'kwetiaw goreng',
 'tail salmon norwegia',
 'my boring station',
 'juice kuini susu',
 'tahu isi jamur',
 'milo o iced',
 'cheesy double beef',
 'telor omahan',
 'cumi sauce padang',
 'ara linen bed',
 'milo oreo blend',
 'burger+sosis',
 'bakso bakar/ goreng',
 'roti cream susu',
 'frozen passion fruit',
 'kispray kasturi pouch',
 'kebab komplit keju',
 'murmer nila goreng',
 'beer heinekken',
 'lemongrass pork chop',
 'burger jamet',
 'ice leci yakult',
 'sweet mozzarella medium',
 'geprek 1',
 'donic',
 'belgian chocolate almond',
 'paket cheeseburger medium',
 'rumput patimah',
 'paha geprek +',
 'mekosu',
 'cilok kuah pedas',
 'strawberry fruit cake',
 'candy manggo',
 'kopi tarik dingin',
 'gulungan senar pancing/layangan',
 'minyak tawon ee',
 'crispy sushi roll',
 'cdr rasa jeruk',
 'beef filone',
 'bk sip vanilla',
 'crinkle cut fries',
 'barrel swivel kili',
 'cilok spicy',
 'mozzarella package',
 'milkshake melon',
 'pudding nutrijell susu',
 'nasi gurih rendang',
 'happyfit court tennis',
 'bicopi gula aren',
 'hayylife tas pinggang',
 'nakopresso',
 'sarcas',
 '5 pcs mix',
 'roti coklat vanilla',
 'korean blueberry milk',
 'klasse pomegranate',
 'nila bakar kacang',
 'thanks a latte',
 'indomie kuah telur',
 'choco milk tea',
 'nasi 3t penyet',
 'helm anak perempuan',
 'chicken curry panini',
 'minty mango frappio',
 'pisang dikeramasin keju',
 'mochaccino',
 'yogurutea berry',
 'advan tab vx',
 'nastar toples segi',
 'bolu tape slice',
 'seven segment 0.56"',
 'masker duckbill 4d',
 'boneless wings 7',
 'lemon tea hot/',
 'roti klopo katulistiwa',
 'roti roll abon',
 'ikan baronang big,',
 'ice candy mojito',
 'paket berlima',
 'happy meal ayam',
 'chicken gyoza pizza',
 'permen jelly 1000',
 'md nyakitin',
 'original chocomaltine',
 'tas belanja lawson',
 'dimsum mix',
 'double garlic toast',
 'xiaomi walkie talkie',
 'paket hemat 3',
 'taucho tahu m',
 'murmer lele goreng',
 'mie gobyoss crabstick',
 'tim obat ayam',
 'donic edge tape',
 'french fries regular',
 'temptation cake',
 'cash drawer laci',
 'endmill hss (mata',
 'naga berry',
 'timurasa bubuk daun',
 'cheese ball chocomalt',
 'shrimp roll',
 'recurve bow anak',
 'indomie kuah daging',
 'banana roll tiramisu',
 'peperoni large',
 'loyang ayam sedang',
 'seblak pentol',
 'beli 1 gratis',
 'strawberry matcha latte',
 'ayam geprek 2',
 'tcl smart android',
 'es lidah buaya',
 'masker kn95 beli',
 'bika ambon coklat',
 'telur hijau dari',
 'selotip / isolasi',
 'dailymeal',
 'niji candy grape',
 'kerupuk kulit patin',
 'es durian',
 'original tea',
 'cookies sagon bakar',
 'milk weasel',
 'ikan kue pedas',
 'fogging liquid disinfektan',
 'dua croflle plus',

In [20]:
EXTERNAL_NAMES

['Warnet',
 'Iliardi',
 'Sapung',
 'Ice',
 'Andre',
 'Reni',
 'Palti',
 'Kadek',
 'Firda',
 'Kaefiyah',
 'Mahesti',
 'Siyama',
 'Amri',
 'Saka',
 'Merly',
 'W',
 'Kpu',
 'Erwan',
 'Sri',
 'Nopendi',
 'Safta',
 'Misbah',
 'Ruswanto',
 'Marsha',
 'Imah',
 'Arta',
 'Fitriya',
 'Nurzadian',
 'Salim',
 'Supiyo.sm',
 'M.azmien',
 'M.azmi',
 'Ny',
 'Siswo',
 'Ruhaeni',
 'Ima',
 'Khaeridah',
 'Anjar',
 'Risjal',
 'Gojali',
 'Albert',
 'Ria',
 'Boih',
 'Sutarman',
 'Fairuz',
 'Liana',
 'Hamdani',
 'Evi',
 'Zeha',
 'Djong',
 'Samto',
 'Amat',
 'Stasiun',
 'Yulia',
 'Djarotdjarotun',
 'Bobby',
 'Risa',
 'Sukiman',
 'Marhuma,',
 'Mamay',
 'Tasbehul',
 'Sanggar',
 'Tutik',
 'Jusup',
 'Barnoto',
 'Amirah/wariman',
 'Candra',
 'Sutarma',
 'Elaine',
 'Mulham',
 'Nurbiyantoni',
 'Ujang',
 'Yudi',
 'Tjong',
 'Mitha',
 'Wahyu',
 'Ansthelabel',
 'Edi',
 'Dybyo',
 'Yustina',
 'Gembah',
 'Djahidin',
 'Purwanta',
 'Willy',
 'Junaidi',
 'Lilis',
 'Ikn',
 'Nrfood',
 'Rismanita',
 'Ropika',
 'Elisa',
 'Chabib',
 '.muamar',
 'Martanto',
 'Junayyah',
 'Erinal',
 'Jerry',
 '.abdul',
 'Sunarwati',
 'Halison',
 'Syamsyuddin',
 'Muhamad',
 'Alimuddin',
 'Suto',
 'Rosyana',
 'Baderuddin,',
 'Nurliani',
 'Lesehan',
 'Ririn',
 'Jenal',
 'Riza',
 'Asai',
 'Sutra',
 'Martho',
 'Fabianus',
 'Sustriati',
 'Chang',
 'Duwi',
 '.',
 'Feri',
 'Tri',
 'Cibi',
 'Deni',
 'Mapul',
 'Sucipto',
 'Ali',
 'Wahyudin',
 'Anna',
 'Widia',
 'Irwandi.a,s.ag',
 'Masdia',
 'Zaenab',
 'Satiyah',
 'Siti',
 'Ha',
 'Erlina,',
 'Nanda',
 'Tika',
 'Denal',
 'Sumurbor',
 'Sonni',
 'Antonius',
 'A.faroqi',
 'Resman',
 'Lie',
 'Parahdiba.',
 'Darmawan',
 'Mardalinda',
 'Sukri',
 'Karsim',
 'Imam',
 'Infan',
 'Nikolaus.t',
 'Sanin',
 'N',
 'Muriyatin',
 'Simon',
 'Enjang',
 'Grafialdi',
 'Huzein',
 'Kalimasada',
 'Olipian',
 'Jaiti',
 'Naimun',
 'Marios',
 'Rudy',
 'Rudi',
 'Wahyudi',
 'Sanudin',
 'Barbara',
 'Dra',
 'Fariz',
 'Iswan',
 'John',
 'Jliteng',
 'Yenik',
 'Roly',
 'Oktalia',
 'Jimmi',
 'Adah',
 'Mirhan',
 'Moh',
 'I.g.a.a.m.',
 'Rizmar',
 'Fikri',
 'Ninix',
 'Toto',
 'Apendra',
 'Irfan',
 'Lis',
 'Darto',
 'Intan',
 'Iip',
 'Lazuardi',
 'Wandi',
 'Yeti',
 'Angelia',
 'Tuty',
 'Bayu',
 'Maad',
 'M.zaidi',
 'Ellianis',
 'Yasamudin',
 'Pede',
 'Rosmanidar,a',
 'Donal',
 'Catur',
 'Ebah',
 'Donna',
 'Kevin',
 'Linggo',
 'Pra',
 'Uta',
 'Rendi',
 'Cornelia',
 'Yysn',
 'Barak',
 'Saroya',
 'Febrian',
 'Ismanto',
 'Nevy',
 'Aryanto',
 'Tirta',
 'Dadan',
 'Netty',
 'Ridho',
 'Tnk',
 'Sugianto',
 'Christina',
 'Pipih',
 'Susanty',
 'Fakhrul',
 'Sukasah',
 'Davy',
 'Arja',
 'Krt',
 'Lysa',
 'Agnes',
 'Kel',
 'Nurleli',
 'Nuril',
 'Ulfah',
 'Julhadri',
 'Rudianto/ex',
 'Ramdani',
 'Siauw',
 'Petrus',
 'Entah',
 'Ira',
 'The',
 'Cartam',
 'Maryoline',
 'Gandhies',
 'Epon',
 'Priyanto',
 'Mario',
 '.abdussamad',
 'Afsah',
 'Arif',
 'Tato',
 'Mega',
 'Topan',
 'Elly',
 'R.ay.f',
 'Suwarno',
 '.m.yahya',
 'Koirul',
 'Indah',
 'Oloan',
 'Najmie',
 'Rokhmah',
 'Ramp',
 'Lim',
 'Surya',
 'Henrika',
 'Lily',
 'Debora',
 'Yoppie',
 'Ingin',
 'Tiara',
 'Wiwin',
 'Roslena',
 'Sunyoto',
 'Pebri',
 'Andrutama',
 'Hengky',
 'Husain',
 'Irpan',
 'Lisna',
 'Ariyanto',
 'Tomi',
 'Alfarino',
 'Zulkifli',
 'Dg',
 'Yanet',
 'Apriyonal',
 'Marcel',
 'Putu',
 'Hery',
 'R.dicky',
 'Fiktor',
 'Satrio',
 'Junih',
 'Mikardeno.',
 'Ansor',
 'Surodjo',
 'Ilham',
 'Syarif',
 'Tiarma',
 'Asmal',
 'Mhd.bawa',
 'Sapril',
 'Ardi',
 'Yanche',
 'Riwoto',
 'Mardjoni',
 'Kasdulah.,s.',
 '.zulkarnaini.s.',
 'Kemala',
 'Moh.febie',
 '.t',
 '.hm.adelan',
 'Novi',
 'Asropik',
 'Luluk',
 'Irsan',
 'Purnomo',
 'Yenny',
 'Fadel',
 'Tjioe',
 'Punawi',
 'Ardian',
 'Yohan',
 'Mar',
 'Zubeir',
 'Moh.',
 'Aslah',
 'Satriantos',
 'Gagang',
 'Efendi',
 'Anfal',
 'Denny',
 'Absar',
 'Aldoni',
 'Bedak',
 'Diki',
 'Yana',
 'Suroyono',
 'Suherman',
 'Desy',
 'Khoirol',
 'Kantin',
 'Deddy',
 'Rajiman',
 'Yati',
 'Sie',
 'Septian',
 'Kris',
 'Lucy',
 'Dl',
 'Julpikar',
 'Zacky',
 'Denni',
 'Warnas',
 'Chumairi',
 'Yetty',
 'Vivin',
 'Sela',
 'Suranto',
 'Saminah',
 'Tedy',
 'Silvana',
 'Aprijal',
 'Khoiri',
 'Fajarno',
 'Ngardam',
 'Janar',
 'Desfina',
 'Rica',
 '.r',
 'Dedi',
 'Muhammad.l',
 'Mulyadi',
 'Oskandar',
 'Dewantoro',
 'Herdinal.',
 'Syekh',
 'Rohman',
 'Tuadi',
 'Cua',
 'Noris',
 'Ijoe',
 'Kkota',
 'Damih',
 'Eka',
 'Ferry',
 'Pemli',
 'Kusniah',
 'Nisra',
 'Lukman',
 'Benyamin',
 "Sam'ani.",
 'Lumbubaratdmt',
 'Farianti',
 'Tgk',
 'Sapto',
 'Anggoro',
 'Fetri',
 'Herman',
 'Tris',
 'Abu',
 'Pompanisasi',
 'Sumiarni',
 'Sabar',
 'Leonard',
 'Suanli',
 'Suminah',
 'Alpian',
 'Aperinus',
 'Anggi',
 'Rahadian',
 'Agusstin',
 'Dede',
 'Ayu',
 'Rusadi/jetpump',
 'Khairil',
 'Yani',
 'T.m.',
 '.jajang',
 'Destro/johan',
 'Gilang',
 'Suprapti',
 'Marmidin',
 'Joni',
 'Witono',
 'Bernadus',
 'Susilahayati',
 'Sandy',
 'Miftahahul',
 'Novianti',
 'Eryani',
 'Ervin',
 'Joko',
 'Iis',
 'Mgs',
 'Kusyanto',
 'Distriati',
 'Fakih',
 'La',
 'Patolik',
 'Dewa',
 'Olt',
 'Sarang',
 'Fitriani',
 'Mcr',
 'Lindya',
 'Kamsiah',
 'M',
 'Hanum',
 'Puthut',
 'Untung',
 'Haryoko',
 'Sudirman',
 'Alpiyah',
 'Asep',
 'Ruslan',
 'Oey',
 'Lilik',
 'Hadi',
 'Elyusrita',
 'Noor',
 'Drh..basir',
 'Lukito',
 'Yusak',
 'Dina',
 'Nita',
 'Riyanta',
 'Zahidin',
 'Amin',
 'Mas',
 'Aidi',
 'Solihatin',
 'Uma',
 'Al',
 'Falta',
 'Grinda',
 'Azkia',
 'Betra',
 'Iin',
 'Meng',
 'Lasenianto',
 'Atan',
 'Syambahari',
 'Dida',
 'Saeful',
 'Apin',
 'Nilawati',
 'Junario',
 'Nurmaini',
 'Irma',
 'Saneci',
 'Kusnadi',
 'Pius',
 'Muzakir',
 'Venilia',
 'Arie',
 'Salman',
 'Robiah',
 'Ambo',
 'M.robby',
 'Artini',
 'Uniek',
 'Toserba',
 'Bona',
 'Dulwarman',
 'Yogen',
 'Esau',
 'Jumaidah',
 'Isninjar',
 'Paula',
 'Herlika',
 'Fipin',
 'Ry',
 'Tjoeng',
 'Prayitno',
 'Baharuddin',
 'Kodirul',
 'Mohamad',
 'Reka',
 'Fadhlan',
 'Yys',
 'I',
 'Pranyono',
 'Maulud',
 'Dewiyanto',
 'Renaldo',
 'Dini',
 'Sukamto',
 'Gito',
 'Windah',
 'Rampeani',
 'Ikbal',
 'Ratim',
 'Elisabeth',
 'Santoso',
 'Cut',
 'Aam',
 'Sudaryanti',
 'Rila',
 'Arthur',
 'Pamsimas',
 'Sonhaji',
 'Pranoto',
 'Eddy',
 'Mansur',
 'Khalimi',
 'Patonah',
 'Pnpm',
 'Habarudin',
 'Lawidin',
 'Anom',
 'Kuswa',
 'Memed',
 'Ernawati.ii',
 'Ibu',
 'Mumuh',
 'Refrizal',
 'Zarmili',
 'Aditya',
 'Dani',
 'Lajuardi',
 'Surasit',
 'Puput',
 'Ading',
 'Suroso',
 'Siduhu',
 'Laiman',
 'Slamet',
 'Cici',
 'Anip',
 'Ni',
 'Nabrawi',
 '.achmad',
 'Enti',
 'Lai',
 'Anang',
 'Cecep',
 'Nony',
 'Ibrahim',
 'Daslim',
 'Resdawita',
 'Nani',
 'Widi',
 'Salvida',
 'Sumriyah.',
 'Cing',
 'Oei',
 'Tarsi',
 'Apri',
 'Jalidin',
 'Asmiyani',
 'Satya',
 'Toni',
 'Suyit',
 'Sawin',
 'Rumadja',
 'Yayuk',
 'Suaib',
 'Arbiah',
 'Pino',
 'Apil',
 'Jajang',
 'Refda',
 'Herianto',
 'Maya',
 'Rochadi',
 'Veronika',
 'Dadang',
 'Muhammat',
 'Yogi',
 'Dawam',
 'Dindin',
 'Endang',
 'Arum',
 'Saiful',
 'Heri',
 'Jenab',
 'Fajrun',
 'Hinsatopa',
 'Micky',
 'Yumadi.',
 'Sus',
 'W.sadiarka',
 'Ivan',
 'Apip',
 'Kho',
 'P',
 'Yoggie',
 'Dalperef',
 'Ida',
 'Neneng',
 'Maria',
 'Ramin',
 'Pradanarian',
 'Khabib',
 'Sigit',
 'Dike',
 'Samsudin.',
 'Soeparno,',
 'Jonner',
 '.siti',
 'Silmi',
 'Yudis',
 'Kembar',
 'Herwin',
 'Kamril',
 'Ullin',
 'Susana',
 'Eryvawati',
 'Irwan',
 'Anjasmara',
 'Lira',
 '.agus',
 'Purwaheni',
 'Lathifatul',
 'Febri',
 'Kartiyah',
 'Faiz',
 'Amirin',
 'Pengadayan',
 'Desak',
 'Jamroni',
 'Usaha',
 'Susy',
 'Neng',
 'Unu',
 'Irigasi',
 'Yunita',
 'Auliak',
 'Radikin',
 'Dedrinaldi',
 'Wahidul',
 'Sihrini',
 'Yuzab',
 'Nurhadita',
 'Kadang',
 'Sriono',
 'Lay',
 'Sani',
 'Adam',
 'George',
 'Upik',
 'Komang',
 'Pawit',
 'Arfin',
 'Reinhard',
 'Ervina',
 'Rocky',
 'Fellix',
 'Rahmad',
 'Hapiluddin',
 'Sutjipto',
 'Asbolah/naga',
 'Waluyo',
 'Aulia,',
 'Bachtiar',
 'Rizal',
 'Iyan',
 'Gede',
 'Fathan',
 'Iyah,',
 'Rafi',
 'Rifki',
 'Safawi',
 'Fitri',
 'Trindo',
 'Dedy',
 'Basuki',
 'Michael',
 'Ahmad',
 'Hasbullah',
 'Johanuri.e',
 'Kiki',
 'Akhmad',
 'Adek',
 'Dian',
 'Subahi',
 'Ruhimat',
 '.yeni.m.',
 'Embunf',
 'Tenri',
 'Ari',
 'Sukli',
 'Marlius',
 'Toyibul',
 'Phiong',
 'J',
 'Mardaliza',
 'Zul',
 'Nursa',
 'Murliana',
 'Darwin',
 'Ayin',
 'Adi',
 'Ramli',
 'Dedeh',
 'Vonirah',
 'A',
 'Dmt_tsel_sel144_aikmel2',
 'Fiki',
 'Bambang',
 'Apdial',
 'Agit',
 'Wiryono',
 'Grace',
 'Las',
 'M.nasrulloh',
 'Gunadi',
 'Maryuliza',
 'Anwar',
 'Naryo',
 'Wp.saragih',
 'Iwan',
 'Percetakan',
 'Agunawan',
 'Hari',
 'Djahroni',
 'Dra.',
 'Yusup',
 'Gatut',
 'Samsul',
 'Apririanti',
 'Low',
 'Nanik',
 'Rifai',
 'Adabi',
 'Mundari',
 'Moch.',
 'J.pardede',
 'Angky',
 'Sitti',
 'Darcim',
 'Danil',
 'Rudian',
 'Tjoe',
 'Albasi',
 'Amrul',
 'Yuli',
 'Iskandar',
 'Sahala.m.lbn.tobing',
 'Eman',
 'Kasmi',
 'Ely',
 'Toha,',
 'Syahrir',
 'Trisilo',
 'Miyar',
 'Mubarizi',
 'Katimun',
 'Mar,ati',
 'Riki',
 'Zaenal',
 'Wong',
 'Andi',
 'Bong',
 'Mediansyah',
 'Achmad',
 'Abie',
 'Rinny',
 'Zaenudin',
 'Zulhakim',
 'Nurdin',
 'Fera',
 'Usniyati',
 'Erna',
 'Sugihono',
 'R.',
 'Selah',
 'Warsiah',
 'Asman',
 'Hendrianto',
 'Yonaldi',
 'Lukmana',
 'Kilang',
 'Aris',
 'Alamsyah',
 'Eli',
 'Pembenihan',
 'Wendy',
 'Asnawi',
 'Wahib',
 'Handri',
 'Zeth',
 'Sholihul',
 'Nurlis',
 'Dwi',
 'Rusdi',
 'Mokhamad',
 'Erika',
 'Entong',
 'Sungudi',
 'Budi',
 'Yanih',
 '.pahruddin',
 'Sariyem/blok',
 'Cahaya',
 'Elyasni',
 'Rino',
 'Los',
 'Yakiman',
 'Ning',
 'Akhmad.e',
 'Ani',
 'Hendra',
 'Syaeful',
 'Wawan',
 'Loli',
 'Samsudi',
 'Maniso.a',
 'Melyn',
 'Indra',
 'Dila',
 'Rulisan',
 'Katrin',
 'Nur',
 'Elygia',
 'Momiyardi',
 'Eva',
 'Dicky',
 'Wirta',
 'Ragil',
 'Setya',
 'Andhi',
 'Melly',
 'Mahmani',
 'Bidan',
 'Trides',
 'Jali',
 'Arry',
 '.hanafiah',
 'Zamhur',
 'David',
 'Pam',
 'Rustam',
 'Herian',
 'Sukardi',
 'Hi.',
 'Enok',
 'Desi',
 'Yasid',
 'Efri',
 'Sulaiman',
 'Kenod',
 'B',
 'Harton',
 'Rosmayuni',
 '.sujana',
 'Anton',
 'Posman',
 'Deetje',
 'Syaiful',
 'Purna',
 'Sofwatunnisa',
 'Rubby',
 'Sukaeni',
 'Nurul',
 'Darmita',
 'Emilatus',
 'Risda',
 'Suyono',
 'Idm',
 'Sepniwati',
 'Maita',
 'Bahtiar',
 'Ester',
 'Pimping',
 'Syahid',
 'Juliana',
 'Deden',
 'Marianie',
 'Ilyas',
 'Heuleur',
 'Cathalina',
 'Alwi',
 'Helmi',
 'Elvison',
 'Elia',
 'Damryanto',
 'Bintang',
 'Mimin',
 'Jhonny',
 "Arba'ien",
 'Kelik',
 'L.',
 'Hendrik',
 'Sukartinah',
 'Chris',
 'Sardy',
 'Munzir',
 'Isnuari',
 'Kliwon/peg',
 'Safaruddin',
 'Novianto',
 'Otong',
 'Chitra',
 '.nurohmah',
 'Saud',
 'A.agung',
 'Noviyatul',
 'Arifin',
 'Ifkal',
 'Bimantoro',
 'Rafail',
 'M.',
 'Belina',
 'Joeki',
 'Reservoir',
 'Vivi',
 'Binsar',
 'Long',
 'Sumerta',
 'Halid',
 'Syupriyanto',
 'Ratih',
 'Riyana',
 'Paeman',
 'Sutirah/sumiatun',
 'Wella',
 'Alni',
 'Lo',
 'M.r',
 'Yatminah',
 'Dyoungs',
 'Itin',
 'Aries',
 'Jesnos',
 'Claudia',
 'Nurzajefry.',
 'Septiono',
 'Siwi',
 'Sahrijal',
 'Rama',
 'Herry',
 'Heru',
 'Dewi',
 'Kurniatie',
 'Armunandar',
 'Bagus',
 'Yasir',
 'Hira',
 'Khaisal',
 'Muh',
 'Purkon',
 'Jamalus',
 'Misno',
 'Seleman',
 'Kua',
 'Wiji',
 'Muhammad',
 'Eko',
 ...]

In [21]:
EXTERNAL_NAMES = [name.strip('.,/ ').capitalize() for name in EXTERNAL_NAMES if len(name) > 2 and name.lower() not in ['warnet', 'stasiun', 'kpu', 'ikn', 'bidan']]

In [22]:
print(f"Loaded {len(EXTERNAL_NAMES)} clean names and {len(EXTERNAL_ITEMS)} items!")

Loaded 1194 clean names and 23802 items!

In [24]:
def generate_random_price():
    slang = ["cepek", "goban", "gocap", "seceng", "cenggo", "goceng", "pekgo"]
    if random.random() < 0.2:
        return random.choice(slang)
    
    formats = [
        lambda: f"{random.randint(10, 500)}k",
        lambda: f"{random.randint(10, 500)} ribu",
        lambda: f"{random.randint(10, 500)}rb",
        lambda: f"{random.randint(1, 9)}.{random.randint(1,9)}jt",
        lambda: f"{random.randint(10, 999)}.000"
    ]
    return random.choice(formats)()

In [25]:
def build_massive_dataset(templates_file, output_file, multiplier=100):
    with open(templates_file, 'r', encoding='utf-8') as f:
        templates = json.load(f)
        
    augmented_data = []
    
    for template in templates:
        for _ in range(multiplier):
            new_text = template["raw_text"]
            new_entities = []
            replacements = {}
            
            for ent in template["entities"]:
                placeholder = ent["value"]
                ent_type = ent["entity"]
                
                if placeholder not in replacements:
                    if "PERSON" in placeholder:
                        replacements[placeholder] = random.choice(EXTERNAL_NAMES)
                    elif "ITEM" in placeholder:
                        replacements[placeholder] = random.choice(EXTERNAL_ITEMS)
                    elif "PRICE" in placeholder:
                        replacements[placeholder] = generate_random_price()
                    else:
                        replacements[placeholder] = placeholder
                
                new_entities.append({
                    "entity": ent_type,
                    "value": replacements[placeholder]
                })
            
            for placeholder, actual_value in replacements.items():
                new_text = new_text.replace(placeholder, str(actual_value))
                
            augmented_data.append({
                "raw_text": new_text,
                "entities": new_entities
            })
            
    random.shuffle(augmented_data)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(augmented_data, f, indent=2, ensure_ascii=False)
        
    print(f"created {len(augmented_data)} rows")

In [28]:
build_massive_dataset("talangin_synthetic_templates.json", "training_data.json", multiplier=10)

created 24900 rows